### ISSUE TITLE
Squirrel installer targeting wrong directory and fails with "out of memory"

### ISSUE THREAD

**Issue by hstraf9** [phw198/OutlookGoogleCalendarSync#1002]
The installer setup for all versions,  including alpha and beta,  fails with a popup error (I attached the screenshot of the error popup) that says:

```
Installation has failed

There was an error while installing the application.
Check the setup log for more information and contact the author.
```

I click the "Open Setup Log" button, and this is the information presented in the SquirrelSetup.log file:

```
2019-12-29 13:21:13> Program: Starting Squirrel Updater: --install .
2019-12-29 13:21:13> Program: Starting install, writing to C:\Users\Admin\AppData\Local\SquirrelTemp
2019-12-29 13:21:13> Program: About to install to: C:\Users\Admin\AppData\Local\inSSIDer
2019-12-29 13:21:13> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\AppData\Local\inSSIDer\packages\.betaId'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2019-12-29 13:21:13> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\AppData\Local\inSSIDer\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2019-12-29 13:21:13> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Admin\AppData\Local\SquirrelTemp
2019-12-29 13:21:13> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2019-12-29 13:21:13> ApplyReleasesImpl: Writing files to app directory: C:\Users\Admin\AppData\Local\inSSIDer\app-5.1.12
2019-12-29 13:21:14> LogHost: Rigging execution stub for inSSIDer_ExecutionStub.exe to C:\Users\Admin\AppData\Local\inSSIDer\inSSIDer.exe
2019-12-29 13:21:21> LogHost: Rigging execution stub for rwatch32_ExecutionStub.exe to C:\Users\Admin\AppData\Local\inSSIDer\rwatch32.exe
2019-12-29 13:21:21> LogHost: Rigging execution stub for rwatch64_ExecutionStub.exe to C:\Users\Admin\AppData\Local\inSSIDer\rwatch64.exe
2019-12-29 13:21:22> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Admin\AppData\Local\inSSIDer\app-5.1.12\inSSIDer.exe]
2019-12-29 13:21:24> ApplyReleasesImpl: Starting fixPinnedExecutables
2019-12-29 13:21:25> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2019-12-29 13:21:25> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2019-12-29 13:21:25> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2019-12-29 13:21:25> ApplyReleasesImpl: Examining Pin: Viber.lnk
2019-12-29 13:21:25> ApplyReleasesImpl: Fixing up tray icons
2019-12-29 13:21:25> ApplyReleasesImpl: cleanDeadVersions: for version 5.1.12
2019-12-29 13:21:25> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-5.1.12
2020-06-02 19:30:58> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2020-06-02 19:39:18> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2020-06-02 19:40:28> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2020-06-03 11:25:03> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2020-06-03 11:25:13> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2020-06-03 11:28:33> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2020-06-03 11:32:17> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
2020-06-03 11:36:48> Unhandled exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

I am running Windows 10 with all updates installed.

I am happy to help if possible. Just let me know if any additional information is needed.  Thanks.

![Annotation 2020-06-03 114050](https://user-images.githubusercontent.com/66384595/83676177-1b96de80-a58f-11ea-8d22-9ba5e0210c7c.jpg)

**Comment by phw198** [comment]
Hi, you sure you're posting to the right project? Looks like your logs show you installing **inSSIDer**...

**Comment by hstraf9** [comment]
Hello,

That's the mystery of it!   I downloaded the setup file (alpha version first), and ran that.    Then I tried it with the beta version, and got the same problem.  

I can confirm 100% that the file I downloaded from the repository is the one that I ran…    I have no idea why it's referencing the inSSIDer software (which I have installed on my laptop previously).

Just to confirm, I tried it again right now.. I click the download link on the website to download the alpha version, and then ran it directly from the browser instead of Windows Explorer.  (ie: The little square in the bottom of the IE browser, which shows the file that was just downloaded.)

I hope that makes sense.

Any suggestions or ideas what might be the problem?

Thanks!

**Comment by phw198** [comment]
I think there could be some weird file link/shortcut going on in your downloaded items folder. Could you download from OGCS website and save the file to a folder with nothing else in it, then try and execute from there?

**Comment by hstraf9** [comment]
Hello,

I downloaded the setup file into a completely new folder, but the same problem occurred.  

It's ok, though.  I was able to get the portable version working with no problem, so I will use that one.

Thanks!

**Comment by phw198** [comment]
I know you're using the portable release of OGCS now instead, but the next things I would have suggested:
1. Delete the `%LocalAppData%\SquirrelTemp` directory first, see if it makes any difference
1. If not, and you're not using inSSIDer uninstall it or delete `%LocalAppData%\inSSIDer` and also repeat step 1 again.

Assuming you're happy using the portable version though, I'll probably close this ticket soon.
