### ISSUE TITLE
Deleted Duplicate Entry in Calendar, Keep Getting 410 Gone Error

### ISSUE THREAD

**Issue by devconfirm** [phw198/OutlookGoogleCalendarSync#1038]
**Are you already using OGCS?**
Just upgraded to 2.8.4.0. Was using 2.8.0.0 before that.

**Describe the question you have**
I had a recurring event created in Google by someone in the same organization, and I was one of the participants. I accepted in Outlook 2019. After accepting it I saw 2 copies of the event in **OUTLOOK** (EDIT: sorry, not Google Calendar) (I think this program created another copy rather than syncing the original one). To avoid confusion I deleted the duplicate entry in **OUTLOOK** . Now, after every sync I receive the following error:

Deleted event failed to remove.
Resource has been deleted [410=Gone]

This produces a popup asking me if I want to continue during every sync.
I am on O<->G sync mode. I tried doing a Full Sync after changing to a one-way sync mode. Same result.
I see the recurring meeting both on Outlook and Google Calendar fine.
Is there at least a way to ignore the errors, and let it continue syncing if I cannot remove this deleted event?

**Edit 1:** 
Duplicate entry was in Outlook, not in GC.

In sync settings only "merge with existing entries" is checked.

Here is the even log when failure happens:
```
2020-07-08 10:18:17,959 INFO  18 OutlookGoogleCalendarSync.Console [0] -  Syncing Outlook → Google
2020-07-08 10:18:18,212 DEBUG  18 OutlookGoogleCalendarSync.Console [0] -  Checking for orphaned items
2020-07-08 10:18:18,284 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Scanning 8 Google events for orphans to reclaim...
2020-07-08 10:18:18,319 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  0 unclaimed.
2020-07-08 10:18:18,319 DEBUG  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Comparing Outlook items to Google events...
2020-07-08 10:18:18,320 INFO  18 OutlookGoogleCalendarSync.Console [0] -  Matching calendar items...
2020-07-08 10:18:18,930 INFO  18 OutlookGoogleCalendarSync.Console [0] -  1 Google calendar entries to be deleted.
2020-07-08 10:18:18,930 INFO  18 OutlookGoogleCalendarSync.Console [0] -  0 Google calendar entries to be created.
2020-07-08 10:18:18,931 INFO  18 OutlookGoogleCalendarSync.Console [0] -  7 calendar entries to be compared.
2020-07-08 10:18:18,949 INFO  18 OutlookGoogleCalendarSync.Console [0] -  Deleting 1 Google calendar entries
2020-07-08 10:18:19,203 DEBUG  18 OutlookGoogleCalendarSync.Console [0] -  7/3/2020 8:00 AM   "COLT Meeting"
2020-07-08 10:18:19,514 WARN  18 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Resource has been deleted [410]
Errors [
	Message[Resource has been deleted] Location[ - ] Reason[deleted] Domain[global]
]

2020-07-08 10:18:19,515 ERROR  18 OutlookGoogleCalendarSync.Console [0] -  Deleted event failed to remove.
2020-07-08 10:18:19,518 ERROR  18 OutlookGoogleCalendarSync.Console [0] -  Resource has been deleted [410=Gone]
2020-07-08 10:18:19,584 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  Google.GoogleApiException: Google.Apis.Requests.RequestError
Resource has been deleted [410]
Errors [
	Message[Resource has been deleted] Location[ - ] Reason[deleted] Domain[global]
]

2020-07-08 10:18:19,587 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131500;-2146233088
2020-07-08 10:18:19,587 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -     at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.deleteCalendarEntry_save(Event ev)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.DeleteCalendarEntries(List`1 events)
2020-07-08 10:18:25,815 INFO  18 OutlookGoogleCalendarSync.Sync.Engine [0] -  User chose not to continue sync.
2020-07-08 10:18:31,350 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  User opted to abandon further syncs.
2020-07-08 10:18:31,351 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Sync aborted after 1 failed attempts!
2020-07-08 10:18:31,414 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Value cannot be null.
Parameter name: value
2020-07-08 10:18:31,415 DEBUG  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Create the timer for the push synchronisation
```
**Edit 2:** I disabled deleting synced items, and deleted the Outlook copy of the event. I then synced G->O hoping that I would get the correct fresh copy of the event from Google Calendar. It created 2 identical Outlook events just like the first time :(  I also now have 2 events in google Calendar. I deleted duplicate in Google, and synced one last time. 1 seem to have 1 copy on both sides. Fingers crossed.

**Edit 3:** Nope. Happened again. I declined a meeting which is deleted in Outlook. I keep seeing 410 error with an annoying popup. Log:

```
2020-07-17 13:31:51,381 DEBUG  5 OutlookGoogleCalendarSync.Sync.Engine [0] -  Synchronising from Outlook to Google.
2020-07-17 13:31:51,382 INFO  5 OutlookGoogleCalendarSync.Console [0] -  Syncing Outlook → Google
2020-07-17 13:31:51,635 DEBUG  5 OutlookGoogleCalendarSync.Console [0] -  Checking for orphaned items
2020-07-17 13:31:51,710 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Scanning 16 Google events for orphans to reclaim...
2020-07-17 13:31:51,796 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  0 unclaimed.
2020-07-17 13:31:51,796 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Comparing Outlook items to Google events...
2020-07-17 13:31:51,796 INFO  5 OutlookGoogleCalendarSync.Console [0] -  Matching calendar items...
2020-07-17 13:31:52,025 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [0] -  7/21/2020 10:15 AM => "MANDATORY Training"
2020-07-17 13:31:52,025 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [0] -  OGCSmodified=20200717122937
2020-07-17 13:31:52,025 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [0] -  outlook_CalendarID=0000000094CB97820D029940892FF0xxxx
2020-07-17 13:31:52,025 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [0] -  outlook_EntryID=0000000094CB97820D029940892xxxx
2020-07-17 13:31:52,026 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.CustomProperty [0] -  outlook_GlobalApptID=040000008200E00074C5B7101xxxx
2020-07-17 13:31:52,932 INFO  5 OutlookGoogleCalendarSync.Console [0] -  1 Google calendar entries to be deleted.
2020-07-17 13:31:52,932 INFO  5 OutlookGoogleCalendarSync.Console [0] -  0 Google calendar entries to be created.
2020-07-17 13:31:52,932 INFO  5 OutlookGoogleCalendarSync.Console [0] -  15 calendar entries to be compared.
2020-07-17 13:31:53,028 INFO  5 OutlookGoogleCalendarSync.Console [0] -  Deleting 1 Google calendar entries
2020-07-17 13:31:53,299 DEBUG  5 OutlookGoogleCalendarSync.Console [0] -  7/20/2020 1:00 PM   "Preparation for Audit Phase 2"
2020-07-17 13:31:53,571 WARN  5 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Resource has been deleted [410]
Errors [
	Message[Resource has been deleted] Location[ - ] Reason[deleted] Domain[global]
]

2020-07-17 13:31:53,571 ERROR  5 OutlookGoogleCalendarSync.Console [0] -  Deleted event failed to remove.
2020-07-17 13:31:53,572 ERROR  5 OutlookGoogleCalendarSync.Console [0] -  Resource has been deleted [410=Gone]
2020-07-17 13:31:53,608 ERROR  5 OutlookGoogleCalendarSync.OGCSexception [0] -  Google.GoogleApiException: Google.Apis.Requests.RequestError
Resource has been deleted [410]
Errors [
	Message[Resource has been deleted] Location[ - ] Reason[deleted] Domain[global]
]

2020-07-17 13:31:53,609 ERROR  5 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131500;-2146233088
2020-07-17 13:31:53,610 ERROR  5 OutlookGoogleCalendarSync.OGCSexception [0] -     at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.deleteCalendarEntry_save(Event ev)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.DeleteCalendarEntries(List`1 events)
2020-07-17 13:31:55,485 INFO  5 OutlookGoogleCalendarSync.Sync.Engine [0] -  Done.
```

**Comment by phw198** [comment]
Thanks for raising this @devconfirm and the detailed information provided - although it's better than that on #1060, there's more activity on that ticket and I've posted a hotfix there that I'm hoping should fix this issue.
