### ISSUE TITLE
Failed to retrieve recurring events. Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by tobiasrenkin** [phw198/OutlookGoogleCalendarSync#1082]
**OGCS Version**: v2.8.4.0  
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
When I try to sync, I get the following error:

```
Failed to retrieve recurring events
Value cannot be null. Parameter name: source
```

The sync mostly works even though it quits with an error. The only thing that does not work are exceptions to recurring events.

**Any other information**  
Here is the relevant part of the log file:
```
2020-09-08 17:03:27,302 DEBUG  22 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 9/7/2020 13:00 (R) => "My weekly meeting"
2020-09-08 17:03:27,304 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -  Creating Google iCalendar definition for recurring event.
2020-09-08 17:03:27,312 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -  RRULE:FREQ=WEEKLY;UNTIL=20210607T130000Z
2020-09-08 17:03:27,334 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -  9/7/2020 13:00 (R) => "My weekly meeting"
2020-09-08 17:03:27,336 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring appointment with 2 exceptions that will now be iteratively compared.
2020-09-08 17:03:27,386 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -  Finding Google instance for Outlook exception:-
2020-09-08 17:03:27,387 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -    Original date: 07/09/2020
2020-09-08 17:03:27,395 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -    Current  date: 07/09/2020
2020-09-08 17:03:27,400 DEBUG  22 OutlookGoogleCalendarSync.Recurrence [0] -  Google exception event is not cached. Retrieving all recurring instances...
2020-09-08 17:03:27,400 DEBUG  22 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving all recurring event instances from Google.
2020-09-08 17:03:27,563 ERROR  22 OutlookGoogleCalendarSync.Console [0] -  Failed to retrieve recurring events
2020-09-08 17:03:27,588 ERROR  22 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Error while copying content to a stream.
2020-09-08 17:03:27,620 ERROR  22 OutlookGoogleCalendarSync.Console [0] -  Unable to update existing entries in the Google calendar.
2020-09-08 17:03:27,621 ERROR  22 OutlookGoogleCalendarSync.Console [0] -  Value cannot be null.
2020-09-08 17:03:27,622 ERROR  22 OutlookGoogleCalendarSync.Console [0] -  Parameter name: source
2020-09-08 17:03:27,838 ERROR  22 OutlookGoogleCalendarSync.OGCSexception [0] -  System.ArgumentNullException: Value cannot be null.
Parameter name: source
2020-09-08 17:03:27,839 ERROR  22 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2020-09-08 17:03:27,840 ERROR  22 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at OutlookGoogleCalendarSync.Recurrence.getGoogleInstance(Exception& oExcp, String gRecurringEventID, String oEntryID, Boolean dirtyCache)
   at OutlookGoogleCalendarSync.Recurrence.UpdateGoogleExceptions(AppointmentItem ai, Event ev, Boolean dirtyCache)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
   at OutlookGoogleCalendarSync.Sync.Engine.outlookToGoogle(List`1 outlookEntries, List`1 googleEntries, String& bubbleText)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass20_0.<Start>b__0(Object o, DoWorkEventArgs args)
2020-09-08 17:03:27,840 ERROR  22 OutlookGoogleCalendarSync.Console [0] -  Value cannot be null.
2020-09-08 17:03:27,841 ERROR  22 OutlookGoogleCalendarSync.Console [0] -  Parameter name: source
2020-09-08 17:03:34,762 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  User opted to abandon further syncs.
2020-09-08 17:03:34,765 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Sync aborted after 1 failed attempts!
```

**Comment by phw198** [comment]
Hi @tobiasrenkin Was this issue reproducible, or just a one off? Seems the main problem was a "Error while copying content to a stream." error being returned by Google so I'm not sure if it was transient.
 
:package: However, please try [hotfix v2.8.5.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5471425/v2.8.5.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes!

**Comment by phw198** [comment]
Any feedback @tobiasrenkin?
