### ISSUE TITLE
Two-way sync outlook error - remote procedure call failed

### ISSUE THREAD

**Issue by Yeznick** [phw198/OutlookGoogleCalendarSync#1102]
**OGCS Version**: v2.8.4.0 
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
When syncing two-way, there is an error "New appointment failed to save. The remote procedure call failed. (Exception from HRESULT: 0x800706BE)"

**Steps to Reproduce the Issue**  
1. change from one-way Outlook -> Google to two-way Outlook <-> Google
2. sync
3. when app tries to write events from Google to Outlook, error apears "New appointment failed to save. The remote procedure call failed. (Exception from HRESULT: 0x800706BE)"

**This is an error in log file:**
```
2020-10-20 10:32:49,005 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Saving timestamp when OGCS updated appointment.
2020-10-20 10:32:49,027 FINE  23 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  Set userproperty OGCSmodified=20.10.2020 10:32:49
2020-10-20 10:32:57,000 ERROR  23 OutlookGoogleCalendarSync.Console [0] -  New appointment failed to save.
2020-10-20 10:32:57,001 ERROR  23 OutlookGoogleCalendarSync.Console [0] -  The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
2020-10-20 10:32:57,030 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The remote procedure call failed. (Exception from HRESULT: 0x800706BE)
2020-10-20 10:32:57,030 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x800706BE;-2147023170
2020-10-20 10:32:57,030 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.Save()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.createCalendarEntry_save(AppointmentItem ai, Event& ev)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.CreateCalendarEntries(List`1 events)
```

**Comment by phw198** [comment]
Does this error occur for every single sync? If so, is it failing for the same Outlook item every time?

Normally, `0x800706BE` just means Outlook has crashed or been restarted in the middle of an OGCS sync. I would expect subsequent syncs to work OK...

**Comment by Yeznick** [comment]
It occurs everytime there is a new event to be added from Google to Outlook. It is also evident, that Outlook crashes, because when I confirm the error, Outlook is restarted.

**Comment by phw198** [comment]
Unfortunately, I don't think there's not much I can do about this - the error code is informing that Outlook is/has crashed, and if this is caused by programmatic adding of a new calendar item, this is likely due to an issue with your Outlook installation or account profile.

As a test, you could try syncing from a new Google calendar to a new Outlook calendar and just place one very simple item in Google? If that still makes Outlook crash, I'd probably suggest [recreating your Outlook profile](https://itservicecentre.derby.ac.uk/hc/en-us/articles/201892111-Recreating-an-Outlook-profile) and/or reinstalling Outlook.
