### ISSUE TITLE
Zimbra corrupts LastModificationDate - "Not a legal OleAut date"

### ISSUE THREAD

**Issue by cjm571** [phw198/OutlookGoogleCalendarSync#1118]
**OGCS Version**: v2.8.0beta and v2.8.5alpha
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  
Sync of an event encounters an error for "Not a legal OleAut date." and creates a popup window. The event sync "succeeds" in that it shows up on my GCal, but I get the error window every time. I would like a way to suppress the pop-ups.

**Steps to Reproduce the Issue**  
Occurs when syncing automatically and manually.

**Any other information**  
I've attempted the sync with all of the date formats provided in the Outlook tab, same behavior

See timestamp 2020-11-10 13:35:33,811 in the log for the attempt I made with logging set to "All".

:paperclip: [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5520073/OGcalsync.log)

**Comment by phw198** [comment]
Looks like you have a corrupted Outlook item - basically it's not possible to access the `LastModificationTime` attribute from the `11/11/2020 1:30 PM  "Jira Planning for Peregrine"` appointment.

```
2020-11-10 13:35:33,811 ERROR  7 OutlookGoogleCalendarSync.Console [277] -  11/11/2020 1:30 PM  "Jira Planning for Peregrine"
2020-11-10 13:35:33,814 ERROR  7 OutlookGoogleCalendarSync.Console [277] -  Event update failed.
2020-11-10 13:35:33,816 ERROR  7 OutlookGoogleCalendarSync.Console [277] -  Not a legal OleAut date.
2020-11-10 13:35:33,880 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentException: Not a legal OleAut date.
2020-11-10 13:35:33,881 ULTRA-FINE  1 OutlookGoogleCalendarSync.Console [189] -  Console navigating.
2020-11-10 13:35:33,883 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80070057,-2147024809; Location: ConvertToManaged() in <Unknown File>
2020-11-10 13:35:33,885 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.StubHelpers.DateMarshaler.ConvertToManaged(Double nativeDate)
   at Microsoft.Office.Interop.Outlook._AppointmentItem.get_LastModificationTime()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 579
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 512
```

Workarounds might be to 
* manually make an edit to the appointment and save it to force a new modification time.
* assign it a "don't sync" category and exclude that in OGCS settings

**Comment by cjm571** [comment]
Thanks for the response.

I'll try the manual edit next time this pops up, although it does seem to happen quite regularly and with random appointments. I'll grab some more logs next time it recurs.

**Comment by phw198** [comment]
Any further update or can this issue be closed out now?

**Comment by cjm571** [comment]
Thanks for following up - this fell through the cracks for me.

Yeah, I'm still seeing the issue, attached another log with an occurrence of it (Sync started at line 684, error occurred at line 730).

Is it possible that my company's email server is misconfigured? We use Zimbra as our backend to Outlook, which has always felt very much like a "lowest bidder" sortof option...
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5871150/OGcalsync.log)

**Comment by phw198** [comment]
Funny you should mention Zimbra - when Googling just now, [this came up](https://forums.zimbra.org/viewtopic.php?t=31029). Unfortunately that's in 2013 and it would seem they are not interested in keeping to date formatting standards. If they break the built in `LastModificationTime` field on calendar items, there's really nothing I can do, sorry!

**Comment by cjm571** [comment]
Classic also-ran shenanigans 🙄 

Thanks for looking into this! I'll update if I manage to find a workaround at somepoint, but feel free to close or do as you please with this issue.

**Comment by phw198** [comment]
Thanks and yes, please do update if any further info comes to light! 

I will close this issue for now...
