### ISSUE TITLE
Some but not all Outlook Calendars found in OGCS 

### ISSUE THREAD

**Issue by Bri0r0** [phw198/OutlookGoogleCalendarSync#1164]
Using the latest version and some of my accounts are found but not the one I use. I tried moving it up in the list in the outlook calendar tab, setting it as the default email and data file, and reinstalling and resetting OGCS , any help would be appreciated! It is a business 365 account that I want to sync , thanks
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5919878/OGcalsync.log)

**Comment by phw198** [comment]
I'm pretty sure this is already fixed.

:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

----
Log extract:
```
2021-02-03 08:15:03,597 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Get the folders configured in Outlook
2021-02-03 08:15:03,599 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Finding Alternative Mailbox calendar folders
2021-02-03 08:15:03,612 WARN  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Failed to find calendar folders in alternate mailbox 'Public Folders - borourke@orionhealth.ca'.
2021-02-03 08:15:03,612 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The property "http://schemas.microsoft.com/mapi/proptag/0x35E30102" is unknown or cannot be found.
2021-02-03 08:15:03,613 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x8004010F;-2147221233
2021-02-03 08:15:03,613 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._PropertyAccessor.GetProperty(String SchemaName)
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.getCalendarStore(NameSpace oNS)
2021-02-03 08:15:03,623 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Could not find Alternative mailbox Calendar folder. Reverting to the default mailbox calendar.
```

**Comment by Bri0r0** [comment]
Hello thanks I'm looking for an account called brian@logicrehab.ca which isn't showing up in OGCS but is in my outlook, let me know if you have any tips I've done my best looking through the wiki, thanks!

**Comment by phw198** [comment]
Did you upgrade OGCS to v2.8.6 then and the issue remains? Please upload your logfile from that version if you have, do I can see if anything has changed when you try and select the alternative mailbox account.
