### ISSUE TITLE
Outlook recurring item exception: UserProperty.get_Value() method not supported

### ISSUE THREAD

**Issue by michaeltm2** [phw198/OutlookGoogleCalendarSync#1178]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.6.0  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
I am receiving the following error: Getting Error: "The synchronisation failed - check the Sync tab for further details. Do you want to try again?" and when I click yes, that just keeps popping up every minute or so until you click no. And it doesn't sync. Please help! Thank you! 

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6045683/OGcalsync.log)

**Comment by phw198** [comment]
Seems the following item does not allow custom "user properties" to be accessed - which OGCS relies upon:
`Processing >> 2/23/2021 11:00 AM (R) => "Team meeting"`

Specifically, it is trying to process the recurring series exception on 26/02/2021.

Do you know what is different about this item compared to any of the others in your calendar?

```
2021-02-25 15:48:36,060 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [611] -  Processing >> 2/23/2021 11:00 AM (R) => "Team meeting"
2021-02-25 15:48:36,061 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [32] -  Creating Google iCalendar definition for recurring event.
2021-02-25 15:48:36,204 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [43] -  RRULE:FREQ=WEEKLY;BYDAY=TU,FR;UNTIL=20211231T170000Z
2021-02-25 15:48:36,541 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [582] -  2/23/2021 11:00 AM (R) => "Team meeting"
2021-02-25 15:48:36,541 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [583] -  This is a recurring appointment with 3 exceptions that will now be iteratively compared.
2021-02-25 15:48:36,890 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [411] -  Finding Google instance for Outlook exception:-
2021-02-25 15:48:36,891 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [412] -    Original date: 26/02/2021
2021-02-25 15:48:36,956 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [416] -    Current  date: 26/02/2021
2021-02-25 15:48:36,960 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [610] -  Matching Google Event recurrence found.
2021-02-25 15:48:37,083 ERROR  11 OutlookGoogleCalendarSync.Recurrence [635] -  The object does not support this method.
2021-02-25 15:48:37,084 ERROR  11 OutlookGoogleCalendarSync.Recurrence [636] -     at Microsoft.Office.Interop.Outlook.UserProperty.get_Value()
   at OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty.getKeySet(AppointmentItem ai, Int32& maxSet) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\CustomProperty.cs:line 146
   at OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty.Exists(AppointmentItem ai, MetadataId searchId, String& searchKey) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\CustomProperty.cs:line 205
   at OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty.get_datetime(AppointmentItem ai, MetadataId key) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\CustomProperty.cs:line 309
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 596
   at OutlookGoogleCalendarSync.Recurrence.UpdateGoogleExceptions(AppointmentItem ai, Event ev, Boolean dirtyCache) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:line 632
```

**Comment by michaeltm2** [comment]
Not sure. My colleague at work created the series and from time to time has to make a change. It was originally 11 am and he changed it to 2:30 pm that day. Perhaps that has something to do with it? But that doesn’t seem so complicated.

**Comment by phw198** [comment]
:package: I've added some extra logging, just to check if there's anything that stands out [v2.8.6.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/6097710/v2.8.6.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please could you increase your logging level to `FINE`, reproduce the issue and then upload your log file again.

**Comment by michaeltm2** [comment]
So I applied your patch and I did a sync - the issue did not reproduce - maybe it's OK now? 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6111905/OGcalsync.log)

**Comment by phw198** [comment]
The hotfix hasn't fixed it, so I would suggest keep running that until you encounter the problem again.

The issue has disappeared I think because `2/23/2021 11:00 AM (R) => "Team meeting"` was problematic and it had a recurring exception on the 26-Feb, but it's now changed to `2/23/2021 10:00 AM (R) => "Team meeting"` and there is no recurring exception on 26-Feb - I guess the meeting organiser changed the invite.
