### ISSUE TITLE
Unable to access appointment recipients [0x80004004 E_ABORT]

### ISSUE THREAD

**Issue by seiler-thomas** [phw198/OutlookGoogleCalendarSync#1195]
**Are you already using OGCS?**
v2.8.6.0

**Describe the question you have**
I used OGCS successfully for quite some time and it stopped working when my Office installation was upgraded to Office 365.
Are there known issues with Outlook 365 and can I provide further specific details?

Log:
```
2021-03-25 14:22:04,749 INFO  1 OutlookGoogleCalendarSync.Program [239] -  Program started: v2.8.6.0
2021-03-25 14:22:04,749 INFO  1 OutlookGoogleCalendarSync.Program [240] -  Started interactively.
2021-03-25 14:22:04,749 INFO  1 OutlookGoogleCalendarSync.Program [244] -  Logging to: C:\Users\<userid>\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2021-03-25 14:22:04,750 INFO  1 OutlookGoogleCalendarSync.Program [249] -  Purging log files older than 30 days...
2021-03-25 14:22:04,751 INFO  1 OutlookGoogleCalendarSync.Program [260] -  Purge complete.
2021-03-25 14:22:04,752 INFO  1 OutlookGoogleCalendarSync.Settings [49] -  Running OGCS from C:\Program Files (x86)\OGCS_v2.8.6\OutlookGoogleCalendarSync.exe
2021-03-25 14:22:04,752 INFO  1 OutlookGoogleCalendarSync.Program [142] -  Storing user files in directory: C:\Users\<userid>\AppData\Roaming\Outlook Google Calendar Sync
2021-03-25 14:22:04,755 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [280] -  Getting MD5 hash for '<email>'
2021-03-25 14:22:04,755 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'CloudLogging' with value 'true'
2021-03-25 14:22:04,755 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [173] -  Turned error reporting ON
2021-03-25 14:22:04,756 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'Portable' with value 'false'
2021-03-25 14:22:04,756 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'LoggingLevel' with value 'WARN'
2021-03-25 14:22:04,757 INFO  1 OutlookGoogleCalendarSync.Settings [598] -  Logging level configured to 'WARN'
2021-03-25 14:22:05,787 WARN  1 OutlookGoogleCalendarSync.Forms.Main [999] -  Outlook calendar selection changed to: Kalender (ID: <calId>)
2021-03-25 14:22:49,327 ERROR  7 OutlookGoogleCalendarSync.Console [278] -  Event creation failed.
2021-03-25 14:22:49,330 ERROR  7 OutlookGoogleCalendarSync.Console [278] -  Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2021-03-25 14:22:49,424 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2021-03-25 14:22:49,426 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004004,-2147467260; Location: get_Recipients() in <Unknown File>
2021-03-25 14:22:49,427 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Recipients()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 420
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 344
2021-03-25 14:22:54,836 FAIL  1 OutlookGoogleCalendarSync.Console [276] -  Sync aborted after 1 failed attempts!
2021-03-25 14:23:46,564 ERROR  6 OutlookGoogleCalendarSync.Console [278] -  Event creation failed.
2021-03-25 14:23:46,565 ERROR  6 OutlookGoogleCalendarSync.Console [278] -  Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2021-03-25 14:23:46,567 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2021-03-25 14:23:46,568 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004004,-2147467260; Location: get_Recipients() in <Unknown File>
2021-03-25 14:23:46,568 ERROR  6 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Recipients()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 420
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 344
2021-03-25 14:23:48,754 FAIL  1 OutlookGoogleCalendarSync.Console [276] -  Sync aborted after 1 failed attempts!
```

![error](https://user-images.githubusercontent.com/66566436/112480485-61b76b80-8d76-11eb-89f8-138bb7c742c2.jpg)

**Comment by schwaben-github** [comment]
Hi @seiler-thomas,

I think, this is the hint you need:
https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---COM-Errors#0x80004004---e-abort

Hopefully it helps!

**Comment by phw198** [comment]
I think this relates to your corporate policies changing at the time of upgrade to M365. I'll take a look to see how this can be handled better, but meanwhile the workaround is probably to disabled sync of meeting attendees.

**Comment by phw198** [comment]
@seiler-thomas Is it failing for every single Outlook appointment, or just a specific one? Also, just to check, are you getting the [Outlook security popup](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs---Outlook-Security) during sync and you are clicking "Deny"?

**Comment by seiler-thomas** [comment]
@phw198: I tried the newest alpha and still have the same issue. No single appointment is synced. It looks like creating events is failing. An error appears for every event. No popup from Outlook is shown. I am happy to try out any workaround you suggest. 

In my settings, it says: 
< AddAttendees >false< /AddAttendees >

The error shows:
Console [278] -  Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
OGCSexception [28] -  System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
OGCSexception [21] -  Code: 0x80004004,-2147467260; Location: get_Recipients() in <Unknown File>
OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Recipients()

I do not need the recipients for sync but I do not find a setting on how to exclude them.

thank you!
Thomas

**Comment by seiler-thomas** [comment]
update: I just checked my Google calendar and now the entries are available. I have no idea why that is. I triggered another manual sync and now it seems to work. Effectively, I did not change anything except installing the latest alpha. Therefore it looks like my issue is solved for now. Sorry for the inconvenience.

**Comment by phw198** [comment]
I'm rather confused - the log excerpt you provided in your opening post is already from the latest alpha v2.8.6, which contains the error.

So essentially, you didn't change anything and it started working? Smacks of your IT admins fiddling with the Exchange security configuration to me!!

**Comment by seiler-thomas** [comment]
most probably not as our it is quite good and it is a not so small company. as I said I had the issues this morning and then some hours later found the calendar uptodate. Strange. I will give more information if problems come up again. Now it seems to work and I do not want to touch the config :)
