### ISSUE TITLE
OGCS doesn't start, just splash screen comes up [0x8A44010F] and [0x8C54010F]

### ISSUE THREAD

**Issue by tew42** [phw198/OutlookGoogleCalendarSync#1245]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.7.0
**Edition**: Installed
**Sync Direction**: N/A

**Bug Description**  
OGCS installs, the Splash screen shows up briefly, and the browser opens a window pointing to the OGCS version history. Nothing else happens. Log File logs two errors (0x8A44010F and 0x8C54010F).
Manual program start produces same result

**Steps to Reproduce the Issue**  
1. Install OGCS or manually run OGCS
2. Wait...

**Any other information**  
Hi, any assistance is much appreciated!

:paperclip: Attach your `OGcalsync.log` file.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/6789749/OGcalsync.log)

**Comment by phw198** [comment]
```
2021-07-09 09:47:34,969 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [421] -  Finding default Mailbox calendar folders
2021-07-09 09:47:35,029 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: The attempted operation failed.  An object could not be found.
2021-07-09 09:47:35,045 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x8A44010F,-1975254769; Location: get_DefaultStore() in <Unknown File>
2021-07-09 09:47:35,048 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook.NameSpaceClass.get_DefaultStore()
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.getDefaultCalendar(NameSpace oNS, MAPIFolder& defaultCalendar) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:line 433
2021-07-09 09:47:35,364 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: The attempted operation failed.  An object could not be found.
2021-07-09 09:47:35,365 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x8A44010F,-1975254769; Location: get_DefaultStore() in <Unknown File>
```
Looks like your Outlook profile has no default store specified. General consensus on the interwebs appear to be to recreate your Outlook profile - [see here for guidance](https://www.slipstick.com/outlook/error-0x8004010foutlook-data-file-accessed/).

Please let me know if this helps resolve your issue.

**Comment by tew42** [comment]
Hi, thanks for the pointer. Creating a new local data file did allow OGCS to start. Unfortunately, the underlying issue appears to be that OGCS doesn't play well with our company system, which appears to have the data file online. OGCS remains unaware of the calendars that I would like to share ("unable to find a calendar"). Seems I need to find a different solution... Thanks though.
