### ISSUE TITLE
OGCS won't start, cannot read %USERNAME% environment variable: Value cannot be null. Parameter name: oldValue

### ISSUE THREAD

**Issue by haknaton** [phw198/OutlookGoogleCalendarSync#1282]
> Checklist:-
> * [x] [Upgrade] Installed 2.9
> * [x] Reproduce the issue: Launch OGCS
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

<details>
<summary>Log file</summary>

```
2021-09-08 19:08:25,520 DEBUG  10 OutlookGoogleCalendarSync.Updater [400] -  Finding Beta release...
2021-09-08 19:08:25,520 INFO  10 OutlookGoogleCalendarSync.Updater [435] -  Already on latest ZIP release.
2021-09-08 19:08:31,909 DEBUG  18 OutlookGoogleCalendarSync.Forms.Splash [74] -  Disposed of splash screen.
2021-09-08 19:09:36,380 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1051] -  Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
2021-09-08 19:09:36,380 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [986] -  Outlook is busy. Attempt 1/3
2021-09-08 19:09:46,385 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1005] -  Starting a new instance of Outlook.
2021-09-08 19:10:17,077 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1051] -  Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
2021-09-08 19:10:17,078 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [986] -  Outlook is busy. Attempt 2/3
2021-09-08 19:10:27,081 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1005] -  Starting a new instance of Outlook.
2021-09-08 19:10:28,008 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1100] -  Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
2021-09-08 19:10:28,009 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1102] -  Extracting specific COM error code from Exception error message.
2021-09-08 19:10:28,515 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1165] -  Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
2021-09-08 19:10:28,758 FATAL  1 OutlookGoogleCalendarSync.Program [76] -  A problem was encountered with your Office install.
Please see the wiki for a solution. [0x80029C4A]
2021-09-08 19:12:34,605 WARN  1 OutlookGoogleCalendarSync.Program [101] -  OGCS has crashed out.
2021-09-08 19:12:34,606 DEBUG  1 OutlookGoogleCalendarSync.Program [109] -  Shutting down application.
2021-09-08 19:12:34,610 INFO  1 OutlookGoogleCalendarSync.Program [118] -  Application closed.
2021-09-08 19:23:07,454 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [178] -  Initialising error reporting to OFF
2021-09-08 19:23:07,471 INFO  1 OutlookGoogleCalendarSync.Program [242] -  Program started: v2.9.0.0
2021-09-08 19:23:07,472 INFO  1 OutlookGoogleCalendarSync.Program [243] -  Started interactively.
2021-09-08 19:23:07,473 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentNullException: Value cannot be null.
Parameter name: oldValue
2021-09-08 19:23:07,476 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: Replace() in <Unknown File>
2021-09-08 19:23:07,476 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.String.Replace(String oldValue, String newValue)
   at OutlookGoogleCalendarSync.Program.MaskFilePath(String path) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 522
   at OutlookGoogleCalendarSync.Program.initialiseLogger(String logFilename, String logPath, Boolean bootstrap) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 246
   at OutlookGoogleCalendarSync.Program.parseArgumentsAndInitialise(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 137
   at OutlookGoogleCalendarSync.Program.Main(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 56
2021-09-08 19:23:07,476 FATAL  1 OutlookGoogleCalendarSync.Program [104] -  Application unexpectedly terminated!
2021-09-08 19:23:15,950 WARN  1 OutlookGoogleCalendarSync.Program [107] -  OGCS has crashed out.
2021-09-08 19:23:15,950 DEBUG  1 OutlookGoogleCalendarSync.Program [109] -  Shutting down application.
2021-09-08 19:23:15,960 INFO  1 OutlookGoogleCalendarSync.Program [118] -  Application closed.
2021-09-08 19:23:35,337 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [178] -  Initialising error reporting to OFF
2021-09-08 19:23:35,357 INFO  1 OutlookGoogleCalendarSync.Program [242] -  Program started: v2.9.0.0
2021-09-08 19:23:35,357 INFO  1 OutlookGoogleCalendarSync.Program [243] -  Started interactively.
2021-09-08 19:23:35,359 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentNullException: Value cannot be null.
Parameter name: oldValue
2021-09-08 19:23:35,361 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: Replace() in <Unknown File>
2021-09-08 19:23:35,361 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.String.Replace(String oldValue, String newValue)
   at OutlookGoogleCalendarSync.Program.MaskFilePath(String path) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 522
   at OutlookGoogleCalendarSync.Program.initialiseLogger(String logFilename, String logPath, Boolean bootstrap) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 246
   at OutlookGoogleCalendarSync.Program.parseArgumentsAndInitialise(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 137
   at OutlookGoogleCalendarSync.Program.Main(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 56
2021-09-08 19:23:35,361 FATAL  1 OutlookGoogleCalendarSync.Program [104] -  Application unexpectedly terminated!
2021-09-08 19:23:37,447 WARN  1 OutlookGoogleCalendarSync.Program [107] -  OGCS has crashed out.
2021-09-08 19:23:37,447 DEBUG  1 OutlookGoogleCalendarSync.Program [109] -  Shutting down application.
2021-09-08 19:23:37,453 INFO  1 OutlookGoogleCalendarSync.Program [118] -  Application closed.
2021-09-08 19:23:44,251 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [178] -  Initialising error reporting to OFF
2021-09-08 19:23:44,269 INFO  1 OutlookGoogleCalendarSync.Program [242] -  Program started: v2.9.0.0
2021-09-08 19:23:44,270 INFO  1 OutlookGoogleCalendarSync.Program [243] -  Started interactively.
2021-09-08 19:23:44,270 INFO  1 OutlookGoogleCalendarSync.Program [247] -  Logging to: C:\Users\<userid>\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2021-09-08 19:23:44,271 INFO  1 OutlookGoogleCalendarSync.Program [252] -  Purging log files older than 30 days...
2021-09-08 19:23:44,271 INFO  1 OutlookGoogleCalendarSync.Program [263] -  Purge complete.
2021-09-08 19:23:44,272 INFO  1 OutlookGoogleCalendarSync.Settings [49] -  Running OGCS from C:\Users\<userid>\Downloads\Portable_OGCS_v2.9.0\OutlookGoogleCalendarSync.exe
2021-09-08 19:23:44,272 INFO  1 OutlookGoogleCalendarSync.Program [145] -  Storing user files in directory: C:\Users\<userid>\AppData\Roaming\Outlook Google Calendar Sync
2021-09-08 19:23:44,276 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [280] -  Getting MD5 hash for 'ab*****************e@gmail.com'
2021-09-08 19:23:44,277 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'CloudLogging' with value 'true'
2021-09-08 19:23:44,277 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [174] -  Turned error reporting ON
2021-09-08 19:23:44,278 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'Portable' with value 'false'
2021-09-08 19:23:44,279 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'LoggingLevel' with value 'DEBUG'
2021-09-08 19:23:44,279 INFO  1 OutlookGoogleCalendarSync.Settings [603] -  Logging level configured to 'DEBUG'
2021-09-08 19:23:44,280 DEBUG  1 OutlookGoogleCalendarSync.Updater [248] -  Setting up Squirrel handlers.
2021-09-08 19:23:44,360 DEBUG  18 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'CompletedSyncs' with value '2457'
2021-09-08 19:23:44,362 DEBUG  18 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'Donor' with value 'false'
2021-09-08 19:23:44,362 DEBUG  18 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'Subscribed' with value '2000-01-01T00:00:00'
2021-09-08 19:23:44,363 DEBUG  18 OutlookGoogleCalendarSync.XMLManager [58] -  Retrieved setting 'HideSplashScreen' with value 'false'
2021-09-08 19:23:44,363 DEBUG  18 OutlookGoogleCalendarSync.Forms.Splash [72] -  Showing splash screen.
2021-09-08 19:23:44,403 DEBUG  1 OutlookGoogleCalendarSync.Program [62] -  Loading settings from file.
2021-09-08 19:23:44,506 INFO  1 OutlookGoogleCalendarSync.SettingsProxy [91] -  Using default proxy (app.config / IE).
2021-09-08 19:23:44,507 INFO  1 OutlookGoogleCalendarSync.SettingsProxy [91] -  Setting system-wide proxy.
2021-09-08 19:23:44,510 DEBUG  1 OutlookGoogleCalendarSync.SettingsProxy [100] -  Testing the system proxy.
2021-09-08 19:23:44,510 DEBUG  1 OutlookGoogleCalendarSync.SettingsProxy [103] -  Confirmation of configured proxy: http://www.google.com
2021-09-08 19:23:44,515 DEBUG  1 OutlookGoogleCalendarSync.Updater [36] -  Automatic update check requested.
2021-09-08 19:23:44,519 DEBUG  10 OutlookGoogleCalendarSync.Updater [385] -  Checking for ZIP update...
2021-09-08 19:23:44,547 INFO  1 OutlookGoogleCalendarSync.NotificationTray [42] -  Using NodaTime TZDB: 2021a (mapping: $Revision$)
2021-09-08 19:23:44,550 DEBUG  20 OutlookGoogleCalendarSync.NotificationTray [59] -  Checking for new timezone database...
2021-09-08 19:23:44,552 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [29] -  Initialiasing MainForm.
2021-09-08 19:23:44,779 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [960] -  Attaching to the already running Outlook process.
2021-09-08 19:23:44,781 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [963] -  Attachment failed - Outlook is running without GUI for programmatic access.
2021-09-08 19:23:44,782 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1005] -  Starting a new instance of Outlook.
2021-09-08 19:23:44,900 DEBUG  20 OutlookGoogleCalendarSync.NotificationTray [75] -  Already have latest TZDB version.
2021-09-08 19:23:45,066 DEBUG  10 OutlookGoogleCalendarSync.Updater [400] -  Finding Beta release...
2021-09-08 19:23:45,067 INFO  10 OutlookGoogleCalendarSync.Updater [435] -  Already on latest ZIP release.
2021-09-08 19:23:45,181 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1051] -  Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
2021-09-08 19:23:45,182 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [986] -  Outlook is busy. Attempt 1/3
2021-09-08 19:23:52,560 DEBUG  18 OutlookGoogleCalendarSync.Forms.Splash [74] -  Disposed of splash screen.
2021-09-08 19:23:55,186 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1005] -  Starting a new instance of Outlook.
2021-09-08 19:24:25,885 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1051] -  Retrieving the COM class factory for component with CLSID {0006F03A-0000-0000-C000-000000000046} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
2021-09-08 19:24:25,886 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [986] -  Outlook is busy. Attempt 2/3
2021-09-08 19:24:35,898 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1005] -  Starting a new instance of Outlook.
2021-09-08 19:24:36,820 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1100] -  Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
2021-09-08 19:24:36,821 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1102] -  Extracting specific COM error code from Exception error message.
2021-09-08 19:24:37,156 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1165] -  Unable to cast COM object of type 'Microsoft.Office.Interop.Outlook.ApplicationClass' to interface type 'Microsoft.Office.Interop.Outlook._Application'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063001-0000-0000-C000-000000000046}' failed due to the following error: Error loading type library/DLL. (Exception from HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY)).
2021-09-08 19:24:37,355 FATAL  1 OutlookGoogleCalendarSync.Program [76] -  A problem was encountered with your Office install.
Please see the wiki for a solution. [0x80029C4A]
2021-09-08 20:03:39,562 WARN  1 OutlookGoogleCalendarSync.Program [101] -  OGCS has crashed out.
2021-09-08 20:03:39,563 DEBUG  1 OutlookGoogleCalendarSync.Program [109] -  Shutting down application.
2021-09-08 20:03:39,572 INFO  1 OutlookGoogleCalendarSync.Program [118] -  Application closed.
2021-09-08 20:23:58,472 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [178] -  Initialising error reporting to OFF
2021-09-08 20:23:58,491 INFO  1 OutlookGoogleCalendarSync.Program [242] -  Program started: v2.9.0.0
2021-09-08 20:23:58,492 INFO  1 OutlookGoogleCalendarSync.Program [243] -  Started interactively.
2021-09-08 20:23:58,493 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentNullException: Value cannot be null.
Parameter name: oldValue
2021-09-08 20:23:58,497 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: Replace() in <Unknown File>
2021-09-08 20:23:58,498 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.String.Replace(String oldValue, String newValue)
   at OutlookGoogleCalendarSync.Program.MaskFilePath(String path) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 522
   at OutlookGoogleCalendarSync.Program.initialiseLogger(String logFilename, String logPath, Boolean bootstrap) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 246
   at OutlookGoogleCalendarSync.Program.parseArgumentsAndInitialise(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 137
   at OutlookGoogleCalendarSync.Program.Main(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 56
2021-09-08 20:23:58,498 FATAL  1 OutlookGoogleCalendarSync.Program [104] -  Application unexpectedly terminated!`
```
</details>

**OGCS Version**: v2.9
**Edition**: Installed 
**Sync Direction**: O->G, but not really applicable, program don't work

**Bug Description**  
Cannot start the program

**Steps to Reproduce the Issue**  
1. Launch OGCS
2. Get error written in issue post
3. Open Github issue

I have followed the complete list to fix registry for this MS365 installation.
I did a full repair of office 365
I did a full reinstall of OGCS

I was user for the last 2 years without any prior issue.
I have a laptop of GPO and changes can have be done without my knowledge.

**Comment by phw198** [comment]
It appears that OGCS is unable to access your `%USERNAME%` environment variable - unless you start OGCS as Administrator (which it appears you tried, but then it crashes for a different reason).

The below hotfix should work around this and provide extra logging - please upload your logfile again once you've tried it, so I can hopefully finalise the fix.

:package: ~~[v2.9.0.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7147614/v2.9.0.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).~~ See [subsequent hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1282#issuecomment-985117533).

Please let me know how it goes.

**Comment by phw198** [comment]
@haknaton Any update?

**Comment by haknaton** [comment]
Hello Paul,

Sorry for not responding.
I didn't have the time to test. But in the meantime, it works again. Is
there something that I can collect for you to spot the difference?

Le ven. 1 oct. 2021 à 23:08, Paul Woolcock ***@***.***> a
écrit :

**Comment by phw198** [comment]
Thanks for the update - you mean it started working on the same OGCS version, without apply the hotfix posted here?

If so, guess we'll put it down to one of those "turn if off and on again" solutions! If you did apply the hotfix, please upload the logfile so I can analyse further.

Thanks!

**Comment by davelot** [comment]
I had the same issue and tried the fix posted.  I receive error:

Object reference not set to an instance of an object

Log is attached, hope it helps!


[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7522850/OGcalsync.log)

**Comment by phw198** [comment]
@davelot Are you interactively logging in to Windows? And how are you running OGCS? Do you have it running as a service somehow?

If you open a Command Prompt and type `set username`, what does it return?

Was OGCS running successfully previously, or have you only just started to try OGCS? If it was OK before, what has changed recently on the computer you are using? (Note, I did come across [this article](https://docs.microsoft.com/en-us/troubleshoot/windows-client/ue-v/percent-username-percent-unavailable)).

**Comment by sjschultze** [comment]
I had the same issue, tried the hotfix, and had the same error that @davelot reported. I'm logging in interactively to Windows and running OGCS portable.  In Command Prompt, `set username` gives `Environment variable username not defined`

**Comment by sjschultze** [comment]
UPDATE: Rebooted and Windows applied some updates. Username is now set and I'm not experiencing the bug with the stock (not-hotfixed) release.

**Comment by phw198** [comment]
@sjschultze Interesting...so this is potentially a turn if off and on again/reboot situation!

The `Object reference not set to an instance of an object` error is a different v2.9.0 bug that should have been fixed subsequently, so I have applied the hotfix to v2.9.2.

:package: [v2.9.2.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7645961/v2.9.2.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

If anyone else hits this issue:
1. Apply the hotfix and run OGCS (should be no errors)
2. Upload your `OGcalsync.log` file so I can review the extra logging.
    a. There should be an `ERROR` line "Problems accessing environment variables."
3. Reboot your computer and run OGCS
    a. The should be no `ERROR` line any more.

If the reboot works, I could add this advice as feedback in the app.

**Comment by rolavarrias** [comment]
Hello. My problem solved itself. I was able to reinstall the app after several failed attempts. Now everything works fine. The version I installed is 2.9.0.0.
Thanks for the help.
Here I leave log information with the error that was initially.
```
2021-12-30 17:06:34,762 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [178] -  Initialising error reporting to OFF
2021-12-30 17:06:34,776 INFO  1 OutlookGoogleCalendarSync.Program [242] -  Program started: v2.9.0.0
2021-12-30 17:06:34,777 INFO  1 OutlookGoogleCalendarSync.Program [243] -  Started automatically.
2021-12-30 17:06:34,777 INFO  1 OutlookGoogleCalendarSync.Program [246] -  Invoked with arguments: --squirrel-install 2.9.0-beta
2021-12-30 17:06:34,779 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: oldValue
2021-12-30 17:06:34,789 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: Replace() in <Unknown File>
2021-12-30 17:06:34,789 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [65] -     en System.String.Replace(String oldValue, String newValue)
   en OutlookGoogleCalendarSync.Program.MaskFilePath(String path) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 522
   en OutlookGoogleCalendarSync.Program.initialiseLogger(String logFilename, String logPath, Boolean bootstrap) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 246
   en OutlookGoogleCalendarSync.Program.parseArgumentsAndInitialise(String[] args) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 137
   en OutlookGoogleCalendarSync.Program.Main(String[] args) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 56
2021-12-30 17:06:34,789 FATAL  1 OutlookGoogleCalendarSync.Program [104] -  Application unexpectedly terminated!
2021-12-30 17:06:44,371 WARN  1 OutlookGoogleCalendarSync.Program [107] -  OGCS has crashed out.
2021-12-30 17:06:44,371 DEBUG  1 OutlookGoogleCalendarSync.Program [109] -  Shutting down application.
2021-12-30 17:06:44,378 INFO  1 OutlookGoogleCalendarSync.Program [118] -  Application closed.
2021-12-30 17:06:48,245 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [178] -  Initialising error reporting to OFF
2021-12-30 17:06:48,264 INFO  1 OutlookGoogleCalendarSync.Program [242] -  Program started: v2.9.0.0
2021-12-30 17:06:48,265 INFO  1 OutlookGoogleCalendarSync.Program [243] -  Started interactively.
2021-12-30 17:06:48,265 INFO  1 OutlookGoogleCalendarSync.Program [246] -  Invoked with arguments: --squirrel-firstrun
2021-12-30 17:06:48,266 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: oldValue
2021-12-30 17:06:48,269 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: Replace() in <Unknown File>
2021-12-30 17:06:48,270 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [65] -     en System.String.Replace(String oldValue, String newValue)
   en OutlookGoogleCalendarSync.Program.MaskFilePath(String path) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 522
   en OutlookGoogleCalendarSync.Program.initialiseLogger(String logFilename, String logPath, Boolean bootstrap) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 246
   en OutlookGoogleCalendarSync.Program.parseArgumentsAndInitialise(String[] args) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 137
   en OutlookGoogleCalendarSync.Program.Main(String[] args) en C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:línea 56
2021-12-30 17:06:48,270 FATAL  1 OutlookGoogleCalendarSync.Program [104] -  Application unexpectedly terminated!
2021-12-30 17:06:50,527 WARN  1 OutlookGoogleCalendarSync.Program [107] -  OGCS has crashed out.
2021-12-30 17:06:50,528 DEBUG  1 OutlookGoogleCalendarSync.Program [109] -  Shutting down application.
2021-12-30 17:06:50,534 INFO  1 OutlookGoogleCalendarSync.Program [118] -  Application closed.
```
