### ISSUE TITLE
Issue creating events in Outlook 2016 from Google calendar

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#13]
When I attempt to synchronize recurring events from Google Calendar it seems
to bomb out with an event in America/Phoenix timezone.  
  
Please see the following logs:  
  
From Google_events.csv  

    
    
    Start Time = 2015-02-10T13:00:00-05:00
    Finish Time =2015-02-10T13:30:00-05:00
    Subject = "Tuesday Scrum"
    Location = 
    Description = 
    Privacy = ""
    FreeBusy = ""
    Required Attendees = "Pete Bertenshaw;Joshua Burlingame;;;Christopher Lynch;Greg Pearcey;"
    Optional Attendees = ""
    Reminder Set = 
    Reminder Minutes = 
    Google ID = 6eed98h0ls3nd51h28nq36jnes
    Outlook ID = 

From the error log:  

    
    
    016-01-25 09:13:13,546 INFO 5 OutlookGoogleCalendarSync.MainForm [0] - Creating 2 Outlook calendar entries...
    2016-01-25 09:13:13,557 DEBUG 5 OutlookGoogleCalendarSync.OutlookCalendar [0] - Processing >> 2/10/2015 1:00 PM (R) => "Tuesday Scrum"
    2016-01-25 09:13:13,751 DEBUG 5 OutlookGoogleCalendarSync.MainForm [0] - 2/10/2015 1:00 PM (R) => "Tuesday Scrum"
    2016-01-25 09:13:13,772 FINE 5 OutlookGoogleCalendarSync.OutlookNew [0] - Timezone "America/Phoenix" mapped to "US Mountain Standard Time"
    2016-01-25 09:13:13,959 INFO 5 OutlookGoogleCalendarSync.MainForm [0] - WARNING: Appointment creation failed.
    The object does not support this method.
    2016-01-25 09:13:13,959 ERROR 5 OutlookGoogleCalendarSync.OutlookCalendar [0] -    at Microsoft.Office.Interop.Outlook._AppointmentItem.set_End(DateTime End)
       at OutlookGoogleCalendarSync.OutlookNew.WindowsTimeZone_set(AppointmentItem ai, Event ev)
       at OutlookGoogleCalendarSync.OutlookCalendar.createCalendarEntry(Event ev)
       at OutlookGoogleCalendarSync.OutlookCalendar.CreateCalendarEntries(List`1 events)

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 168](http://outlookgooglecalendarsync.codeplex.com/workitem/168)
**Status:**	Resolved
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jan 25, 2016 at 1:23 PM
**Reported by:**	zjm7891
**Updated on:**	Mar 5, 2016 at 7:08 PM
**Updated by:**	phw198

**Comment by phw198** [comment]
On *2016-01-25 21:24:54 UTC*, **zjm7891** commented:

Attaching Full Log File:

**Comment by phw198** [comment]
On *2016-03-06 03:08:20 UTC*, **phw198** commented:

Hi, 
This should actually be fixed in v2.1.2.0 if you would like to upgrade to that. 
Thanks
