### ISSUE TITLE
Automatic update not working

### ISSUE THREAD

**Issue by nkappler** [phw198/OutlookGoogleCalendarSync#1308]
> Checklist:-
> * [ ] ~[Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available)~ N/A
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.8.0.0  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
OGCS prompts me every time on startup or manual check that an update (v2.9.0) is available.
Clicking on `Upgrade` results in an error and the update not being installed every time.
![image](https://user-images.githubusercontent.com/9429273/136003006-1b576ef7-0e51-4729-8ef3-2ded30200e33.png)

I am going to install it manually now.

**Steps to Reproduce the Issue**  
1. Start v2.8.0.0
1. Click on `Upgrade` in the "Update Available" Dialog

**Log File**
I've removed some personal information from the log file, but it should include everything important:

<details>
<summary>
Expand Logfile
</summary>

```log
2021-10-05 12:13:02,308 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [0] -  Initialising error reporting to OFF
2021-10-05 12:13:02,321 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Program started: v2.8.0.0
2021-10-05 12:13:02,322 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Started interactively.
2021-10-05 12:13:02,322 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Logging to: C:\Users\*****\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2021-10-05 12:13:02,322 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purging log files older than 30 days...
2021-10-05 12:13:02,322 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Purge complete.
2021-10-05 12:13:02,323 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  Running OGCS from C:\Users\*****\AppData\Local\OutlookGoogleCalendarSync\app-2.8.0-beta\OutlookGoogleCalendarSync.exe
2021-10-05 12:13:02,323 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Storing user files in directory: C:\Users\*****\AppData\Roaming\Outlook Google Calendar Sync
2021-10-05 12:13:02,327 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Getting MD5 hash for '****@gmail.com'
2021-10-05 12:13:02,328 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'CloudLogging' with value 'false'
2021-10-05 12:13:02,328 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'Portable' with value 'false'
2021-10-05 12:13:02,329 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'LoggingLevel' with value 'DEBUG'
2021-10-05 12:13:02,329 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  Logging level configured to 'DEBUG'
2021-10-05 12:13:02,330 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Setting up Squirrel handlers.
2021-10-05 12:13:02,375 DEBUG  20 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'CompletedSyncs' with value '1590'
2021-10-05 12:13:02,376 DEBUG  20 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'Donor' with value 'false'
2021-10-05 12:13:02,377 DEBUG  20 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'Subscribed' with value '2000-01-01T00:00:00'
2021-10-05 12:13:02,379 DEBUG  20 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'HideSplashScreen' with value 'false'
2021-10-05 12:13:02,379 DEBUG  20 OutlookGoogleCalendarSync.Forms.Splash [0] -  Showing splash screen.
2021-10-05 12:13:02,390 DEBUG  1 OutlookGoogleCalendarSync.Program [0] -  Loading settings from file.
2021-10-05 12:13:02,436 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Automatic update check requested.
2021-10-05 12:13:02,438 INFO  1 OutlookGoogleCalendarSync.SettingsProxy [0] -  Using default proxy (app.config / IE).
2021-10-05 12:13:02,438 INFO  1 OutlookGoogleCalendarSync.SettingsProxy [0] -  Setting system-wide proxy.
2021-10-05 12:13:02,440 DEBUG  1 OutlookGoogleCalendarSync.SettingsProxy [0] -  Testing the system proxy.
2021-10-05 12:13:02,440 DEBUG  1 OutlookGoogleCalendarSync.SettingsProxy [0] -  Confirmation of configured proxy: http://www.google.com
2021-10-05 12:13:02,444 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Checking for Squirrel update...
2021-10-05 12:13:02,465 INFO  1 OutlookGoogleCalendarSync.NotificationTray [0] -  Using NodaTime TZDB: 2021c (mapping: $Revision$)
2021-10-05 12:13:02,466 DEBUG  24 OutlookGoogleCalendarSync.NotificationTray [0] -  Checking for new timezone database...
2021-10-05 12:13:02,467 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Initialiasing MainForm.
2021-10-05 12:13:02,723 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attaching to the already running Outlook process.
2021-10-05 12:13:02,745 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Factory [0] -  Outlook Version: 16.0.0.13801
2021-10-05 12:13:02,746 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Getting MD5 hash for '****@gmail.com'
2021-10-05 12:13:02,746 DEBUG  1 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&cid=469f9ce675a80dfbbdfb0e1f9cf5fab6&ec=outlook&ea=version&el=2016
2021-10-05 12:13:02,747 DEBUG  1 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&cid=469f9ce675a80dfbbdfb0e1f9cf5fab6&ec=ogcs&ea=version&el=2.8.0.0
2021-10-05 12:13:02,754 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Find Folders
2021-10-05 12:13:02,758 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attaching to the already running Outlook process.
2021-10-05 12:13:02,760 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Setting up Outlook connection.
2021-10-05 12:13:02,772 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Exchange server version: 15.20.4566.22
2021-10-05 12:13:02,772 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Exchange connection mode: olCachedConnectedFull
2021-10-05 12:13:02,777 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Getting active window inspector
2021-10-05 12:13:02,787 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Done.
2021-10-05 12:13:02,816 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Get the folders configured in Outlook
2021-10-05 12:13:02,823 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Finding default Mailbox calendar folders
2021-10-05 12:13:02,826 DEBUG  24 OutlookGoogleCalendarSync.NotificationTray [0] -  Already have latest TZDB version.
2021-10-05 12:13:02,837 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Currently installed version: 2.8.0-beta
2021-10-05 12:13:02,840 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Found 8 newer releases available.
2021-10-05 12:13:02,841 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Found a new beta version: 2.9.0.0
2021-10-05 12:13:03,016 DEBUG  19 OutlookGoogleCalendarSync.Updater [0] -  Release notes retrieved.
2021-10-05 12:13:03,027 INFO  32 OutlookGoogleCalendarSync.Forms.UpdateInfo [0] -  Showing new release information.
2021-10-05 12:13:03,736 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Default Calendar folder: Kalender
2021-10-05 12:13:03,740 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Folder type: olPrimaryExchangeMailbox
2021-10-05 12:13:03,780 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Setting up Explorer event watchers.
2021-10-05 12:13:03,782 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Watcher needed for 1 existing explorers.
2021-10-05 12:13:03,789 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Adding listener for Explorer 'Posteingang - ******** - Outlook'
2021-10-05 12:13:03,818 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  List Calendar folders
2021-10-05 12:13:03,882 DEBUG  1 OutlookGoogleCalendarSync.Program [0] -  CheckShortcut: directory=Startup; subdir=
2021-10-05 12:13:03,884 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  Logging level configured to 'Debug'
2021-10-05 12:13:03,889 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  C:\Users\*****\AppData\Roaming\Outlook Google Calendar Sync\settings.xml
2021-10-05 12:13:03,889 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  OUTLOOK SETTINGS:-
2021-10-05 12:13:03,889 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Service: DefaultMailbox
2021-10-05 12:13:03,889 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Mailbox/FolderStore Name: 
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: Kalender
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Category Filter: Exclude
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Categories: 
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Only Responded Invites: False
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Filter String: g
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    GAL Blocked: False
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  GOOGLE SETTINGS:-
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: Arbeit
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Personal API Keys: False
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Identifier: 
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Secret: 
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit in effect: False
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit last reached: 01/01/2000 00:00:00
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Assigned API key: deleted by me, let me know if you need it
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Cloak Email: True
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  SYNC OPTIONS:-
2021-10-05 12:13:03,890 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   How
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncDirection: Outlook → Google
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MergeItems: True
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DisableDelete: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ConfirmOnDelete: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesPrivate: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesAvailable: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesColour: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Obfuscate Words: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   When
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInThePast: 1
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInTheFuture:60
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncInterval: 2
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncIntervalUnit: Hours
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Push Changes: True
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   What
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddLocation: True
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddDescription: True; OnlyToGoogle: True
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddAttendees: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddColours: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddReminders: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      UseGoogleDefaultReminder: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      UseOutlookDefaultReminder: False
2021-10-05 12:13:03,891 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      ReminderDND: False (22:00-06:00)
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  PROXY:-
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Type: IE
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  APPLICATION BEHAVIOUR:-
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleTooltipWhenSyncing: False
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartOnStartup: True; DelayedStartup: 60
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    HideSplashScreen: N/A
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SuppressSocialPopup: N/A
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartInTray: True
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseToTray: True
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseNotClose: True
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleWhenMinimising: False
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Portable: False
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    CreateCSVFiles: False
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    VerboseOutput: True
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MuteClickSounds: False
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Logging Level: DEBUG
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Error Reporting: False
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ABOUT:-
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Alpha Releases: False
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Skip Version: 
2021-10-05 12:13:03,892 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Subscribed: 01-Jan-2000
2021-10-05 12:13:03,893 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Timezone Database: 2021c
2021-10-05 12:13:03,893 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ENVIRONMENT:-
2021-10-05 12:13:03,893 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Current Locale: en-DE
2021-10-05 12:13:03,893 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Date Format: dd/MM/yyyy
2021-10-05 12:13:03,893 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Time Format: HH:mm
2021-10-05 12:13:03,893 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Completed Syncs: 1590
2021-10-05 12:13:03,923 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Create the timer for the auto synchronisation
2021-10-05 12:13:03,925 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for Tuesday, 5 October 2021 @ 14:07:32 + Push
2021-10-05 12:13:03,925 DEBUG  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Create the timer for the push synchronisation
2021-10-05 12:13:06,653 DEBUG  19 OutlookGoogleCalendarSync.Updater [0] -  Download started...
2021-10-05 12:13:06,681 DEBUG  19 OutlookGoogleCalendarSync.Updater [0] -  Download complete.
2021-10-05 12:13:06,681 DEBUG  19 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&cid=469f9ce675a80dfbbdfb0e1f9cf5fab6&ec=squirrel&ea=download&el=from%3D2.8.0.0%3Bto%3D2.9.0.0%3Bsuccessful
2021-10-05 12:13:06,681 INFO  19 OutlookGoogleCalendarSync.Updater [0] -  Applying the updated release...
2021-10-05 12:13:06,706 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  System.ArgumentException: File does not exist: C:\Users\*****\AppData\Local\OutlookGoogleCalendarSync\packages\OutlookGoogleCalendarSync-2.8.1-alpha-delta.nupkg
2021-10-05 12:13:06,708 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80070057;-2147024809
2021-10-05 12:13:06,709 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -     at SharpCompress.Archives.AbstractArchive`2..ctor(ArchiveType type, FileInfo fileInfo, ReaderOptions readerOptions)
   at SharpCompress.Archives.AbstractWritableArchive`2..ctor(ArchiveType type, FileInfo fileInfo, ReaderOptions readerFactoryOptions)
   at SharpCompress.Archives.Zip.ZipArchive..ctor(FileInfo fileInfo, ReaderOptions readerOptions)
   at SharpCompress.Archives.Zip.ZipArchive.Open(FileInfo fileInfo, ReaderOptions readerOptions)
   at SharpCompress.Archives.Zip.ZipArchive.Open(String filePath, ReaderOptions readerOptions)
   at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
2021-10-05 12:13:06,709 DEBUG  19 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&cid=469f9ce675a80dfbbdfb0e1f9cf5fab6&ec=squirrel&ea=download&el=%3Bfailed
2021-10-05 12:13:06,712 ERROR  19 OutlookGoogleCalendarSync.Updater [0] -  Failed upgrading OGCS. File does not exist: C:\Users\*****\AppData\Local\OutlookGoogleCalendarSync\packages\OutlookGoogleCalendarSync-2.8.1-alpha-delta.nupkg
2021-10-05 12:13:10,490 DEBUG  20 OutlookGoogleCalendarSync.Forms.Splash [0] -  Disposed of splash screen.
```

</details>

**Comment by phw198** [comment]
Thanks for reporting. However, there have been quite a lot of changes to the upgrade mechanism since v2.8.0, so as prompted in the pop-up, your best best is to click `Yes` and download and install manually from the website.

Hopefully you shouldn't have to do this when upgrading from v2.9.0.
