### ISSUE TITLE
Cannot upgrade from v2.9.1

### ISSUE THREAD

**Issue by MartinJJ** [phw198/OutlookGoogleCalendarSync#1341]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
Thats'whats failing ...
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.1.0  
**Edition**: Installed / Portable  
**Sync Direction**:  O->G 

**Bug Description**  
Get an error when trying to upgrade to 2.9.2-alpha
Am at  2.9.1.0

**Steps to Reproduce the Issue**  
1. Click UPGRADE
1. follow steps

or:
1. Download  2.9.2-alpha
2. try to run the Setup.exe
 Also gives the same error
 Application unexpectedly terminated!
 Object reference not set to an instance of an object.
 
 See screenshot.
 

Regards, Martin

**Any other information**  
![Screen Shot 2021-11-15-08 27 46](https://user-images.githubusercontent.com/3940571/141938807-873b752f-aa3e-46a0-bd5a-46a38ed3408e.PNG)

**Comment by MartinJJ** [comment]
If in the upgrade info popup, i select upgrade 'Later'  and later try to upgrade via: - About: Check upgrade [Tagging 'Check for Alpha Release']
The button goes to 'Checking...'   and the window  Freezes.
I have to end the process.

Regards, Martin

**Comment by sdlaw-sdelorme** [comment]
Same thing is happening to me.

**Comment by lammertsm** [comment]
Same here.

setup.exe from this link works for me.
https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.9.2-alpha/Setup.exe

**Comment by phw198** [comment]
Can someone upload their `OGcalsync.log` file after a failed upgrade, please?

**Comment by phw198** [comment]
I've replicated the issue:
```
2021-11-16 23:24:18,108 INFO  12 OutlookGoogleCalendarSync.Updater [178] -  Applying the updated release(s)...
2021-11-16 23:24:18,864 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [28] -  System.TypeLoadException: Could not load type 'SharpCompress.Readers.ExtractionOptions' from assembly 'SharpCompress, Version=0.24.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'.
2021-11-16 23:24:18,959 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131522,-2146233054; Location: ApplyDeltaPackage() in <Unknown File>
2021-11-16 23:24:18,978 ERROR  12 OutlookGoogleCalendarSync.OGCSexception [65] -     at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Squirrel.UpdateManager.<ApplyReleases>d__10.MoveNext()
2021-11-16 23:24:18,978 DEBUG  12 OutlookGoogleCalendarSync.Telemetry [32] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=1&ec=squirrel&ea=download&el=%3Bfailed
2021-11-16 23:24:18,978 ERROR  12 OutlookGoogleCalendarSync.Updater [66] -  Failed upgrading OGCS. Could not load type 'SharpCompress.Readers.ExtractionOptions' from assembly 'SharpCompress, Version=0.24.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'.
```
...and it seems I have amnesia and hit the same bug in v2.8.1 with #926 :disappointed: 

I'll have to revert to SharpCompress.dll v20.0, but then won't be available until v2.9.3 and upgrades from that.

**Comment by phw198** [comment]
### Patch Available

:package: For those "stuck" on either v2.9.1 or v2.9.2, you can download [SharpCompress-patch.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7550711/SharpCompress-patch.zip) and apply the files in the same way as a hotfix ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

You should then be able to upgrade successfully!

Alternatively, download and run the [v2.9.2 Setup.exe](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.9.2-alpha/Setup.exe) directly to upgrade from v2.9.1

**Comment by MartinJJ** [comment]
Thanks Paul,

The update via 'v2.9.2 Setup.exe' directly to upgrade from v2.9.1 works perfetly !

Regards, Martin

**Comment by jcrummie** [comment]
I have tried everything in this message and keep getting the same error - "object reference not set to instance of object".  Software use to work great but know I cannot get it to install,  I have sent in the error log multiple times.  HELP!!!!!

**Comment by phw198** [comment]
@jcrummie 
* Download [2.9.2 setup.exe](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.9.2-alpha/Setup.exe)
* Make sure `outlookgooglecalendarsync.exe` is not running (check the Task Manager processes)
* Execute the `Setup.exe`

Where are you sending the error log to?

**Comment by jcrummie** [comment]
Thank you for the instructions.   I will try them tomorrow and let you know.  When I tried the install before and it failed a dialogue box asked if I wanted to send the error log and I said yes.

**Comment by jcrummie** [comment]
I followed these instructions and received the same error.  Attached is the log file.  I really liked this product and want to use it
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7915134/OGcalsync.log)
.

**Comment by phw198** [comment]
@jcrummie Your issue is different from this one, so I have opened #1379 to track the problem you're reporting.
