### ISSUE TITLE
Recurring master appointment update failed. [0x800706BA] during GetCOMIPFromRCW()

### ISSUE THREAD

**Issue by BarryBJB** [phw198/OutlookGoogleCalendarSync#1395]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.9.3.0  
**Edition**: Installed / Portable  
**Sync Direction**: G->O / O->G / O<->G

**Bug Description**  
Since most recent update (2.9.3.0) I occasionally (once or twice a day) get the message below. Once it happens it´s a permanent issue. If I kill the app and restart all is OK. Until the next time................

NB - It´s not clear that anyone monitors these threads and I know a lot of other people are experiencing the same problem, so FYI - I have solved the problem by reverting to 2.9.1.0. Of course YMMV. Good luck!

`"Appointment update failed. Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)."`

**Steps to Reproduce the Issue**  
1. Go to...
1. Click on...

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.
There is no OGcalsync.log File for today´s date (ie most recent failure).

**Comment by BarryBJB** [comment]
Since most recent update (2.9.3.0) I occasionally (once or twice a day) get the message below.  Once it happens it´s a permanent issue.  If I kill the app and restart all is OK.  Until the next time................


"Appointment update failed. Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)."

**Comment by BarryBJB** [comment]
PS - There is no OGcalsync.log File for today´s date (ie most recent failure).

**Comment by kwagner115** [comment]
I too have been experiencing the same issue. 

And I am running 2.9.3.2.

**Comment by WarningU2** [comment]
I am experiencing the same issue.   If I shutdown OGS and restart the sync completes fine.   

```
2022-03-14 19:25:54,236 ERROR  9 OutlookGoogleCalendarSync.Console [278] -  Appointment update failed.
2022-03-14 19:25:54,716 ERROR  9 OutlookGoogleCalendarSync.Console [278] -  Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).
2022-03-14 19:25:54,770 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [28] -  System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).
2022-03-14 19:25:54,772 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004002,-2147467262; Location: GetCOMIPFromRCW() in <Unknown File>
2022-03-14 19:25:54,773 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Outlook.MAPIFolder.get_Items()
   at OutlookGoogleCalendarSync.Recurrence.CompareOutlookPattern(Event ev, RecurrencePattern& aiOpattern, Direction syncDirection, StringBuilder sb, Int32& itemModified) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:line 172
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 493
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 360
2022-03-14 19:25:54,775 DEBUG  9 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Outlook appointment update failed. Continue with synchronisation?
2022-03-14 19:25:54,902 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.
2022-03-14 19:26:00,770 DEBUG  9 System.Windows.Forms.OgcsMessageBox [87] -  Response: Yes
2022-03-14 19:26:01,012 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [430] -  Processing recurring master appointment.
2022-03-14 19:26:01,013 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [433] -  Processing >> 2022-04-15 (R) => "Good Friday"
2022-03-14 19:26:01,050 ERROR  9 OutlookGoogleCalendarSync.Console [278] -  Appointment update failed.
2022-03-14 19:26:01,051 ERROR  9 OutlookGoogleCalendarSync.Console [278] -  Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).
2022-03-14 19:26:01,083 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [28] -  System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).
2022-03-14 19:26:01,084 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004002,-2147467262; Location: GetCOMIPFromRCW() in <Unknown File>
2022-03-14 19:26:01,085 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Outlook.MAPIFolder.get_Items()
   at OutlookGoogleCalendarSync.Recurrence.CompareOutlookPattern(Event ev, RecurrencePattern& aiOpattern, Direction syncDirection, StringBuilder sb, Int32& itemModified) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:line 172
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 493
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 360
2022-03-14 19:26:01,086 DEBUG  9 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Outlook appointment update failed. Continue with synchronisation?
2022-03-14 19:26:01,131 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.
2022-03-14 19:26:03,712 DEBUG  9 System.Windows.Forms.OgcsMessageBox [87] -  Response: No
2022-03-14 19:26:03,719 INFO  9 OutlookGoogleCalendarSync.Sync.Engine+Calendar [689] -  User chose not to continue sync.
2022-03-14 19:26:04,561 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [148] -  Setting 'CompletedSyncs' updated to '8939'
2022-03-14 19:26:04,561 INFO  1 OutlookGoogleCalendarSync.Console [282] -  Sync finished!
```

**Comment by galexmay** [comment]
I have the same issue
```
Appointment update failed.
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).
0 entries updated.
```
Running latest Alpha version as the stable release had another bug that I had a problem with.

**Comment by WarningU2** [comment]
Problem is still occuring.   Love the program but this release is most likely the buggiest

**Comment by BarryBJB** [comment]
It´s not clear that anyone monitors these threads and I know a lot of other people are experiencing the same problem, so FYI - I have solved the problem by reverting to 2.9.1.0. Of course YMMV. Good luck!

**Comment by WarningU2** [comment]
Good plan Barry.  I will do the same.    I believe the threads are monitored but Paul must have bigger fish

**Comment by BarryBJB** [comment]
> Good plan Barry. I will do the same. I believe the threads are monitored but Paul must have bigger fish

It´s been working for 24 hours+ without crashing.  It maybe that there are later updates that also work, but 2.9.1.0 is good for me.  PS When I "downgraded" I lost the settings and had to start from scratch.  Not a big deal, but good to know in advance.

**Comment by phw198** [comment]
> I believe the threads are monitored but Paul must have bigger fish

Indeed, it's been a busy patch!

> this release is most likely the buggiest

It brought in a massive change with the addition of Profiles - the call for early adopters was limited....so onwards to alpha release it was.

> When I "downgraded" I lost the settings and had to start from scratch.

If actually upgrading from a previous version, the `settings.xml` will be backed up prior to upgrade, so this can be used if reverting back. If you started with v2.9.3, then there is no formal "downgrade".

In https://github.com/phw198/OutlookGoogleCalendarSync/issues/1400#issuecomment-1067882842, #1023 @Curtalain said

> I started the DCOM server in Services Administration from the control panel and it works

Can anyone verify if this works for them also??

**Comment by phw198** [comment]
* Is this happening for anyone which just a **single** Profile configured?
* Does the problem happen on the first sync after starting OGCS, or does it take time before the problem hits?
* NB: I really need complete log files, not just snippets to troubleshoot better

:package: Meanwhile, here's a patch with extra logging around the problem - [v2.9.3.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8405145/v2.9.3.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes and upload your logfile after applying and encountering the issue again. Thanks!

**Comment by WarningU2** [comment]
I only have the default Profile Paul.   The problem takes time for it to occur.   I believe it is when I have changed an existing entry on my outlook.    Next time it happens I will update this ticket with the full log files.

**Comment by WarningU2** [comment]
I have implemented the hotfix.  Running 2.9.3.9

**Comment by WarningU2** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8414298/OGcalsync.log)

Issue occurred again.  Attaching log post hotfix with error logging. 


2022-04-04 11:03:17,841 ERROR  11 OutlookGoogleCalendarSync.Console [278] -  Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA).

**Comment by WarningU2** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8428122/OGcalsync.log)

Another error this morning.

**Comment by phw198** [comment]
:package: Please check if this is now resolved with [v2.9.3.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8459226/v2.9.3.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

When the issue occurs, OGCS should automatically retry the sync after a few seconds.

**Comment by WarningU2** [comment]
Fix applied.

**Comment by BarryBJB** [comment]
Hi - I´ve been travelling for the last few weeks, so I haven´t been able to try any of the patches yet.  My question is - Does 2.9.4 alpha already contain the fix from 2.9.3.11 ie Can I go straight to that and skip the 2.9.3 patches?

**Comment by phw198** [comment]
@BarryBJB No, the changes were not included in v2.9.4 as there was no evidence it provided a fix. I have now pulled in the 2.9.4 release changes to this hotfix, so please apply this.

:package: [v2.9.4.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8604024/v2.9.4.8.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

In some sense, it might be good to run v2.9.4.0 anyway and see if this issue appears again (I suspect it might not), then apply v2.9.4.8 to confirm it disappears...

Let me know how it goes.

**Comment by phw198** [comment]
Is anyone still experiencing this bug under a vanilla alpha release (ie 2.9.4.0 or 2.9.5.0)? Seems to have gone suspiciously quiet, so maybe this hotfix isn't required any longer...

**Comment by WarningU2** [comment]
Sorry Paul I reverted to the standard version of the product due to multiple issues with the alpha.    Don't know if the issue is still occurring   
  

  

  
  
  Stephen Warner | 1180 Bellview St. Burlington ON L7S1C7 | h.(905)634-4629 c.(905)317-7765

      
  
  
>
