### ISSUE TITLE
Profiles - Unhandled exception when selecting 2nd profile from drop down

### ISSUE THREAD

**Issue by SDeGonge** [phw198/OutlookGoogleCalendarSync#1396]
**OGCS Version**: v2.9.3.3  
**Edition**: Portable  
**Sync Direction**: O<->G

**Bug Description**  
Profile - Unhandled exception when selecting 2nd profile from drop down.
![image](https://user-images.githubusercontent.com/14916505/156472977-913ebe26-c4c7-48c4-8ded-a24d5d89d2a8.png)
![image](https://user-images.githubusercontent.com/14916505/156472881-03b8549f-a492-41f9-a25a-a81aca23ca0a.png)
<details><summary>Crash stacktrace</summary>

```
=========================== Error Details ==========================================
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '2' is not valid for 'SelectedIndex'.
Parameter name: SelectedIndex
   at System.Windows.Forms.DomainUpDown.set_SelectedIndex(Int32 value)
   at OutlookGoogleCalendarSync.Forms.Main.UpdateGUIsettings_Profile() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 470
   at OutlookGoogleCalendarSync.SettingsStore.Calendar.SetActive() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\SettingsStore\Calendar.cs:line 203
   at OutlookGoogleCalendarSync.Forms.Main.ddProfile_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1061
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookGoogleCalendarSync
    Assembly Version: 2.9.8093.33009
    Win32 Version: 2.9.3.3
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/OutlookGoogleCalendarSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
log4net
    Assembly Version: 2.0.12.0
    Win32 Version: 2.0.12.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4435.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Google.Cloud.Logging.Log4Net
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Cloud.Logging.Log4Net.DLL
----------------------------------------
Google.Cloud.Logging.V2
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Cloud.Logging.V2.DLL
----------------------------------------
Google.Protobuf
    Assembly Version: 3.17.3.0
    Win32 Version: 3.17.3.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Protobuf.DLL
----------------------------------------
Google.Cloud.Logging.Type
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Cloud.Logging.Type.DLL
----------------------------------------
Google.Api.Gax
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Api.Gax.DLL
----------------------------------------
Google.Api.CommonProtos
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Api.CommonProtos.DLL
----------------------------------------
Google.Api.Gax.Grpc
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Api.Gax.Grpc.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Apis.Core.DLL
----------------------------------------
Grpc.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.1.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Grpc.Core.DLL
----------------------------------------
Grpc.Core.Api
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Grpc.Core.Api.DLL
----------------------------------------
Grpc.Auth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Grpc.Auth.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.1.25517
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Squirrel
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.1
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Squirrel.DLL
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/NuGet.Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Splat.DLL
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
NodaTime
    Assembly Version: 2.4.13.0
    Win32 Version: 2.4.13.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/NodaTime.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1507
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
Google.Apis.Calendar.v3
    Assembly Version: 1.54.0.2410
    Win32 Version: 1.54.0.2410
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Apis.Calendar.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.54.0.0
    Win32 Version: 1.54.0.0
    CodeBase: file:///D:/_NAS/Users/Sam/Apps/OGCS/Google.Apis.DLL
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
=========================== END Error Details ==========================================
```
</details>

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8173804/OGcalsync.log)
[settings.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8173807/settings.zip)

**Comment by SDeGonge** [comment]
Update: I created a 3rd profile then deleted it. Went back to the 2nd profile any the exception was corrected. Everything looks okay now.

**Comment by SDeGonge** [comment]
Spoke too soon! Still experiencing the problem, method to fix was the same.
Note that I also had another issue which may be related to this problem (see #1397).

**Comment by SDeGonge** [comment]
sorry about that...clicked 'close with comment' instead of 'comment'.

**Comment by phw198** [comment]
Is this consistent? Without creating and deleting the third profile, is there anything specific you are doing before hand to the profile configuration(s)? Possibly around altering the sync direction to/from bi-directional?

:link: [Code](https://github.com/phw198/OutlookGoogleCalendarSync/blob/issue-1394/src/OutlookGoogleCalendarSync/Forms/MainForm.cs#L470)

**Comment by SDeGonge** [comment]
> Is this consistent? Without creating and deleting the third profile, is there anything specific you are doing before hand to the profile configuration(s)? Possibly around altering the sync direction to/from bi-directional?
> 
> 🔗 [Code](https://github.com/phw198/OutlookGoogleCalendarSync/blob/issue-1394/src/OutlookGoogleCalendarSync/Forms/MainForm.cs#L470)

The error is consistent. The profiles are configured for bi-direction. Creating & deleting the third profile fixes the problem, however, it comes back after restarting the application.

To duplicate the error...
1. Launch OutlookGoogleCalendarSync.exe
2. Select the 2nd profile
3. Error occurs
4. Add a temporary profile and click Save (added to position 2)
5. Select any profile
6. No Errors
7. Delete the temporary profile and save
8. Select any profile
9. No Errors
10. Exit OGCS
11. Go to step 1 (error comes back)

Word doc attached with my configuration
[OGCS Issue 1396.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8240893/OGCS.Issue.1396.zip)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8240895/OGcalsync.log)

**Comment by phw198** [comment]
Thanks I was finally able to replicate this using your `settings.xml` file :+1: 

:package: This should now be resolved with [v2.9.3.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8402286/v2.9.3.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by SDeGonge** [comment]
v2.9.3.7 appears to have corrected the problem.

**Comment by phw198** [comment]
:package: Final build to include [1d9defb](https://github.com/phw198/OutlookGoogleCalendarSync/commit/1d9defbc0653aaa03c7f98ffa4ba2645f210b176) - [v2.9.3.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8405279/v2.9.3.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
