### ISSUE TITLE
Error sync / default code 403 - Daily Limit Exceeded

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#14]
Dears,  
  
I'm using OG calsync not for a long time, but very positive about it's
functioning. Since a day or two I'm confronted with the following problem;  

    
    
    Reading Google Calendar Entries...
    Unable to connect to the Google calendar. The following error occurred:
    Google.Apis.Requests.RequestError
    Daily Limit Exceeded [403]
    Errors [
        Message[Daily Limit Exceeded] Location[ - ] Reason[dailyLimitExceeded] Domain[usageLimits]

I've checked at my cloudhost, which has confirmed that the application is able
to connect to internet. So apparently the problem lies elsewhere.  
  
Can you help me out ?  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 171](http://outlookgooglecalendarsync.codeplex.com/workitem/171)
**Status:**	Resolved
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Jan 28, 2016 at 8:03 PM
**Reported by:**	wernerbastiaansen
**Updated on:**	Mar 11, 2016 at 10:36 AM
**Updated by:**	durbalau

**Comment by phw198** [comment]
On *2016-01-29 04:23:54 UTC*, **deswong** commented:

Also getting the same error.

Log file information:
2016-01-29 07:13:10,293 INFO 1 OutlookGoogleCalendarSync.Program [0] - Program started: v2.1.1.0
2016-01-29 07:13:10,355 INFO 1 OutlookGoogleCalendarSync.Program [0] - Storing user files in roaming directory: C:\Users\******\AppData\Roaming\Outlook Google Calendar Sync
2016-01-29 07:13:10,371 DEBUG 1 OutlookGoogleCalendarSync.XMLManager [0] - Retrieved setting 'Portable' with value 'false'
2016-01-29 07:13:10,371 DEBUG 1 OutlookGoogleCalendarSync.XMLManager [0] - Retrieved setting 'LoggingLevel' with value 'OFF'
2016-01-29 07:13:10,371 INFO 1 OutlookGoogleCalendarSync.Settings [0] - Logging level configured to 'OFF'
2016-01-29 07:14:33,420 WARN 1 DotNetOpenAuth.Messaging [0] - Multiple message types seemed to fit the incoming data: {AccessTokenSuccessResponse (2.0),
UnauthorizedResponse (2.0),
}
2016-01-29 07:20:22,074 INFO 1 OutlookGoogleCalendarSync.Settings [0] - C:\Users\******\AppData\Roaming\Outlook Google Calendar Sync\settings.xml
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] - OUTLOOK SETTINGS:-
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Service: DefaultMailbox
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Calendar: Default Calendar
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Filter String: g
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] - GOOGLE SETTINGS:-
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Calendar: Work - ********
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   API attendee limit in effect: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   API attendee limit last reached: 10/09/2015 3:29:12 PM
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] - SYNC OPTIONS:-
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -  Main
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   SyncDirection: Outlook → Google
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   DaysInThePast: 1
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   DaysInTheFuture:60
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   SyncInterval: 30
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   SyncIntervalUnit: Minutes
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Push Changes: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   AddDescription: True; OnlyToGoogle: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   AddReminders: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   AddAttendees: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   MergeItems: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   DisableDelete: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   ConfirmOnDelete: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Obfuscate Words: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] - PROXY:-
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Type: Custom
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Server Name: 127.0.0.1
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Port: 3128
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   UserName: 
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Password: 
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] - APPLICATION BEHAVIOUR:-
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   ShowBubbleTooltipWhenSyncing: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   StartOnStartup: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   StartInTray: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   MinimiseToTray: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   MinimiseNotClose: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   ShowBubbleWhenMinimising: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Portable: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   CreateCSVFiles: False
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   VerboseOutput: True
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Logging Level: DEBUG
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] - ENVIRONMENT:-
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Current Locale: en-AU
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Short Date Format: d/MM/yyyy
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Short Time Format: h:mm tt
2016-01-29 07:20:22,199 INFO 1 OutlookGoogleCalendarSync.Settings [0] -   Completed Syncs: 4614
2016-01-29 07:20:26,100 DEBUG 1 OutlookGoogleCalendarSync.MainForm [0] - Manual sync started.
2016-01-29 07:20:26,116 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Sync version: 2.1.1.0
2016-01-29 07:20:26,116 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Sync started at 29/01/2016 7:20:26 AM
2016-01-29 07:20:26,116 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Syncing from 28/01/2016 to 30/03/2016
2016-01-29 07:20:26,116 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Outlook → Google
2016-01-29 07:20:26,116 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - --------------------------------------------------
2016-01-29 07:20:26,116 INFO 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Deregistering from Outlook appointment change events...
2016-01-29 07:20:26,116 DEBUG 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Removing 1 Outlook event handler hooks.
2016-01-29 07:20:26,365 INFO 15 OutlookGoogleCalendarSync.MainForm [0] - Reading Outlook Calendar Entries...
2016-01-29 07:20:26,802 INFO 15 OutlookGoogleCalendarSync.MainForm [0] - 18 Outlook calendar entries found.
2016-01-29 07:20:26,911 INFO 15 OutlookGoogleCalendarSync.MainForm [0] - --------------------------------------------------
2016-01-29 07:20:27,020 INFO 15 OutlookGoogleCalendarSync.MainForm [0] - Reading Google Calendar Entries...
2016-01-29 07:20:27,020 DEBUG 15 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all events from Google: 28/01/2016 -> 30/03/2016
2016-01-29 07:20:28,334 INFO 15 OutlookGoogleCalendarSync.MainForm [0] - Unable to connect to the Google calendar. The following error occurred:
2016-01-29 07:20:28,446 INFO 15 OutlookGoogleCalendarSync.MainForm [0] - Google.Apis.Requests.RequestError
Daily Limit Exceeded [403]
Errors [
    Message[Daily Limit Exceeded] Location[ - ] Reason[dailyLimitExceeded] Domain[usageLimits]
]
2016-01-29 07:20:28,446 ERROR 15 OutlookGoogleCalendarSync.MainForm [0] -    at Google.Apis.Requests.Request.AsyncRequestResult.GetResponse()
   at Google.Apis.Requests.ServiceRequest`1.GetResponse()
   at Google.Apis.Requests.ServiceRequest`1.Fetch()
   at OutlookGoogleCalendarSync.GoogleCalendar.GetCalendarEntriesInRange(DateTime from, DateTime to)
   at OutlookGoogleCalendarSync.GoogleCalendar.GetCalendarEntriesInRange()
   at OutlookGoogleCalendarSync.MainForm.synchronize()
2016-01-29 07:20:30,384 DEBUG 1 OutlookGoogleCalendarSync.XMLManager [0] - Setting 'CompletedSyncs' updated to '4614'
2016-01-29 07:20:30,384 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - Operation aborted after 1 failed attempts!
2016-01-29 07:20:30,384 INFO 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Registering for Outlook appointment change events...
2016-01-29 07:20:30,416 DEBUG 1 OutlookGoogleCalendarSync.OutlookCalendar [0] - Create the timer for the push synchronisation
2016-01-29 07:20:30,416 DEBUG 1 OutlookGoogleCalendarSync.XMLManager [0] - Setting 'LastSyncDate' updated to '29/01/2016 7:20:26 AM'

**Comment by phw198** [comment]
On *2016-01-29 04:26:26 UTC*, **jeffreymfields** commented:

Same here...

**Comment by phw198** [comment]
On *2016-01-29 04:27:50 UTC*, **deswong** commented:

Apparently this has previously happened with the app - I'm not sure though of the requests per day limit that this has.

**Comment by phw198** [comment]
On *2016-01-29 04:33:37 UTC*, **deswong** commented:

See 
https://outlookgooglecalendarsync.codeplex.com/wikipage?title=FAQs%20%2f%20Known%20Issues&version;=9#usagelimits for a possible fix.


I have this unticked as this has caused issues with the large amount of attendees I have on some calendar invites in the past.


But this still is stuck until the next daily reset.

**Comment by phw198** [comment]
On *2016-01-29 18:54:31 UTC*, **durbalau** commented:

Same problem here.
I don't have "Attendees" checked.

What I find strange is that the Sync is done every hour, even if I set the "Interval" to more hours. So, basically maybe the limit is reached in this case (1,000,000 queries per day).

**Comment by phw198** [comment]
On *2016-01-31 19:10:29 UTC*, **phw198** commented:

It appears the popularity of the tool has meant we are now starting to reach the 1m API calls a day that Google provides for free.


However, as durbalau has highlighted there is a issue logged for a sync interval bug - so this might help alleviate the limit issue for while if I can get that fixed.

**Comment by phw198** [comment]
On *2016-02-01 06:37:21 UTC*, **phw198** commented:

v2.1.2.0 is out which should resolve the above problem with the sync interval, as well as the ability to subscribe for a guaranteed API quota.

**Comment by phw198** [comment]
On *2016-03-11 18:08:43 UTC*, **romke** commented:

To reduce the numbers of syncs. Can a schedule be added. e.g only sync during daytime hours: 8:00h till 19:00h. I don't need to sync during the night. I asume this is valid for many users.

**Comment by phw198** [comment]
On *2016-03-11 18:36:55 UTC*, **durbalau** commented:

Until a daytime (8:00-19:00) implementation, I successfully reduced the number of syncs by setting the sync interval to 24 Hours and I use also the "Push Outlook changes immediately" (check-box). So, I don't care about daytime hours.

Note: I use Outlook->Google sync.
