### ISSUE TITLE
Object reference not set - cannot update Google item when syncing colours and Outlook has no category

### ISSUE THREAD

**Issue by MartinJJ** [phw198/OutlookGoogleCalendarSync#1422]
> Checklist:-
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

I set  Logging level to 'debug'. 

**OGCS Version**: 2.9.4.0  - alpha
**Edition**: Installed / 
**Sync Direction**:   O->G 

**Bug Description**  
 

**Steps to Reproduce the Issue**  
After version update  run a SYNC

**Any other information**  
```
Sync version: 2.9.4.0

Profile: Default

Sync started at 2022-04-13 12:03:15

Syncing from 2022-03-29 to 2022-10-11

Outlook → Google

Finding Calendar Entries
Scanning Outlook calendar...

83 Outlook calendar entries found.

Scanning Google calendar...
81 Google calendar entries found.

17 are exceptions to recurring events.

Total inc. recurring items spanning sync date range...
Outlook 82, Google 82
Checking for orphaned Google items
Matching calendar items...


0 Google calendar entries to be deleted.

0 Google calendar entries to be created.

82 calendar entries to be compared.

Comparing 82 existing Google calendar entries

Event update failed.
Object reference not set to an instance of an object.
0 entries updated.

Sync finished!
```
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8480458/OGcalsync.log)

```
2022-04-13 12:02:25,364 ERROR  20 OutlookGoogleCalendarSync.Console [278] -  Event update failed.
2022-04-13 12:02:25,366 ERROR  20 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2022-04-13 12:02:25,399 ERROR  20 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2022-04-13 12:02:25,400 ERROR  20 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in GoogleCalendar.cs:784:21
2022-04-13 12:02:25,401 ERROR  20 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557
2022-04-13 12:02:25,402 DEBUG  20 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Google event update failed. Continue with synchronisation?
```

**Comment by OliGross** [comment]
I am experiencing the same issue
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8482187/OGcalsync.log)

**Comment by phw198** [comment]
:package: Please confirm if this is now resolved with [hotfix v2.9.4.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8508550/v2.9.4.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

**Comment by DirkBloedorn** [comment]
> 📦 Please confirm if this is now resolved with [hotfix v2.9.4.3.zip]
Had the same issue. The hotfix workes for me. Thanks!

**Comment by DirkBloedorn** [comment]
> 📦 Please confirm if this is now resolved with [hotfix v2.9.4.3.zip]

Had the same issue. The hotfix workes for me. Thanks!

**Comment by anders-m** [comment]
And hotfix works here :-)

**Comment by vprichard** [comment]
I had the same issue after the update to v2.9.4.0, and the hotfix to v2.9.4.3 fixed the problem for me.

**Comment by dgkasi** [comment]
Hotfix to v2.9.4.3 also fixed the problem for me. Thanks a lot!

**Comment by sansnil** [comment]
The hotfix worked for me as well - thanks!
