### ISSUE TITLE
Event update failed - Corrupted REG_TZI_FORMAT

### ISSUE THREAD

**Issue by Samuel-Oliveira** [phw198/OutlookGoogleCalendarSync#1442]
Log: 

```
2022-04-23 09:53:44,013 DEBUG  27 OutlookGoogleCalendarSync.Recurrence [32] -  Creating Google iCalendar definition for recurring event.
2022-04-23 09:53:44,073 ERROR  27 OutlookGoogleCalendarSync.Console [278] -  Event update failed.
2022-04-23 09:53:44,202 ERROR  27 OutlookGoogleCalendarSync.Console [278] -  O ID de fuso horário 'E. South America Standard Time' foi encontrado no computador local, mas as informações do Registro foram corrompidas.
2022-04-23 09:53:44,203 ERROR  27 OutlookGoogleCalendarSync.Console [278] -  A estrutura REG_TZI_FORMAT está corrompida.
2022-04-23 09:53:44,203 ERROR  27 OutlookGoogleCalendarSync.Console [278] -  Nome do parâmetro: bytes
2022-04-23 09:53:44,256 ERROR  27 OutlookGoogleCalendarSync.OGCSexception [28] -  System.InvalidTimeZoneException: O ID de fuso horário 'E. South America Standard Time' foi encontrado no computador local, mas as informações do Registro foram corrompidas.
2022-04-23 09:53:44,257 ERROR  27 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131500,-2146233088; Location: FindSystemTimeZoneById() in <Unknown File>
2022-04-23 09:53:44,257 ERROR  27 OutlookGoogleCalendarSync.OGCSexception [21] -  InnerException:-
2022-04-23 09:53:44,257 ERROR  27 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentException: A estrutura REG_TZI_FORMAT está corrompida.
Nome do parâmetro: bytes
2022-04-23 09:53:44,258 ERROR  27 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80070057,-2147024809; Location: .ctor() in <Unknown File>
2022-04-23 09:53:44,258 ERROR  27 OutlookGoogleCalendarSync.OGCSexception [65] -     em System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   em OutlookGoogleCalendarSync.Recurrence.BuildGooglePattern(AppointmentItem ai, Event ev) na C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:linha 41
   em OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) na C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:linha 684
   em OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) na C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:linha 555
2022-04-23 09:53:44,259 DEBUG  27 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Google event update failed. Continue with synchronisation?
```

Version: 2.9.4.0
Windows 11 Pro

**Comment by phw198** [comment]
:package: Please confirm if this is now resolved with [hotfix v2.9.4.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8602927/v2.9.4.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

When an unrecognised time zone is encountered, OGCS should now provide a pop-up window allowing you to manually map that time zone to one that does exists.

**Comment by Samuel-Oliveira** [comment]
I will test this hotfix and bring to u a feedback!
Maybe in a day or two, don't happen all the time. 
Thanks for u time!

**Comment by phw198** [comment]
Hi @Samuel-Oliveira, has it happened again yet?

**Comment by Samuel-Oliveira** [comment]
Not. Sorry for not returning. 
I Will Close. Thx.

**Comment by phw198** [comment]
I guess that means we don't know if the fix works yet then. Can you force the issue to occur by editing the Outlook appointment that had the problem before? Just make a pretend change like adding a space to the subject, removing it, saving and closing - hopefully this will make it sync again to Google and cause the timezone problem...

**Comment by wgalafassijr** [comment]
I have the same issue with version 2.9.5. Same result with 2.9.0 
Only happen with recurring events
OS: windows 11 22h2
Outlook: 2212 build 15928.20198
```
2023-01-18 09:27:01,146 INFO  11 OutlookGoogleCalendarSync.Console [287] -  Creating 1 Google calendar entries
2023-01-18 09:27:01,414 DEBUG  11 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [409] -  Processing >> 16/01/2023 11:00 (R) => "rever plano internet 2001"
2023-01-18 09:27:01,416 DEBUG  11 OutlookGoogleCalendarSync.Recurrence [32] -  Creating Google iCalendar definition for recurring event.
2023-01-18 09:27:01,445 ERROR  11 OutlookGoogleCalendarSync.Console [283] -  16/01/2023 11:00 (R) "rever plano internet 2001"
2023-01-18 09:27:01,449 ERROR  11 OutlookGoogleCalendarSync.Console [283] -  Event creation failed.
2023-01-18 09:27:01,449 ERROR  11 OutlookGoogleCalendarSync.Console [283] -  The time zone ID 'E. South America Standard Time' was found on the local computer, but the registry information was corrupt.
2023-01-18 09:27:01,449 ERROR  11 OutlookGoogleCalendarSync.Console [283] -  The REG_TZI_FORMAT structure is corrupt.
2023-01-18 09:27:01,450 ERROR  11 OutlookGoogleCalendarSync.Console [283] -  Parameter name: bytes
2023-01-18 09:27:01,519 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [28] -  System.InvalidTimeZoneException: The time zone ID 'E. South America Standard Time' was found on the local computer, but the registry information was corrupt.
2023-01-18 09:27:01,520 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131500,-2146233088; Location: FindSystemTimeZoneById() in <Unknown File>
2023-01-18 09:27:01,521 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [21] -  InnerException:-
2023-01-18 09:27:01,521 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ArgumentException: The REG_TZI_FORMAT structure is corrupt.
Parameter name: bytes
2023-01-18 09:27:01,522 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80070057,-2147024809; Location: .ctor() in <Unknown File>
2023-01-18 09:27:01,522 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [65] -     at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at OutlookGoogleCalendarSync.Recurrence.BuildGooglePattern(AppointmentItem ai, Event ev) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:line 41
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 413
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 366
```

**Comment by phw198** [comment]
@wgalafassijr Are you still encountering this error? If so I'm needing to get v2.9.6 out first, but then I could pull in the hoped hotfix for you to test...

**Comment by phw198** [comment]
:package: Fix has now been updated onto latest alpha release - [hotfix v2.9.6.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/10610805/v2.9.6.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.
