### ISSUE TITLE
v2.9.4 Portable Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by asgreenb** [phw198/OutlookGoogleCalendarSync#1459]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.9.4
Portable

**Problem Description**  
Error: Object reference not set to an instance of an object.

**Steps to Reproduce the Issue**  
Synch

**Any other information**  
From the log files
This looks strange to me:  C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557

```
2022-05-04 07:52:04,865 ERROR  14 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557
2022-05-04 07:52:04,865 DEBUG  14 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Google event update failed. Continue with synchronisation?
2022-05-04 07:52:04,898 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.
2022-05-04 07:52:05,410 DEBUG  14 System.Windows.Forms.OgcsMessageBox [87] -  Response: Yes
2022-05-04 07:52:05,411 DEBUG  14 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [643] -  Processing >> 3/5/2021 10:00 AM (R) => "Adam and John Weekly 1:1"
2022-05-04 07:52:05,412 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [32] -  Creating Google iCalendar definition for recurring event.
2022-05-04 07:52:05,432 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [48] -  RRULE:FREQ=WEEKLY;UNTIL=20220905T150000Z
2022-05-04 07:52:05,449 ERROR  14 OutlookGoogleCalendarSync.Console [278] -  Event update failed.
2022-05-04 07:52:05,449 ERROR  14 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2022-05-04 07:52:05,515 ERROR  14 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2022-05-04 07:52:05,515 ERROR  14 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in GoogleCalendar.cs:784:21
2022-05-04 07:52:05,515 ERROR  14 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557
2022-05-04 07:52:05,515 DEBUG  14 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Google event update failed. Continue with synchronisation?
2022-05-04 07:52:05,532 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.
2022-05-04 07:52:06,019 DEBUG  14 System.Windows.Forms.OgcsMessageBox [87] -  Response: Yes
2022-05-04 07:52:06,030 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [601] -  11/19/2020 8:30 AM (R) => "Change Advisory Board Meeting"
2022-05-04 07:52:06,030 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [602] -  This is a recurring appointment with 74 exceptions that will now be iteratively compared.
2022-05-04 07:52:23,465 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [426] -  Finding Google instance for Outlook exception:-
2022-05-04 07:52:23,481 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [427] -    Original date: 05/05/2022
2022-05-04 07:52:23,499 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [431] -    Current  date: 05/05/2022
2022-05-04 07:52:23,515 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [631] -  Matching Google Event recurrence found.
2022-05-04 07:52:23,582 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [601] -  8/20/2012 3:30 PM (R) => "Media Roundup:"
2022-05-04 07:52:23,582 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [602] -  This is a recurring appointment with 16 exceptions that will now be iteratively compared.
2022-05-04 07:52:24,465 DEBUG  14 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [643] -  Processing >> 2/10/2012 10:30 AM (R) => "Admin: Innate, Clock, Status"
2022-05-04 07:52:24,465 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [32] -  Creating Google iCalendar definition for recurring event.
2022-05-04 07:52:24,482 DEBUG  14 OutlookGoogleCalendarSync.Recurrence [48] -  RRULE:FREQ=WEEKLY
2022-05-04 07:52:24,532 ERROR  14 OutlookGoogleCalendarSync.Console [278] -  Event update failed.
2022-05-04 07:52:24,532 ERROR  14 OutlookGoogleCalendarSync.Console [278] -  Object reference not set to an instance of an object.
2022-05-04 07:52:24,631 ERROR  14 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2022-05-04 07:52:24,632 ERROR  14 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in GoogleCalendar.cs:784:21
2022-05-04 07:52:24,632 ERROR  14 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 784
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 557
2022-05-04 07:52:24,632 DEBUG  14 System.Windows.Forms.OgcsMessageBox [72] -  Sync item failed: Google event update failed. Continue with synchronisation?
2022-05-04 07:52:24,665 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.
2022-05-04 07:56:44,712 DEBUG  14 System.Windows.Forms.OgcsMessageBox [87] -  Response: No
2022-05-04 07:56:44,713 INFO  14 OutlookGoogleCalendarSync.Sync.Engine+Calendar [592] -  User chose not to continue sync.
2022-05-04 07:56:45,164 DEBUG  1 System.Windows.Forms.OgcsMessageBox [72] -  Sync Failed: The synchronisation failed - check the Sync tab for further details.
Do you want to try again?
2022-05-04 07:56:45,176 INFO  1 OutlookGoogleCalendarSync.Forms.Main [891] -  Application window restored.
2022-05-04 07:56:46,816 DEBUG  1 System.Windows.Forms.OgcsMessageBox [87] -  Response: No
2022-05-04 07:56:46,816 INFO  1 OutlookGoogleCalendarSync.Sync.Engine+Calendar [97] -  User opted to abandon further syncs.
2022-05-04 07:56:46,817 ERROR  1 OutlookGoogleCalendarSync.Console [278] -  Sync aborted after 1 failed attempts!
2022-05-04 07:56:46,836 DEBUG  1 OutlookGoogleCalendarSync.Sync.Engine [97] -  ActiveProfile set to: None
2022-05-04 07:56:57,732 DEBUG  1 OutlookGoogleCalendarSync.Program [112] -  Shutting down application.
2022-05-04 07:56:57,747 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [118] -  De-referencing all Outlook application objects.
2022-05-04 07:56:57,782 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [133] -  Disconnecting from Outlook application.
2022-05-04 07:56:57,799 INFO  1 OutlookGoogleCalendarSync.Program [121] -  Application closed.
```

**Comment by h07d0q** [comment]
I'm getting this error too. glad you came first ;)
Getting this since some days every time a sync is started. Was waiting for the next alpha version, but now I installed v2.9.0.0 and everything runs again as expected.

**Comment by phw198** [comment]
Duplicates #1422
