### ISSUE TITLE
Remote Server Returned an error: (401) Unauthorized.  Google Handshare failed.

### ISSUE THREAD

**Issue by kokada26** [phw198/OutlookGoogleCalendarSync#1620]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v 2.9.0.0
**Edition**: Installed 
**Sync Direction**: O<->G

**Bug Description**  
Every time I try to sync, I receive same error messages in the sync log.

**Steps to Reproduce the Issue**  
1. Click "start sync" button.

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/11066233/OGcalsync.log)
```
2023-03-24 12:57:48,721 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [96] -  Authenticating with Google calendar service...
2023-03-24 12:57:48,722 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [100] -  Google credential file location: C:\Users\keaka\AppData\Roaming\Outlook Google Calendar Sync\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user
2023-03-24 12:57:48,745 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [110] -  User has provided authorisation and credential file saved.
2023-03-24 12:57:48,746 INFO  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [133] -  Refresh and Access token successfully retrieved.
2023-03-24 12:57:48,746 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [136] -  Access token expires 3/24/2023 1:49:48 PM
2023-03-24 12:57:48,752 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [214] -  Retrieving email address associated with Google account.
2023-03-24 12:57:48,990 DEBUG  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [231] -  Reading response.
2023-03-24 12:57:48,991 ERROR  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [234] -  {
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}

2023-03-24 12:57:48,993 WARN  24 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [238] -  The remote server returned an error: (401) Unauthorized.
2023-03-24 12:57:48,994 ERROR  24 OutlookGoogleCalendarSync.Console [278] -  The remote server returned an error: (401) Unauthorized.
2023-03-24 12:57:49,056 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [28] -  System.AggregateException: One or more errors occurred.
2023-03-24 12:57:49,058 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131500,-2146233088; Location: ThrowIfExceptional() in <Unknown File>
2023-03-24 12:57:49,059 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [21] -  InnerException:-
2023-03-24 12:57:49,060 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Net.WebException: The remote server returned an error: (401) Unauthorized.
2023-03-24 12:57:49,061 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131509,-2146233079; Location: DownloadDataInternal() in <Unknown File>
2023-03-24 12:57:49,197 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [28] -  System.ApplicationException: Google handshake failed.
2023-03-24 12:57:49,198 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131600,-2146232832; Location: get_Instance() in GoogleCalendar.cs:34:29
2023-03-24 12:57:49,199 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.get_Instance() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 34
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 410
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass24_0.<Start>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 216
2023-03-24 12:57:49,199 ERROR  9 OutlookGoogleCalendarSync.Console [278] -  Google handshake failed.
```

Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Google doesn't seem to like the contents of your credential file - can you try
1. Closing OGCS
2. Move or rename `C:\Users\keaka\AppData\Roaming\Outlook Google Calendar Sync\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user` out the way
3. Starting OGCS and click Sync
4. Reauthorise OGCS to manage your calendar
