### ISSUE TITLE
Google Event creation failed when GAL blocked. Operation aborted [0x80004004 (E_ABORT)]

### ISSUE THREAD

**Issue by Yikkayi** [phw198/OutlookGoogleCalendarSync#1651]
First time posting in GitHub!   Please forgive any mistakes.  Thank you!

**OGCS Version**: v2.9.7.0
**Edition**: Installed  
**Sync Direction**: O<->G

**Bug Description**  
Cannot create event in Google calendar when syncing from Outlook calendar.

**Steps to Reproduce the Issue**  
1. Create new event in Outlook
2. Start sync

**Any other information**  
```
2023-05-16 22:09:46,166 WARN  10 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [1349] -  It looks like the organiser changed time of appointment, but due to GAL policy we can't check who they are.
2023-05-16 22:10:18,388 WARN  10 OutlookGoogleCalendarSync.Sync.Engine+Calendar [537] -  That step took a long time! Issue #599
2023-05-16 22:10:19,153 ERROR  10 OutlookGoogleCalendarSync.Console [292] -  Event creation failed.
2023-05-16 22:10:19,174 ERROR  10 OutlookGoogleCalendarSync.Console [292] -  Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2023-05-16 22:10:19,261 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2023-05-16 22:10:19,266 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004004,-2147467260; Location: get_Recipients() in <Unknown File>
2023-05-16 22:10:19,268 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Recipients()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 444
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 366
2023-05-16 22:11:34,684 ERROR  10 OutlookGoogleCalendarSync.Console [292] -  Event creation failed.
2023-05-16 22:11:34,686 ERROR  10 OutlookGoogleCalendarSync.Console [292] -  Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2023-05-16 22:11:34,788 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
2023-05-16 22:11:34,790 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004004,-2147467260; Location: get_Recipients() in <Unknown File>
2023-05-16 22:11:34,790 ERROR  10 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Recipients()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 444
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 366
2023-05-16 22:11:42,572 ERROR  1 OutlookGoogleCalendarSync.Console [292] -  Sync aborted after 1 failed attempts!
2023-05-16 22:13:44,572 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [1024] -  No Outlook process available to attach to.
```

I'm not sure why the file path in the log says C:\Users\Paul\.  There is no Paul user on my computer.

**Comment by phw198** [comment]
Hi @Yikkayi and welcome :slightly_smiling_face: 

It appears your corporation has blocked access to the Global Address List, but you also have set OGCS to sync meeting attendees? This shouldn't be possible - once it detects GAL is blocked, the ability to sync attendees should be removed. However, I think this is only happening in the user interface and not during the sync.

:package: Please could you try with [hotfix v2.9.7.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11524583/v2.9.7.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) and let me know if it behaves better!

NB: The file path in the log is the compile-time path, ie not your computer.

**Comment by Yikkayi** [comment]
Problem solved!  Thank you!

**Comment by phw198** [comment]
Thanks for confirming @Yikkayi 
Reopening this issue until the fix is released into the next alpha.
