### ISSUE TITLE
Unable To Add New Entries

### ISSUE THREAD

**Issue by ptiseo-ep** [phw198/OutlookGoogleCalendarSync#1654]
**OGCS Version**: v2.9.7.0
**Edition**: Installed
**Sync Direction**: G->O

**Bug Description**  

Fresh, first-time install of OGCS on W11, Outlook v2304. A few events do get logged to Google before it fails.
```
2023-05-24 19:37:14,974 ERROR  16 OutlookGoogleCalendarSync.Console [292] -  Unable to add new entries into the Google Calendar.
2023-05-24 19:37:14,975 ERROR  16 OutlookGoogleCalendarSync.Console [292] -  Object reference not set to an instance of an object.
2023-05-24 19:37:15,094 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2023-05-24 19:37:15,095 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: CreateGoogleExceptions() in Recurrence.cs:635:49
2023-05-24 19:37:15,095 ERROR  16 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.Recurrence.CreateGoogleExceptions(AppointmentItem ai, String recurringEventId) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:line 635
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 398
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.outlookToGoogle(List`1 outlookEntries, List`1 googleEntries, String& bubbleText) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 593
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 493
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.<>c__DisplayClass11_1.<StartSync>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 129
2023-05-24 19:37:15,095 ERROR  16 OutlookGoogleCalendarSync.Console [292] -  Object reference not set to an instance of an object.
2023-05-24 19:37:15,219 DEBUG  1 System.Windows.Forms.OgcsMessageBox [72] -  Sync Failed: The synchronisation failed - check the Sync tab for further details.
Do you want to try again?
2023-05-24 19:37:15,248 INFO  1 OutlookGoogleCalendarSync.Forms.Main [963] -  Application window restored.
2023-05-24 19:37:22,322 DEBUG  1 System.Windows.Forms.OgcsMessageBox [87] -  Response: No
2023-05-24 19:37:22,323 INFO  1 OutlookGoogleCalendarSync.Sync.Engine+Calendar [97] -  User opted to abandon further syncs.
2023-05-24 19:37:22,323 ERROR  1 OutlookGoogleCalendarSync.Console [292] -  Sync aborted after 1 failed attempts!
```
**Steps to Reproduce the Issue**  

Install and sync

**Any other information**

**Comment by velaar** [comment]
I can confirm that this bug is also present in the portable version. 
Here is the stack, but seems to be pointing to the same code line. 

```
2023-05-25 12:43:52,344 ERROR  30 OutlookGoogleCalendarSync.Console [292] -  Object reference not set to an instance of an object.
2023-05-25 12:43:52,693 ERROR  30 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2023-05-25 12:43:52,694 ERROR  30 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: CreateGoogleExceptions() in Recurrence.cs:635:49
2023-05-25 12:43:52,695 ERROR  30 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.Recurrence.CreateGoogleExceptions(AppointmentItem ai, String recurringEventId) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Recurrence.cs:line 635
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 398
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.outlookToGoogle(List`1 outlookEntries, List`1 googleEntries, String& bubbleText) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 593
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 493
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.<>c__DisplayClass11_1.<StartSync>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 129
2023-05-25 12:43:52,695 ERROR  30 OutlookGoogleCalendarSync.Console [292] -  Object reference not set to an instance of an object.
```

**Comment by phw198** [comment]
I think you both omitted the preceding `WARN` log line of "Determined a 'duplicate' exists on that date - this will be deleted."?

:package: Hopefully this should now be resolved with [hotfix v2.9.7.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/11569923/v2.9.7.11.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by cinzas** [comment]
Hi @phw198, I can confirm. It solved the sync problem.
At least for me :)

**Comment by ptiseo-ep** [comment]
1. Yes, I did somehow forget one line at the start that was WARNing about duplicates. Sorry.
2. The hotfix fixed the hot for me too. I got full sync. :)

**Comment by nadabunny** [comment]
the hotfix also worked for me, thank you so much!
