### ISSUE TITLE
v2.10.1.0 Object reference not set to an instance of an object: Console.MuteClicks()

### ISSUE THREAD

**Issue by TheGooginator** [phw198/OutlookGoogleCalendarSync#1724]
**OGCS Version**: v2.10.1.0 
**Edition**: Installed
**Sync Direction**: O->G 

**Bug Description**  
I recently downloaded the newest Alpha version to a new computer and I exported my settings from my old computer and uploaded the XML to the new computer. I made sure my connections to Outlook and Google were working and then tried to start a manual sync. The error in the title appears right away. Below is a snippet of the log file.
```
2023-10-26 21:45:28,374 DEBUG  1 OutlookGoogleCalendarSync.Sync.Engine [97] -  ActiveProfile set to: None
2023-10-26 21:45:28,376 ERROR  1 OutlookGoogleCalendarSync.Console [292] -  Problem encountered during synchronisation.
2023-10-26 21:45:28,377 ERROR  1 OutlookGoogleCalendarSync.Console [292] -  Object reference not set to an instance of an object.
2023-10-26 21:45:28,401 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.NullReferenceException: Object reference not set to an instance of an object.
2023-10-26 21:45:28,402 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004003,-2147467261; Location: StartSync() in Calendar.cs:223:60
2023-10-26 21:45:28,403 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [65] -     at OutlookGoogleCalendarSync.Sync.Engine.Calendar.StartSync(Boolean manualIgnition, Boolean updateSyncSchedule) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 223
   at OutlookGoogleCalendarSync.Sync.Engine.Start(Boolean manualIgnition, Boolean updateSyncSchedule) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 213
   at OutlookGoogleCalendarSync.Sync.Engine.Sync_Requested(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 174
   at OutlookGoogleCalendarSync.Forms.Main.Sync_Click(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 686
```

**Comment by phw198** [comment]
What version of OGCS was the settings that you imported from? Before v2.9.3?

It looks like it was one that didn't have Profiles and then you tried to run a sync on v2.10.1 without configuring a profile properly...

**Comment by TheGooginator** [comment]
The version on my old computer was on the Alpha version 2.10.1 but I turned on my new computer this morning and it loaded and asked me to choose my Google Calendar. After doing that it just worked without throwing that error. You can go ahead and close this bug report as it looks to have resolved itself.

On a side note my membership expires tomorrow and I believe paypal will auto donate again for another year will this get refreshed automatically?

**Comment by phw198** [comment]
Glad you got it working again! 

Yes, subscription renewals should just update automatically and you'll see the new date on the About tab.

**Comment by phw198** [comment]
Just for completeness, it appears the error was due to the Console (the sync output window) not being initialised properly, as the error was happening on the: `if (Settings.Instance.MuteClickSounds) Console.MuteClicks(true);`

No idea how this happened, but don't think it was related to you copying your settings. Restarting OGCS was no doubt the fix...
