### ISSUE TITLE
Unable to reclaim orphan calendar entries in Google calendar [0x8004010F]

### ISSUE THREAD

**Issue by ajkessel** [phw198/OutlookGoogleCalendarSync#1726]
I'm getting "Unable to reclaim orphan calendar entries in Google calendar. Exception from HRESULT: 0x8004010F" every time I sync. How do I clear this error?

Full log shown below.
```
2023-10-30 07:28:57,069 WARN  1 OutlookGoogleCalendarSync.Sync.AbortableBackgroundWorker [26] -  Aborting background thread...
2023-10-30 07:28:57,121 WARN  1 OutlookGoogleCalendarSync.Sync.Engine [207] -  Sync thread forcefully aborted!
2023-10-30 07:30:38,463 ERROR  36 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Threading.ThreadAbortException: Thread was being aborted.
2023-10-30 07:30:38,489 ERROR  36 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80131530,-2146233040; Location: get_Categories() in <Unknown File>
2023-10-30 07:30:38,496 ERROR  36 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Categories()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.FilterCalendarEntries(Calendar profile, Boolean filterBySettings, Boolean noDateFilter, String extraFilter, Boolean suppressAdvisories) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 219
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.GetCalendarEntriesInRange(Calendar profile, Boolean suppressAdvisories) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 135
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 302
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.<>c__DisplayClass11_1.<StartSync>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 129
2023-10-30 07:30:38,505 FAIL  36 OutlookGoogleCalendarSync.Sync.AbortableBackgroundWorker [17] -  Thread was being aborted.
2023-10-30 13:32:00,910 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [139] -  Initialising error reporting to OFF
2023-10-30 13:32:00,989 INFO  1 OutlookGoogleCalendarSync.Program [253] -  Program started: v2.10.0.0
2023-10-30 13:32:00,994 INFO  1 OutlookGoogleCalendarSync.Program [254] -  Started automatically.
2023-10-30 13:32:00,996 INFO  1 OutlookGoogleCalendarSync.Program [257] -  Invoked with arguments: /d:300
2023-10-30 13:32:00,998 INFO  1 OutlookGoogleCalendarSync.Program [258] -  Logging to: C:\apps\OGCS\OGcalsync.log
2023-10-30 13:32:01,000 INFO  1 OutlookGoogleCalendarSync.Program [263] -  Purging log files older than 30 days...
2023-10-30 13:32:01,009 DEBUG  1 OutlookGoogleCalendarSync.Program [267] -  Deleted C:\apps\OGCS\OGcalsync.log.2023-09-29
2023-10-30 13:32:01,011 DEBUG  1 OutlookGoogleCalendarSync.Program [267] -  Deleted C:\apps\OGCS\OGcalsync.log.2023-09-30
2023-10-30 13:32:01,028 INFO  1 OutlookGoogleCalendarSync.Program [274] -  Purge complete.
2023-10-30 13:32:01,035 INFO  1 OutlookGoogleCalendarSync.Settings [49] -  Running OGCS from C:\apps\OGCS\OutlookGoogleCalendarSync.exe
2023-10-30 13:32:01,037 INFO  1 OutlookGoogleCalendarSync.Program [156] -  Storing user files in directory: C:\apps\OGCS
2023-10-30 13:32:01,038 DEBUG  1 OutlookGoogleCalendarSync.Telemetry [38] -  Settings not loaded; checking if the raw settings file has Gmail account set.
2023-10-30 13:32:01,066 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [290] -  Getting MD5 hash for 'aj*****l@gmail.com'
2023-10-30 13:32:01,070 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [59] -  Retrieved setting 'CloudLogging' with value 'true'
2023-10-30 13:32:01,072 INFO  1 OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting [135] -  Turned error reporting ON
2023-10-30 13:32:01,075 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [59] -  Retrieved setting 'Portable' with value 'true'
2023-10-30 13:32:01,079 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [59] -  Retrieved setting 'LoggingLevel' with value 'WARN'
2023-10-30 13:32:01,079 INFO  1 OutlookGoogleCalendarSync.Settings [410] -  Logging level configured to 'WARN'
2023-10-30 13:37:09,468 WARN  1 OutlookGoogleCalendarSync.Forms.Main [1277] -  Outlook calendar selection changed to: Calendar (ID: 0000000038EE96C57A17894DA499A5E2E866EE3D01007CE6F0AEF30556419E683905DB5F1416000000BD63840000)
2023-10-30 13:38:27,718 WARN  35 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [133] -  Could not find table of keys.
2023-10-30 13:38:27,723 WARN  35 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [49] -  Subscriber keyring is empty!
2023-10-30 13:38:32,381 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [28] -  System.InvalidCastException: Specified cast is not valid.
2023-10-30 13:38:32,863 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80004002,-2147467262; Location: GetLocation() in <Unknown File>
2023-10-30 13:38:44,215 WARN  34 OutlookGoogleCalendarSync.Recurrence [552] -  Failed to find master Google event for: 8/29/2023 1:00 PM (R) => [redacted]
2023-10-30 13:53:38,774 WARN  30 OutlookGoogleCalendarSync.Recurrence [552] -  Failed to find master Google event for: 8/29/2023 1:00 PM (R) => [redacted]
2023-10-30 14:08:35,062 WARN  15 OutlookGoogleCalendarSync.Recurrence [552] -  Failed to find master Google event for: 8/29/2023 1:00 PM (R) => [redacted]
2023-10-30 14:23:32,160 WARN  34 OutlookGoogleCalendarSync.OGCSexception [18] -  Calendar item does not have a proper date range - cannot sync it. ExchangeMode=olCachedConnectedFull
2023-10-30 14:23:32,164 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: The item has been moved or deleted.
2023-10-30 14:23:32,170 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x96A4010A,-1767636726; Location: get_EntryID() in <Unknown File>
2023-10-30 14:23:32,175 WARN  34 OutlookGoogleCalendarSync.OGCSexception [18] -  Failed to get appointment summary: 
2023-10-30 14:23:32,179 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: The item has been moved or deleted.
2023-10-30 14:23:32,180 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x9AC4010A,-1698430710; Location: get_AllDayEvent() in <Unknown File>
2023-10-30 14:23:32,181 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_AllDayEvent()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.GetEventSummary(AppointmentItem ai, Boolean onlyIfNotVerbose) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 1330
2023-10-30 14:23:39,137 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: The item has been moved or deleted.
2023-10-30 14:23:39,139 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0xA304010A,-1560018678; Location: get_Subject() in <Unknown File>
2023-10-30 14:23:39,140 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Subject()
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.skipCorruptedItem(List`1& outlookEntries, AppointmentItem cai, String errMsg) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 271
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 405
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.<>c__DisplayClass11_1.<StartSync>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 129
2023-10-30 14:23:39,143 ERROR  34 OutlookGoogleCalendarSync.Console [292] -  The item has been moved or deleted.
2023-10-30 14:24:26,702 WARN  34 OutlookGoogleCalendarSync.Recurrence [552] -  Failed to find master Google event for: 8/29/2023 1:00 PM (R) => [redacted]
2023-10-30 14:27:36,517 ERROR  34 OutlookGoogleCalendarSync.Console [292] -  Unable to reclaim orphan calendar entries in Google calendar.
2023-10-30 14:27:38,717 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x8004010F
2023-10-30 14:27:38,720 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x8004010F,-2147221233; Location: get_Start() in <Unknown File>
2023-10-30 14:27:38,720 ERROR  34 OutlookGoogleCalendarSync.OGCSexception [65] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Start()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.signature(AppointmentItem ai) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 1231
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.ReclaimOrphanCalendarEntries(List`1& gEvents, List`1& oAppointments, Boolean neverDelete) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\GoogleOgcs\GoogleCalendar.cs:line 1128
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.synchronize() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 471
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.<>c__DisplayClass11_1.<StartSync>b__0(Object o, DoWorkEventArgs args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 129
2023-10-30 14:27:38,721 ERROR  34 OutlookGoogleCalendarSync.Console [292] -  Exception from HRESULT: 0x8004010F
2023-10-30 14:28:23,367 ERROR  1 OutlookGoogleCalendarSync.Console [292] -  Sync aborted after 2 failed attempts!
```

**Comment by phw198** [comment]
0x800401F generally means you have a corrupted Outlook data file - have a [look at the wiki for possible resolutions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/FAQs#repairing-a-corrupted-outlook-data-file).

Please let me know if this resolve the issue, so I can catch this error in future releases and suggest the solution.

**Comment by phw198** [comment]
From what I can tell, you are also getting different errors at different points when accessing different calendar items. 
1. You start a sync, and it fails when checking items for corruption, (but not a `0x8004010F` error)
2. You then opt to try the sync again
3. This time there is no corruption detected on any items, so the sync proceeds further
4. But when it gets to the "reclaim orphans" phase, it then fails with a `0x8004010F` that the start date cannot be accessed - even though that was already tested in the corruption detection earlier.

So, definitely feels like your PST/OST file is giving inconsistent results...
