### ISSUE TITLE
COM object that has been separated from its underlying RCW cannot be used. 2.10.3.0

### ISSUE THREAD

**Issue by hillcountryfare** [phw198/OutlookGoogleCalendarSync#1777]
**OGCS Version**: v2.10.3.0 (previous value was wrong)
**Edition**: Installed
**Sync Direction**: mixed

**Bug Description**  
When on the settings screen-->outlook after adding profiles, got this crash.  Tried multiple times to reproduce but couldn't get it to repro.  Recorded video of repro steps.  Will upload all relevant files and leave it to you if you are able to fix or chase down issue.

**Steps to Reproduce the Issue**  
1. Settings
2. New profile.  Outlook --> Gmail
3. Choose non standard Outlook calendar (ICS)
4. Click through menus and dropdowns.  Something triggered this.  :(

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

**Comment by phw198** [comment]
Looks like it was switch of Profile and, after reconnecting to Outlook, then disconnecting with `Logoff()` that caused the error - which it was literally just using a split second before OK. So can only surmise something else must have been going on in parallel/background which disconnected the object from under its feet.

This type of issue is nigh on impossible to track down, so it might have to go on the "too tricky and time consuming to fix" given it's not easily reproducible - but thanks for taking the time to report it!

```
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Outlook.NameSpaceClass.Logoff()
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.Connect() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:line 107
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.Reset() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 75
   at OutlookGoogleCalendarSync.Forms.Main.rbOutlookDefaultMB_CheckedChanged(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1326
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at OutlookGoogleCalendarSync.Forms.Main.UpdateGUIsettings_Profile() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 594
   at OutlookGoogleCalendarSync.SettingsStore.Calendar.SetActive() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\SettingsStore\Calendar.cs:line 241
   at OutlookGoogleCalendarSync.Forms.Main.ddProfile_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1210
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
🔗 OGCS File Upload Nos 47
