### ISSUE TITLE
WARNING: Problem encountered during synchronisation. Sequence contains no elements

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#18]
Hi,  
I updated to 2.1.2.0 yesterday, I don't think the sync has worked, I get the
following error.  

    
    
    WARNING: Problem encountered during synchronisation.
    Sequence contains no elements

I'm on Office 16 on Windows 10. My .log file is attached, should you need
anything else, please let me know.  
  
I might downgrade to get the sync working again, but I'm happy to try any
potential fixes again for you.  
  
Thanks.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 178](http://outlookgooglecalendarsync.codeplex.com/workitem/178)
**Status:**	Resolved
**Reason Closed:**	Unassigned
**Assigned to:**	phw198
**Reported on:**	Feb 2, 2016 at 8:22 PM
**Reported by:**	TheJacksonian
**Updated on:**	Feb 10, 2016 at 7:42 PM
**Updated by:**	jmathis0517

#### Plaintext Attachments

[CodePlex Issue #178 Plain Text Attachments](https://gist.github.com/5819dfd6db5810605315f427cbe4054a)

#### Binary Attachments

[OutlookGoogleCalendarSync.exe](http://outlookgooglecalendarsync.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=outlookgooglecalendarsync&WorkItemId=178&FileAttachmentId=1546035)

**Comment by phw198** [comment]
On *2016-02-05 18:11:51 UTC*, **tsl** commented:

Same issue here with Outlook 2013 on Windows 7 32 bits.

Is the log already provided good enough for the troubleshooting?

I can provide another one if needed.

**Comment by phw198** [comment]
On *2016-02-05 20:49:06 UTC*, **smithbill** commented:

I'm getting the same issue. I'm on Win7 32bit Enterprise with MS Office 2010. Partial log file:


2016-02-05 13:41:17,237 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - WARNING: Problem encountered during synchronisation.
Sequence contains no elements
2016-02-05 13:41:17,252 ERROR 1 OutlookGoogleCalendarSync.MainForm [0] - at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
at OutlookGoogleCalendarSync.GoogleCalendar.userSubscriptionCheck()
at OutlookGoogleCalendarSync.GoogleCalendar.get_Instance()
at OutlookGoogleCalendarSync.Social.TrackSync()
at OutlookGoogleCalendarSync.MainForm.sync_Start(Boolean updateSyncSchedule)
at OutlookGoogleCalendarSync.MainForm.Sync_Requested(Object sender, EventArgs e)
at OutlookGoogleCalendarSync.MainForm.sync_Click(Object sender, EventArgs e)

**Comment by phw198** [comment]
On *2016-02-06 04:22:22 UTC*, **chickaplow** commented:

Same issue here. I'm running Outlook 2013 on Windows 7 Professional. The log file is attached; I've replaced my username in Outlook with "USER".

**Comment by phw198** [comment]
On *2016-02-06 19:45:37 UTC*, **phw198** commented:

Thanks everyone - hotfix v2.1.2.2 attached to the ticket which should squash this issue.

**Comment by phw198** [comment]
On *2016-02-08 22:20:15 UTC*, **tsl** commented:

I can confirm - the attached solved the issue :)

**Comment by phw198** [comment]
On *2016-02-08 22:20:53 UTC*, **tsl** commented:

Thank you, this seems have fixed it! :)

**Comment by phw198** [comment]
On *2016-02-09 01:21:04 UTC*, **chickaplow** commented:

This fix worked for me too. Thanks!

**Comment by phw198** [comment]
On *2016-02-09 12:03:04 UTC*, **jmathis0517** commented:

How do I get hotfix v2.1.2.2?

**Comment by phw198** [comment]
On *2016-02-09 18:25:17 UTC*, **chickaplow** commented:

In the File Attachments section at towards the top of this thread, it's the file named
"OutlookGoogleCalendarSync.exe".

**Comment by phw198** [comment]
On *2016-02-10 04:56:52 UTC*, **TheJacksonian** commented:

Just confirming the hotfix worked for me also, thanks.

**Comment by phw198** [comment]
On *2016-02-11 03:42:13 UTC*, **jmathis0517** commented:

Hot fix worked for me. Thanks
