### ISSUE TITLE
"Object reference not set to an instance of an object." after reconfiguration and reinstall

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#184]
<div><strong>This discussion was imported from <a href="http://outlookgooglecalendarsync.codeplex.com/discussions/660416" target="_blank">CodePlex</a></strong></div><hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/fleapower" target="_blank">fleapower</a></strong> wrote at 2016-12-30 17:24:</p><div class="markDownOutput ">I had OGCS working in a previous setup during testing. I then uninstalled it, reconfigured Outlook (deleted some folders and accounts), and then reinstalled it. Now when I try to run OGCS (both the full install and the portable versions), I get &quot;Object
 reference not set to an instance of an object&quot; and it won't start.<br>
</div></div>
<hr/>
<div>
<p><strong><a href="http://www.codeplex.com/site/users/view/Sarah9" target="_blank">Sarah9</a></strong> wrote at 2016-12-31 21:10:</p><div class="markDownOutput ">I had the same issue as I tried to install the download. I'm using Outlook 2016.<br>
</div></div>

**Comment by fabstar81** [comment]
i have the same error, however, only as i just updated to the beta 2.4.0. Before my update, i never had any issues. please solve this issue, as OGCS is now useless because it does not sync at all now due to this error. 

Below is a part of the log:
```
2017-05-23 08:53:20,877 WARN 10 OutlookGoogleCalendarSync.GoogleCalendar [0] - Found Google item missing Outlook IDs. 1-1-2000 (R) => ""
2017-05-23 08:53:21,083 INFO 10 OutlookGoogleCalendarSync.MainForm [0] - Failed to retrieve master for Google recurring event.
2017-05-23 08:53:21,301 INFO 10 OutlookGoogleCalendarSync.MainForm [0] - The following error was encountered during sync:-
2017-05-23 08:53:21,535 INFO 10 OutlookGoogleCalendarSync.MainForm [0] - Object reference not set to an instance of an object.
2017-05-23 08:53:21,535 ERROR 10 OutlookGoogleCalendarSync.OGCSexception [0] - System.NullReferenceException: Object reference not set to an instance of an object.
2017-05-23 08:53:21,535 ERROR 10 OutlookGoogleCalendarSync.OGCSexception [0] - Code: 0x80004003;-2147467261
2017-05-23 08:53:21,535 ERROR 10 OutlookGoogleCalendarSync.OGCSexception [0] -    at OutlookGoogleCalendarSync.MainForm.synchronize()
   at OutlookGoogleCalendarSync.MainForm.<>c__DisplayClass2.<sync_Start>b__0(Object o, DoWorkEventArgs args)
```

**Comment by phw198** [comment]
@fabstar81 you don't have this issue, you have Issue #82 which has a fix
