### ISSUE TITLE
Issue with the new way OGS gets outlook calendar

### ISSUE THREAD

**Issue by Morgan-6Freedom** [phw198/OutlookGoogleCalendarSync#1906]
> Checklist:-
> * [X] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [X] Reproduce the issue
> * [X] Complete the information below
> * [X] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))
```
**OGCS Version**: v3.0.0.3
**Edition**: Portable  
**Sync Direction**: O->G

**Bug Description**  

Sync version: 3.0.0.3

Profile: DEV-3D

Sync started at 10/07/2024 12:31:54

Syncing from 09/07/2024 to 09/09/2024

Outlook → Google

Finding Calendar Entries
Scanning Outlook calendar...

Authenticating with Microsoft
Handshake successful.

Unable to access the Outlook calendar.

One or more errors occurred.
Code: ErrorInvalidIdMalformed
Message: Id is malformed.
ClientRequestId: 5e18348e-d0c1-4427-99a7-080c8260029e


Sync aborted after 1 failed attempts!
```
**Steps to Reproduce the Issue**  
Try to pull my outlook calendar to sync it with google

**Any other information**  

[OGcalsync.log](https://github.com/user-attachments/files/16159496/OGcalsync.log)

**Comment by phw198** [comment]
It doesn't look like you followed the advice of starting with a new settings.xml file when trying out the development builds.

Essentially your settings still have an Outlook folder ID for the legacy client which is incompatible with Outlook online - you could try removing the `UseOutlookCalendar` sections from your settings file if you want, see if that works....?

**Comment by Morgan-6Freedom** [comment]
Nothing [here ](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1881#issue-2355908389) says to start with a new settings.xml.
It doesn't says how to do it.

I tried as you said : remove the `UseOutlookCalendar` section. But I have this error :
![image](https://github.com/user-attachments/assets/3e4abc01-342c-44b5-a1bc-2e19d6b2a1bf)

So I tried to choose the outlook calendar :

![image](https://github.com/user-attachments/assets/8eb2f585-53f1-446d-8f55-787974dee781)
![image](https://github.com/user-attachments/assets/41f40d8f-58ef-4f0e-ac56-d1f0712d0dac)




I also tried : move my settings.xml out of my "C:\Users\USER\AppData\Roaming\Outlook Google Calendar Sync" folder.
Now when launching OutlookGoogleCalendarSync.exe (from the unzipped version of the 3.0.0.1) I have this error :

![image](https://github.com/user-attachments/assets/6d6d5818-5cad-4f2a-a0c4-3b805b8c2eb2)
```
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  ExcludeAllDay: False; that are marked Free: False
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  ExcludeSubject: False
2024-07-18 12:28:46,173 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Choose Outlook Calendar: You need to select an Outlook Calendar first on the 'Settings' tab.
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Application window restored.
2024-07-18 12:28:46,173 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Response: OK
2024-07-18 12:28:46,173 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  ActiveProfile set to: None
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Minimising application to task tray.
2024-07-18 12:28:46,173 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Shutting down application.
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Application closed.
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Initialising error reporting to OFF
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Program started: v3.0.0.3
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Started interactively.
2024-07-18 12:28:46,173 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Logging to: C:\Users\<userid>\AppData\Roaming\Outlook Google Calendar Sync\OGcalsync.log
2024-07-18 12:28:46,174 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Purging log files older than 30 days...
2024-07-18 12:28:46,174 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Purge complete.
2024-07-18 12:28:46,174 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  No settings.xml file found in S:\Documents\Desktop\Portable_OGCS_v3.0.0.1
2024-07-18 12:28:46,174 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Saving settings.
2024-07-18 12:28:46,174 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  New blank template created.
2024-07-18 12:28:46,174 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Setting 'Portable' updated to 'True'
2024-07-18 12:28:46,174 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Running OGCS from S:\Documents\Desktop\Portable_OGCS_v3.0.0.1\OutlookGoogleCalendarSync.exe
2024-07-18 12:28:46,174 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Storing user files in directory: C:\Users\<userid>\AppData\Roaming\Outlook Google Calendar Sync
2024-07-18 12:28:46,174 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Settings not loaded; checking if the raw settings file has Gmail account set.
2024-07-18 12:28:46,174 WARN  1 OutlookGoogleCalendarSync.ErrorFlagAppender [137] -  No Gmail account found, building custom thumbprint instead.
2024-07-18 12:28:46,174 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Getting MD5 hash for 'NEO-TOKYO;AMD Ryzen 9 5950X 16-Core Processor            ;80A63227'
2024-07-18 12:28:46,174 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Retrieved setting 'CloudLogging' with value ''
2024-07-18 12:28:46,174 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Retrieved setting 'Portable' with value 'true'
2024-07-18 12:28:46,175 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  File storage location is incorrect according to S:\Documents\Desktop\Portable_OGCS_v3.0.0.1\settings.xml
2024-07-18 12:28:46,175 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Making the application portable...
2024-07-18 12:28:46,175 INFO  1 OutlookGoogleCalendarSync.ErrorFlagAppender [136] -  Moving files from C:\Users\fangh\AppData\Roaming\Outlook Google Calendar Sync to S:\Documents\Desktop\Portable_OGCS_v3.0.0.1:-
2024-07-18 12:28:46,175 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  settings.xml
2024-07-18 12:28:46,175 ERROR  1 OutlookGoogleCalendarSync.ErrorFlagAppender [138] -  System.IO.FileNotFoundException: Could not find file 'S:\Documents\Desktop\Portable_OGCS_v3.0.0.1\settings.xml'.
2024-07-18 12:28:46,175 ERROR  1 OutlookGoogleCalendarSync.ErrorFlagAppender [138] -  Failed retrieving 'CloudLogging' from S:\Documents\Desktop\Portable_OGCS_v3.0.0.1\settings.xml
2024-07-18 12:28:46,175 ERROR  1 OutlookGoogleCalendarSync.ErrorFlagAppender [138] -  System.IO.FileNotFoundException: Could not find file 'S:\Documents\Desktop\Portable_OGCS_v3.0.0.1\settings.xml'.
2024-07-18 12:28:46,175 ERROR  1 OutlookGoogleCalendarSync.ErrorFlagAppender [138] -  Code: 0x80070002,-2147024894; Location: WinIOError() in ImportElement() at offset 40 in XMLManager.cs:55:17
2024-07-18 12:28:46,175 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Asking user if they want to automatically report errors.
2024-07-18 12:28:46,175 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=f11195d93442365c561ee80817cc9dc3&ec=ogcs&ea=setting&el=CloudLogging%3DTrue
2024-07-18 12:28:46,175 DEBUG  1 OutlookGoogleCalendarSync.ErrorFlagAppender [135] -  GA4: {"client_id":"f11195d93442365c561ee80817cc9dc3","user_id":"f11195d93442365c561ee80817cc9dc3","non_personalized_ads":true,"user_properties":{"ogcs_version":{"value":"3.0.0.3"},"benefactor":{"value":"False"},"account_present":{"value":"False"},"profiles":{"value":"1"},"outlook_version":{"value":null},"outlook_name":{"value":null},"continent":{"value":null},"country":{"value":null},"country_code":{"value":null},"region":{"value":null},"city":{"value":null}},"events":[{"name":"setting","params":{"cloud_logging":"True"}}]}
2024-07-18 12:28:46,176 ERROR  1 OutlookGoogleCalendarSync.Exception [22] -  Code: 0x80070002,-2147024894; Location: WinIOError() in moveFiles() at offset 260 in Program.cs:463:13
2024-07-18 12:28:46,176 ERROR  1 OutlookGoogleCalendarSync.Exception [66] -     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at OutlookGoogleCalendarSync.Program.moveFiles(String srcDir, String dstDir) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 463
   at OutlookGoogleCalendarSync.Program.MakePortable(Boolean portable) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 441
   at OutlookGoogleCalendarSync.Program.parseArgumentsAndInitialise(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 166
   at OutlookGoogleCalendarSync.Program.Main(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 63
2024-07-18 12:28:46,176 FATAL  1 OutlookGoogleCalendarSync.Program [113] -  Application unexpectedly terminated!
2024-07-18 12:28:46,177 DEBUG  1 OutlookGoogleCalendarSync.Extensions.MessageBox [75] -  Application unexpectedly terminated!: Could not find file 'S:\Documents\Desktop\Portable_OGCS_v3.0.0.1\settings.xml'.
2024-07-18 12:28:47,737 DEBUG  1 OutlookGoogleCalendarSync.Extensions.MessageBox [90] -  Response: OK
2024-07-18 12:28:47,738 WARN  1 OutlookGoogleCalendarSync.Program [116] -  OGCS has crashed out.
2024-07-18 12:28:47,738 DEBUG  1 OutlookGoogleCalendarSync.Program [118] -  Shutting down application.
2024-07-18 12:28:47,757 INFO  1 OutlookGoogleCalendarSync.Program [127] -  Application closed.
```

I also tried launching with the parameters you state : 
![image](https://github.com/user-attachments/assets/255103f0-e4f9-4df8-8fff-36268c12320d)

I click "yes"
![image](https://github.com/user-attachments/assets/9f3906d2-1165-4d00-8fb4-b0c16903b7f2)

I click "ok"
![image](https://github.com/user-attachments/assets/a173f833-68f4-4d03-a835-381e666cfc31)


Then it crashes

**Comment by phw198** [comment]
> Nothing [here ](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1881#issue-2355908389) says to start with a new settings.xml.
It doesn't says how to do it.

I'm not sure I agree - the "Setup Recommendations" section's second bullet point says "Unzip the development build to a new directory and have it use a new settings and log file", and then provides the commands to achieve this.

Thanks for reporting though, and I think most of these issues (except the problems related to moving of `settings.xml` file) should be resolved in v3.0.0.4 - just released over on #1888, if you'd like to take a look.

**Comment by Morgan-6Freedom** [comment]
> have it use a new settings and log file
How to do that ?

Oh maybe with this command line ?
> call OutlookGoogleCalendarSync /t:"Development Build" /s:.\settings.xml /l:.\OGcalsync.log

It's

**Comment by phw198** [comment]
Your post looks to have got truncated, but yes, that's the command - given the zip is extracted to a new directory, the referenced settings and log file won't exist the first time the development build is run using that command.
