### ISSUE TITLE
Check fails for Google descriptions with max 8Kb content - Object reference not set

### ISSUE THREAD

**Issue by Sieppos** [phw198/OutlookGoogleCalendarSync#1959]
This started to happen after installing 2.11.0.0 (tried to revert to previous version, no help). Might concern updated instances? If I update an instance on my mobile, then try to sync on my desktop, the software gives the error: "Object reference not set to an instance of an object". Sync seems broken at the moment.

`C:\Users\Paul\Git\OutlookGoogleCalendarSync\...` is NOT my computer (the developers?) and might be the reason?

From the log: 
```
2024-09-03 08:31:40,407 ERROR 4  OutlookGoogleCalendarSync.Console [362] -  Appointment update failed.
2024-09-03 08:31:40,407 ERROR 4  OutlookGoogleCalendarSync.Exception [29] -  System.NullReferenceException: Object reference not set to an instance of an object.
2024-09-03 08:31:40,408 ERROR 4  OutlookGoogleCalendarSync.Exception [22] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in UpdateCalendarEntry() at offset 3290 in OutlookCalendar.cs:610:21
2024-09-03 08:31:40,408 ERROR 4  OutlookGoogleCalendarSync.Exception [66] -     at OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 610
   at OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 436
2024-09-03 08:31:40,409 DEBUG 4  OutlookGoogleCalendarSync.Extensions.MessageBox [75] -  Sync item failed: Outlook appointment update failed. Continue with synchronisation?
2024-09-03 08:31:40,433 INFO  1  OutlookGoogleCalendarSync.Forms.Main [1020] -  Application window restored.
2024-09-03 08:31:44,985 DEBUG 4  OutlookGoogleCalendarSync.Extensions.MessageBox [91] -  Response: Yes
```

**Comment by phw198** [comment]
:package: Thanks for reporting - this should now be resolved with [hotfix v2.11.0.4.zip](https://github.com/user-attachments/files/16899001/v2.11.0.4.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `F425BECE` Exe = `3FA16411`

Please let me know how it goes.

**Comment by Sieppos** [comment]
Copied the fix-content into "Running from", version shows 2.11.0.4 but still no help :(.. 
```
2024-09-06 18:47:45,625 INFO  12 OutlookGoogleCalendarSync.Console [366] -  27 calendar entries to be compared.
2024-09-06 18:47:45,626 INFO  12 OutlookGoogleCalendarSync.Console [366] -  Comparing 27 existing Outlook calendar entries
2024-09-06 18:47:45,896 DEBUG 12 OutlookGoogleCalendarSync.Outlook.Calendar [509] -  Processing >> 25/09/2024 22:00 => "3734e82766cb7982662ac66f29cb6a39"
2024-09-06 18:47:45,967 ERROR 12 OutlookGoogleCalendarSync.Console [362] -  25/09/2024 22:00 => "3734e82766cb7982662ac66f29cb6a39"
2024-09-06 18:47:46,058 ERROR 12 OutlookGoogleCalendarSync.Console [362] -  Appointment update failed.
2024-09-06 18:47:46,059 ERROR 12 OutlookGoogleCalendarSync.Exception [29] -  System.NullReferenceException: Object reference not set to an instance of an object.
2024-09-06 18:47:46,060 ERROR 12 OutlookGoogleCalendarSync.Exception [22] -  Code: 0x80004003,-2147467261; Location: UpdateCalendarEntry() in UpdateCalendarEntry() at offset 3297 in OutlookCalendar.cs:610:21
2024-09-06 18:47:46,060 ERROR 12 OutlookGoogleCalendarSync.Exception [66] -     at OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 610
   at OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Outlook\OutlookCalendar.cs:line 436
2024-09-06 18:47:46,061 DEBUG 12 OutlookGoogleCalendarSync.Extensions.MessageBox [75] -  Sync item failed: Outlook appointment update failed. Continue with synchronisation?
2024-09-06 18:47:46,095 INFO  1  OutlookGoogleCalendarSync.Forms.Main [1020] -  Application window restored.
2024-09-06 18:47:53,244 DEBUG 12 OutlookGoogleCalendarSync.Extensions.MessageBox [91] -  Response: Yes
```

**Comment by phw198** [comment]
That's annoying - can you confirm if the item at 25/09/2024 22:00 has description/body content in Google?

**Comment by Sieppos** [comment]
No, it has just three words in the title and a 15min reminder. Before reporting I deleted a huge amount of similar error giving instances hoping the error would go away. 

The previous version before 2.11.0 worked perfectly.

Edit: there are more error-instances but I limited the sync range to 20 days into the future and 7 past.

**Comment by phw198** [comment]
Got to be honest, troubleshooting on snippets of log file is very inefficient, but if the following assumptions are true for you:
* You have two-way sync enabled
* Obfuscation enabled for O->G
* "Description only to Google" is turned _off_

...then this [hotfix v2.11.0.7.zip](https://github.com/user-attachments/files/16922286/v2.11.0.7.zip) should work.

If not, please provide your log file, or at the very least the section that provides the settings you have configured.

Thanks!

**Comment by Sieppos** [comment]
hotfix v2.11.0.7 fixed it! Not getting errors anymore so far. Thanks for your help! 

Sorry I did not want to post whole log-file due to privacy (it will show the email address etc. I have donated though) :).. Will do if the errors come back.

**Comment by phw198** [comment]
Thanks for the donation! 😊
