### ISSUE TITLE
Web request to 'https://accounts.google.com/o/oauth2/token' failed

### ISSUE THREAD

**Issue by fivewaves** [phw198/OutlookGoogleCalendarSync#249]
After setting up OutlookGoogleCalendarSync, the message "Please ensure you can access the internet with Internet Explorer,  Test it now? If successful, please retry synchronising your calendar." gets displayed periodically.    Noticed that the erorr "Web request to 'https://accounts.google.com/o/oauth2/token' failed" appears in OGcalsync.log.   A relevant extract from this log file is pasted here: 
```
2017-06-23 11:22:08,527 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - --------------------------------------------------
2017-06-23 11:22:08,527 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - Reading Google Calendar Entries...
2017-06-23 11:22:08,527 DEBUG 14 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving all events from Google: 16-06-2017 -> 22-10-2017
2017-06-23 11:22:29,572 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - ERROR: Unable to connect to the Google calendar.
2017-06-23 11:22:32,706 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - The following error was encountered during sync:-
2017-06-23 11:22:32,706 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - Web request to 'https://accounts.google.com/o/oauth2/token' failed.
2017-06-23 11:22:32,706 ERROR 14 OutlookGoogleCalendarSync.OGCSexception [0] - DotNetOpenAuth.Messaging.ProtocolException: Web request to 'https://accounts.google.com/o/oauth2/token' failed.
2017-06-23 11:22:32,706 ERROR 14 OutlookGoogleCalendarSync.OGCSexception [0] - Code: 0x80131500;-2146233088
2017-06-23 11:22:32,722 ERROR 14 OutlookGoogleCalendarSync.OGCSexception [0] -    at OutlookGoogleCalendarSync.MainForm.synchronize()
   at OutlookGoogleCalendarSync.MainForm.<>c__DisplayClass2.<sync_Start>b__0(Object o, DoWorkEventArgs args)
2017-06-23 11:22:32,862 INFO 1 OutlookGoogleCalendarSync.MainForm [0] - User opted to retry sync straight away.
2017-06-23 11:22:32,862 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - Reading Outlook Calendar Entries...
2017-06-23 11:22:32,893 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - 9 Outlook calendar entries found.
2017-06-23 11:22:32,893 INFO 14 OutlookGoogleCalendarSync.MainForm [0] - --------------------------------------------------
```
Can anyone advise how to resolve this issue?   Thanks.

**Comment by phw198** [comment]
I can't tell from the log extract, but I'm guessing you are using a proxy to access the internet? I've seen some users have that address blocked for some reason, which scuppers the whole sync :disappointed: 

Are you able to try syncing without the proxy or use a different one? I assume the OAuth authenticate process when OK when initially setting up the Google account to sync with?

**Comment by fivewaves** [comment]
Yes, it is behind a proxy.  I am trying to sync my Outlook calendar to Google calendar when I am in the office network which is behind a proxy.  The OAuth authenticate process was OK.  If it is behind a proxy, is there any configuration that I should do to address it?

**Comment by mpking828** [comment]
I get this from time to time.  My work uses Zscaler.  Most of the time our traffic exits the company somewhere in New York.  Other times it exits the company in Denmark (We're international)  When we're out of Denmark, the whole sync fails with that error message.  Usually waiting a few hours for me resolves the issue.

Do you know what proxy your company is using?

**Comment by phw198** [comment]
Could you try v2.6.1 - the way OGCS authenticates to Google has been improved and may well have resolved this issue.

**Comment by fafurd** [comment]
I was having the same issue and also behind a proxy.  Just installed and is working for me now, but I have seen cases where it worked for a few days and stopped.  So far so good at the moment.
