### ISSUE TITLE
Error Selecting Calendar

### ISSUE THREAD

**Issue by orangelight** [phw198/OutlookGoogleCalendarSync#300]
I am trying to use this program to sync my outlook calendar with a google calendar but when I try to select an outlook calendar from the drop down an error appears
![image](https://user-images.githubusercontent.com/3813458/29482632-1c2309a0-8463-11e7-9a0d-6cec9edb3c4e.png)

The full error is:
`System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Outlook.MAPIFolder.get_EntryID()
   at OutlookGoogleCalendarSync.MyOutlookCalendarListEntry..ctor(MAPIFolder calendarFolder)
   at OutlookGoogleCalendarSync.OutlookCalendar.set_UseOutlookCalendar(MAPIFolder value)
   at OutlookGoogleCalendarSync.MainForm.cbOutlookCalendar_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`
Then when I try to sync it finds no events in the outlook calendar.

Thanks,
Alex

**Comment by phw198** [comment]
:spiral_notepad: Thanks for raising this. Please could you also provide your OGcalsync.log file [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)]

**Comment by orangelight** [comment]
[OGcalsync](https://gist.github.com/orangelight/5a0b711f11659b394ef6157cfddcf0e2)

**Comment by phw198** [comment]
Thanks. Looks like this only happened once and then recovered. I've altered things slightly to handle the error better, which will be included in the next release.

BTW, you appear to have [included no Outlook categories](https://gist.github.com/orangelight/5a0b711f11659b394ef6157cfddcf0e2#file-gistfile1-txt-L2231-L2232) in the sync, which then means [everything is excluded](https://gist.github.com/orangelight/5a0b711f11659b394ef6157cfddcf0e2#file-gistfile1-txt-L2292).
