### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by thelordsmurf** [phw198/OutlookGoogleCalendarSync#306]
Hi all,
I started getting this error just a day or two ago. One of the series of appointments was cancelled, so I'm not sure if it's related to that, but I manually deleted the cancelled entry from both Outlook and GCal so I'm not sure what's up. It looks like this was also Issue #82 but that's closed, and I am on 2.6.0.0 and in Issue #82 it said there was a hotfix at 2.4.0.2.
Any thoughts?
Thanks!
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1248781/OGcalsync.txt)

**Comment by phw198** [comment]
Hi,
I think you've got the logging level dialled up so high, the file you've uploaded hasn't actually captured the error :slightly_smiling_face:
As soon as the error happens, could you provide the logfile at that point?

**Comment by thelordsmurf** [comment]
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1258279/OGcalsync.log.txt)
Does this work?

**Comment by phw198** [comment]
Yes, thanks :+1: 

Two issues logged here - the first one is of more importance:
```
2017-08-28 15:20:16,832 INFO  6 OutlookGoogleCalendarSync.MainForm [0] -  5/22/2017 3:00 PM (R) => "Early Career Academic Working Group Monthly Call"
2017-08-28 15:20:17,036 INFO  6 OutlookGoogleCalendarSync.MainForm [0] -  WARNING: Appointment update failed.
Object reference not set to an instance of an object.
2017-08-28 15:20:17,037 ERROR  6 OutlookGoogleCalendarSync.OutlookCalendar [0] -     at OutlookGoogleCalendarSync.OutlookNew.GetRecipientEmail(Recipient recipient)
   at OutlookGoogleCalendarSync.OutlookCalendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
   at OutlookGoogleCalendarSync.OutlookCalendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
```
Looks like there's a recipient in Outlook for this appointment with an email address that's causing problems. Could you increase the logging level to `FINE`, perform another sync and then provide your log file again?

The second error appears to be a failure due to you upgrading to v2.6.1 in the middle of a sync, which closed the notification tray icon. Pretty obscure, but I've added handling so this doesn't error out in future.
```
2017-08-28 15:26:26,078 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'CompletedSyncs' updated to '2446'
2017-08-28 15:26:26,078 INFO  1 OutlookGoogleCalendarSync.MainForm [0] -  WARNING: Problem encountered during synchronisation.
Object reference not set to an instance of an object.
2017-08-28 15:26:26,079 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
2017-08-28 15:26:26,079 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2017-08-28 15:26:26,079 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.NotificationTray.UpdateItem(String itemName, String itemText, Boolean enabled)
   at OutlookGoogleCalendarSync.MainForm.sync_Start(Boolean updateSyncSchedule)
   at OutlookGoogleCalendarSync.MainForm.Sync_Requested(Object sender, EventArgs e)
   at OutlookGoogleCalendarSync.MainForm.Sync_Click(Object sender, EventArgs e)
```

**Comment by thelordsmurf** [comment]
[OGcalsync.log (2).txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1273290/OGcalsync.log.2.txt)

Okay, this should be the log in fine format, thanks for the help!

**Comment by phw198** [comment]
:flushed: Oops, well if nothing else that's highlighted a rather inefficient bit of code - your log is filled up with repeated steps and it doesn't include the error again. I assume it still errored?

:package: Try this [hotfix v2.6.1.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1273306/v2.6.1.4.zip) which should not fill the log quite so much. If it does still, there should be several log files of the form OGcalsync.log.nn - so I might need more than just the latest, but let's see...

**Comment by thelordsmurf** [comment]
Yes, the error is still there...
And the hotfix does not run, keeps crashing. sorry.

**Comment by phw198** [comment]
Oh, I thought you were familiar with [how to apply hotfixes](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix).

**Comment by thelordsmurf** [comment]
[OGcalsync.log.1.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1275283/OGcalsync.log.1.txt)
[OGcalsync.log.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1275282/OGcalsync.log.txt)
Got the hotfix up, error's still happening, and here are the logs that seem to be from the last run!

**Comment by phw198** [comment]
:package: Think I've got it - please give [hotfix v2.6.1.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1275580/v2.6.1.5.zip) a whirl...

**Comment by thelordsmurf** [comment]
So far so good!
Thank you so much!

**Comment by mmiltz91** [comment]
what about this issue? Any ideas?
![go contact error](https://user-images.githubusercontent.com/42324089/44005375-71c2e824-9e40-11e8-8d61-488f7bd1357d.PNG)

**Comment by phw198** [comment]
Nope...but I think you're posting to the wrong GitHub project?! Looks like a sourceforge project even. :confused:
