### ISSUE TITLE
an outlook event consistently failing to sync to google

### ISSUE THREAD

**Issue by shie-erlich** [phw198/OutlookGoogleCalendarSync#332]
one of my meetings (it's an instance of a series) is failing to be created every time. 
below are the relevant log lines (log level = all, replaced recipient name with "XXX")
```
2017-09-11 10:46:25,627 INFO  16 OutlookGoogleCalendarSync.MainForm [0] -  Creating 1 Google calendar entries...
2017-09-11 10:46:25,628 DEBUG  16 OutlookGoogleCalendarSync.GoogleCalendar [0] -  Processing >> 9/12/2017 1:30 PM (R) => "Shie|XXX"
2017-09-11 10:46:25,832 DEBUG  16 OutlookGoogleCalendarSync.MainForm [0] -  9/12/2017 1:30 PM (R) => "Shie|XXX"
2017-09-11 10:46:25,838 DEBUG  16 OutlookGoogleCalendarSync.Recurrence [0] -  Creating Google iCalendar definition for recurring event.
2017-09-11 10:46:25,855 DEBUG  16 OutlookGoogleCalendarSync.Recurrence [0] -  RRULE:FREQ=WEEKLY;INTERVAL=4;UNTIL=20180130T133000Z
2017-09-11 10:46:26,134 INFO  16 OutlookGoogleCalendarSync.MainForm [0] -  WARNING: Event creation failed.
Object reference not set to an instance of an object.
2017-09-11 10:46:26,134 ERROR  16 OutlookGoogleCalendarSync.GoogleCalendar [0] -     at OutlookGoogleCalendarSync.OutlookNew.GetRecipientEmail(Recipient recipient)
   at OutlookGoogleCalendarSync.GoogleCalendar.CreateAttendee(Recipient recipient)
   at OutlookGoogleCalendarSync.GoogleCalendar.createCalendarEntry(AppointmentItem ai)
   at OutlookGoogleCalendarSync.GoogleCalendar.CreateCalendarEntries(List`1 appointments)
```

**Comment by phw198** [comment]
I think this looks like issue #306 which has a hotfix.

**Comment by shie-erlich** [comment]
i attempted to apply the 2.6.1.5 hotfix but i can't run the app.
seems like windows smartscreen or something else is getting in the way. i'm seeing 'windows error reporting' icon and then it goes away.

does the latest alpha build on the site contain the fix?

**Comment by phw198** [comment]
No, but you need to upgrade to the latest alpha before applying the hotfix.

**Comment by shie-erlich** [comment]
did it, and happy to report the issue has gone away!
