### ISSUE TITLE
.NET Framework crash - Unhandled expection

### ISSUE THREAD

**Issue by markcs** [phw198/OutlookGoogleCalendarSync#365]
I quite often see this error when trying to sync.  

I'm running version 2.6.2

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring.ChangeKeys()
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.getGaccountEmail(String accessToken)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<getAuthenticated>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator..ctor()
   at OutlookGoogleCalendarSync.GoogleCalendar.get_Instance()
   at OutlookGoogleCalendarSync.Social.TrackSync()
   at OutlookGoogleCalendarSync.MainForm.sync_Start(Boolean updateSyncSchedule)
   at OutlookGoogleCalendarSync.MainForm.Sync_Requested(Object sender, EventArgs e)
   at OutlookGoogleCalendarSync.NotificationTray.notifyIcon_DoubleClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseDoubleClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring.ChangeKeys()
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.getGaccountEmail(String accessToken)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<getAuthenticated>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<>c__DisplayClass6_0.<<-ctor>b__0>d.MoveNext()<---

```

**Comment by phw198** [comment]
:spiral_notepad: Can you provide the OGcalsync.log section that precedes this crash? ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file))

**Comment by markcs** [comment]
@phw198 Paul, I sent you a link to the file in Dropbox
