### ISSUE TITLE
The synchronization failed check the sink tab for further details

### ISSUE THREAD

**Issue by mbodey** [phw198/OutlookGoogleCalendarSync#385]
:memo: Please use the below template to report your issue.  
:paperclip: To aid investigation of this issue, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).

---
**OGCS Version**: v2.6.0.0
**Installed or Portable**: Installed

**Problem Description**  
 sync failed: "the synchronization failed-check the sink tab for further details"

 unable to identify differences in Google calendar. The following error was encountered during sinc:-object reference not set to an instance of an object.

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/1451115/OGcalsync.log)

**Comment by phw198** [comment]
The error looks to be related to an issue with a Todoist Outlook entry with a bad date range:
```
2017-11-07 09:55:04,067 DEBUG  7 OutlookGoogleCalendarSync.GoogleCalendar [0] -  Retrieving specific Event with ID todoist1806024i105485513u337a1965f309401da4b5884a96d45327
2017-11-07 09:55:04,330 WARN  7 OutlookGoogleCalendarSync.MainForm [0] -  Calendar item does not have a proper date range - cannot sync it.
2017-11-07 09:55:04,330 DEBUG  7 OutlookGoogleCalendarSync.MainForm [0] -  The end date you entered occurs before the start date.
2017-11-07 09:55:04,331 WARN  7 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Failed to get appointment summary: 
2017-11-07 09:55:04,331 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The end date you entered occurs before the start date.
2017-11-07 09:55:04,331 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x98B04005;-1733279739
2017-11-07 09:55:04,331 ERROR  7 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_Start()
   at OutlookGoogleCalendarSync.OutlookCalendar.GetEventSummary(AppointmentItem ai)
```
If you are able to remove this entry, that'll probably work around the issue.
Otherwise, please upgrade to the latest alpha release of OGCS (v2.6.3) and confirm if the problem remains.

Thanks
