### ISSUE TITLE
"Sync item failed" requires action to continue Sync :(

### ISSUE THREAD

**Issue by RDiane** [phw198/OutlookGoogleCalendarSync#402]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
At every Sync I get at least 2-3 popups titled "Sync item failed" -- stating: "Updated Outlook appointment failed to save.  Continue with synchronisation?"  I then have to select YES to continue.  I cannot figure out which calendar entry is causing the problem, and I don't know how I would correct the issue if I could (other than potentially simply deleting it).  Having these constant halts to the sync requiring action on my part is very frustrating and destroys the overall efficiency of automatic syncing.

**Steps to Reproduce the Issue**  
1. Run the program 

**Any other information**  
I am unable to include a sync log -- I hope you can help with this issue without it.

**Comment by RDiane** [comment]
I am running the latest version, including Alpha.

**Comment by RDiane** [comment]
Here is an excerpt of the log, which includes its last lines -- it seems to be where all of the errors occur:
```
2017-11-28 17:24:29,701 DEBUG  15 OutlookGoogleCalendarSync.MainForm [0] -  3 attributes updated.
2017-11-28 17:24:29,702 DEBUG  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Saving timestamp when OGCS updated appointment.
2017-11-28 17:24:30,006 DEBUG  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Processing recurring master appointment.
2017-11-28 17:24:30,006 DEBUG  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Processing >> 12/21/2017 (R) => "MVP PTO - Full day"
2017-11-28 17:24:30,032 DEBUG  15 OutlookGoogleCalendarSync.Recurrence [0] -  Converting RRULE:FREQ=WEEKLY;UNTIL=20171222T000000Z;BYDAY=MO,TU,WE,TH,FR
2017-11-28 17:24:30,820 DEBUG  15 OutlookGoogleCalendarSync.MainForm [0] -  12/21/2017 (R) => "MVP PTO - Full day"
Recurrence Interval: 0 => 1
2017-11-28 17:24:30,820 DEBUG  15 OutlookGoogleCalendarSync.MainForm [0] -  1 attributes updated.
2017-11-28 17:24:30,820 DEBUG  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Saving timestamp when OGCS updated appointment.
2017-11-28 17:24:31,049 INFO  15 OutlookGoogleCalendarSync.MainForm [0] -  WARNING: Updated appointment failed to save.
Unknown Error.
2017-11-28 17:24:31,050 ERROR  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.Save()
   at OutlookGoogleCalendarSync.OutlookCalendar.updateCalendarEntry_save(AppointmentItem ai)
   at OutlookGoogleCalendarSync.OutlookCalendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
2017-11-28 17:24:33,950 DEBUG  1 OutlookGoogleCalendarSync.SyncTimer [0] -  Scheduled sync triggered.
2017-11-28 17:24:33,989 DEBUG  1 OutlookGoogleCalendarSync.SyncTimer [0] -  Busy syncing already. Rescheduled for 5 mins time.
2017-11-28 17:24:33,990 INFO  1 OutlookGoogleCalendarSync.SyncTimer [0] -  Next sync scheduled for Tuesday, November 28, 2017 - 5:29:33 PM
2017-11-28 17:25:07,478 DEBUG  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Processing recurring master appointment.
2017-11-28 17:25:07,478 DEBUG  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Processing >> 12/26/2017 (R) => "MVP PTO - Full day"
2017-11-28 17:25:07,508 DEBUG  15 OutlookGoogleCalendarSync.Recurrence [0] -  Converting RRULE:FREQ=WEEKLY;UNTIL=20171229T000000Z;BYDAY=MO,TU,WE,TH,FR
2017-11-28 17:25:08,246 DEBUG  15 OutlookGoogleCalendarSync.MainForm [0] -  12/26/2017 (R) => "MVP PTO - Full day"
Recurrence Interval: 0 => 1
2017-11-28 17:25:08,246 DEBUG  15 OutlookGoogleCalendarSync.MainForm [0] -  1 attributes updated.
2017-11-28 17:25:08,246 DEBUG  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Saving timestamp when OGCS updated appointment.
2017-11-28 17:25:08,399 INFO  15 OutlookGoogleCalendarSync.MainForm [0] -  WARNING: Updated appointment failed to save.
Unknown Error.
2017-11-28 17:25:08,399 ERROR  15 OutlookGoogleCalendarSync.OutlookCalendar [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.Save()
   at OutlookGoogleCalendarSync.OutlookCalendar.updateCalendarEntry_save(AppointmentItem ai)
   at OutlookGoogleCalendarSync.OutlookCalendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
2017-11-28 17:25:10,105 INFO  15 OutlookGoogleCalendarSync.MainForm [0] -  12 entries updated.
2017-11-28 17:25:10,310 INFO  15 OutlookGoogleCalendarSync.MainForm [0] -  --------------------------------------------------
2017-11-28 17:25:11,122 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'CompletedSyncs' updated to '8'
2017-11-28 17:25:11,132 INFO  1 OutlookGoogleCalendarSync.MainForm [0] -  Sync finished with success!
2017-11-28 17:25:11,133 INFO  1 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Registering for Outlook appointment change events...
2017-11-28 17:25:11,133 DEBUG  1 OutlookGoogleCalendarSync.OutlookCalendar [0] -  Create the timer for the push synchronisation
2017-11-28 17:25:11,192 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'LastSyncDate' updated to '11/28/2017 5:23:33 PM'
2017-11-28 17:26:06,057 INFO  1 OutlookGoogleCalendarSync.SyncTimer [0] -  Next sync scheduled for Tuesday, November 28, 2017 - 5:27:06 PM
2017-11-28 17:26:16,483 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Application closed.
```

**Comment by phw198** [comment]
Looks the same as issue #398

**Comment by RDiane** [comment]
Thank you so much for the reference to issue #398!  It led me to experiment with the re-occurrence aspect and I was actually able to fix it -- a re-occurrence was created in outlook that re-occurred based on "week days" only - and also spanned through a weekend.  Once this was re-entered as a spanning event from start day to end day rather than a re-occurrence, the glitch was fixed.  Other day to day re-occurrences don't cause the problem, so I think the problem must arise when "week days" are used to designate the re-occurrence, or when the re-occurrence spans a weekend.  THANKS MUCH

**Comment by RDiane** [comment]
Now I am pretty sure it is the "week days" only designation that causes the problem.  Just fixed another shared event where a colleague used this designation for 2 weekdays in a row and it caused the glitch for me.  I changed the recurrence to "every 1 day" instead and it fixed the problem.

**Comment by phw198** [comment]
Yep, that was my suspicion too - hopefully will get to take a look into this over the weekend... 

Thanks!

**Comment by phw198** [comment]
Yep, that was my suspicion too - hopefully will get to take a look into this over the weekend... 

Thanks!

**Comment by phw198** [comment]
I've posted a hotfix on the other issue, if you could see if that works around the problem.

What version of Outlook are you running? I couldn't actually replicate the problem on Outlook 2016.

**Comment by RDiane** [comment]
using Outlook 2016 / Office 365

**Comment by RDiane** [comment]
thanks ;)  I'll try it.
