### ISSUE TITLE
Recurring meeting sync fails

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#43]
It looks like I have a recurring calendar entry on my Google calendar that
causes the sync to error out. Below is the relevant debug log details. Sync is
configured to just push Google calendar events and description one way to
Outlook (no attendees). Full log file can be found here on google drive -&gt;
[ https://goo.gl/UejLS4 ](https://goo.gl/UejLS4)  
  
Is there a way to prevent the UI/Sync from stopping and asking if it should
continue? Ie each time it hits this error, I must respond to the prompt; is
the a silent-fail or continue on error option I've missed?  

    
    
    2016-06-13 12:44:07,627 DEBUG 10 OutlookGoogleCalendarSync.OutlookCalendar [0] - Processing >> 6/3/2016 3:30 PM (R) => "Google / Accenture Launchpad All Hands"
    2016-06-13 12:44:07,641 DEBUG 10 OutlookGoogleCalendarSync.Recurrence [0] - Converting RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20160826T193000Z;INTERVAL=2;BYDAY=FR
    2016-06-13 12:44:07,840 INFO 10 OutlookGoogleCalendarSync.MainForm [0] - WARNING: Appointment update failed.
    The object does not support this method.
    2016-06-13 12:44:07,842 ERROR 10 OutlookGoogleCalendarSync.OutlookCalendar [0] -    at Microsoft.Office.Interop.Outlook._AppointmentItem.set_End(DateTime End)
       at OutlookGoogleCalendarSync.OutlookNew.WindowsTimeZone_set(AppointmentItem ai, Event ev)
       at OutlookGoogleCalendarSync.Recurrence.BuildOutlookPattern(Event ev, AppointmentItem ai, RecurrencePattern& oPattern)
       at OutlookGoogleCalendarSync.Recurrence.CompareOutlookPattern(Event ev, AppointmentItem ai, StringBuilder sb, Int32& itemModified)
       at OutlookGoogleCalendarSync.OutlookCalendar.UpdateCalendarEntry(AppointmentItem ai, Event ev, Int32& itemModified, Boolean forceCompare)
       at OutlookGoogleCalendarSync.OutlookCalendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
    2016-06-13 12:44:11,495 DEBUG 10 OutlookGoogleCalendarSync.OutlookCalendar [0] - Processing recurring master appointment.

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 287](http://outlookgooglecalendarsync.codeplex.com/workitem/287)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Jun 13, 2016 at 5:05 PM
**Reported by:**	dhoff4
**Updated on:**	Jan 15 at 10:55 PM
**Updated by:**	phw198

**Comment by phw198** [comment]
On *2016-07-05 22:00:17 UTC*, **mvader** commented:

I would like to second error supression feature. I have a persistent error that isn't a big deal because it is an event a few months in the past that won't sync for some reason. I have to click yes to continue sync EVERY time...
everything continues smoothly after that.

If I could just suppress the error, that would be great.

**Comment by phw198** [comment]
On *2016-08-22 22:26:37 UTC*, **jaredbaszler** commented:

I'm having this same issue. A recurring event in Google causes errors when syncing. I'm only pushing Google events to Outlook, one-way.

**Comment by phw198** [comment]
On *2016-12-04 05:43:17 UTC*, **phw198** commented:

Sorry for the delay in response. Could you confirm if this problem is resolved in the latest Beta release (or latest Alpha) - there was quite a lot of work done around the issue you have reported...


As yet, there is no option to silently continue past error messages - something in the pipeline.


Thanks!

**Comment by phw198** [comment]
On *2017-01-16 06:55:21 UTC*, **phw198** commented:

Will keep this ticket open, re the feature request of silently continue.

**Comment by phw198** [comment]
Tracking feature request under #47.
