### ISSUE TITLE
Event creation failed, string cannot be of zero length

### ISSUE THREAD

**Issue by kloknibor** [phw198/OutlookGoogleCalendarSync#475]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.1.0
**Installed or Portable**: Installed

**Problem Description**  
OGCS reports the syncing failed every 5 minutes...

**Steps to Reproduce the Issue**  
1. sync my calendar

**Any other information**  
error during sync : 

Event creation failed.
String cannot be of zero length. Parameter name: oldValue

```
2018-02-21 10:28:05,115 WARN  16 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Exchange does not have an email for recipient: Controls Box
2018-02-21 10:28:05,126 DEBUG  16 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Retrieved from PropertyAccessor instead.
2018-02-21 10:28:05,168 ERROR  16 OutlookGoogleCalendarSync.Console [0] -  Event creation failed.
2018-02-21 10:28:05,169 ERROR  16 OutlookGoogleCalendarSync.Console [0] -  String cannot be of zero length.
2018-02-21 10:28:05,169 ERROR  16 OutlookGoogleCalendarSync.Console [0] -  Parameter name: oldValue
2018-02-21 10:28:05,187 FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console navigating.
2018-02-21 10:28:05,193 FINE  1 OutlookGoogleCalendarSync.Console [0] -  Navigated status = Loading
2018-02-21 10:28:05,204 FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console finished navigating
2018-02-21 10:28:05,216 FINE  1 OutlookGoogleCalendarSync.Console [0] -  Document completed.
2018-02-21 10:28:05,440 ERROR  16 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -     at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at OutlookGoogleCalendarSync.ILogExtentions.Fine(ILog log, String message, String containsEmail)
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.GetRecipientEmail(Recipient recipient)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateAttendee(Recipient recipient)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.createCalendarEntry(AppointmentItem ai)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.CreateCalendarEntries(List`1 appointments)
```

**Comment by phw198** [comment]
Thanks for reporting this.

:package: This should now be resolved with [v2.7.1.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1756081/v2.7.1.1.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by phw198** [comment]
Any feedback on this fix?

**Comment by phw198** [comment]
@kloknibor Have you been able to test v2.7.1.1 at all?
