### ISSUE TITLE
Cannot sync

### ISSUE THREAD

**Issue by lacibaci** [phw198/OutlookGoogleCalendarSync#485]
:memo: Use the below template to report your issue.  
:bulb: Have you upgraded to the latest alpha to check if the problem is already fixed?  
:paperclip: To aid investigation, please provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.1.0  
**Installed or Portable**: Portable

**Problem Description**  
No sync. "Failed to retrieve master for Google recurring event outside of sync range." The Google calendar is empty.

**Steps to Reproduce the Issue**  
Fresh install.

**Any other information**  
Windows 10, Outlook 2016

```
2018-03-08 08:14:20,285 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Manual sync requested.
2018-03-08 08:14:20,316 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync version: 2.7.1.0
2018-03-08 08:14:20,332 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync started at 3/8/2018 8:14:20 AM
2018-03-08 08:14:20,347 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Syncing from 3/7/2018 to 5/8/2018
2018-03-08 08:14:20,363 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Outlook → Google
2018-03-08 08:14:20,394 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Deregistering from Outlook appointment change events...
2018-03-08 08:14:20,410 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Removing 1 Outlook event handler hooks.
2018-03-08 08:14:20,425 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Schedule disabled.
2018-03-08 08:14:20,441 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Authenticating with Google...
2018-03-08 08:14:20,472 DEBUG  15 OutlookGoogleCalendarSync.Console [0] -  Preparing to authenticate with Google.
2018-03-08 08:14:20,801 DEBUG  15 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Getting keyring.
2018-03-08 08:14:20,863 ERROR  15 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Failed to retrieve data: The request was aborted: Could not create SSL/TLS secure channel.
2018-03-08 08:14:20,863 DEBUG  15 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  There are 0 keys.
2018-03-08 08:14:20,863 DEBUG  15 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  0 keys are active.
2018-03-08 08:14:20,879 DEBUG  15 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Picking a Standard key.
2018-03-08 08:14:20,879 WARN  15 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Standard keyring is empty!
2018-03-08 08:14:20,894 DEBUG  15 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Reverting to default key.
2018-03-08 08:14:20,894 DEBUG  15 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'AssignedClientIdentifier' updated to ''
2018-03-08 08:14:20,910 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Authenticating with Google calendar service...
2018-03-08 08:14:20,925 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Google credential file location: C:\utils\OGCS\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user
2018-03-08 08:14:21,066 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  User has provided authorisation and credential file saved.
2018-03-08 08:14:21,082 INFO  5 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Refresh and Access token successfully retrieved.
2018-03-08 08:14:21,082 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token expires 3/8/2018 9:11:52 AM
2018-03-08 08:14:21,097 DEBUG  5 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Retrieving email address associated with Google account.
2018-03-08 08:14:21,473 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Retrieving all subscribers from past year.
2018-03-08 08:14:21,738 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Page 1 received.
2018-03-08 08:14:21,754 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Searching for subscription for: ls****y@gmail.com
2018-03-08 08:14:21,769 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Retrieving all donors.
2018-03-08 08:14:22,051 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Page 1 received.
2018-03-08 08:14:22,051 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Searching for donation from: ls****y@gmail.com
2018-03-08 08:14:22,066 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'Donor' updated to 'False'
2018-03-08 08:14:22,097 INFO  9 OutlookGoogleCalendarSync.Console [0] -  Finding Calendar Entries
2018-03-08 08:14:22,691 INFO  9 OutlookGoogleCalendarSync.Console [0] -  Scanning Outlook calendar...
2018-03-08 08:14:22,832 INFO  9 OutlookGoogleCalendarSync.Console [0] -  11 Outlook calendar entries found.
2018-03-08 08:14:23,270 INFO  9 OutlookGoogleCalendarSync.Console [0] -  Scanning Google calendar...
2018-03-08 08:14:23,832 DEBUG  9 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving all events from Google: 3/7/2018 -> 5/8/2018
2018-03-08 08:14:23,973 DEBUG  9 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Page 1 received.
2018-03-08 08:14:23,988 INFO  9 OutlookGoogleCalendarSync.Console [0] -  0 Google calendar entries found.
2018-03-08 08:14:24,504 INFO  9 OutlookGoogleCalendarSync.Console [0] -  Total inc. recurring items spanning sync date range...
2018-03-08 08:14:25,160 ERROR  9 OutlookGoogleCalendarSync.Console [0] -  Failed to retrieve master for Google recurring event outside of sync range.
2018-03-08 08:14:25,770 DEBUG  9 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2018-03-08 08:14:25,770 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The operation failed.
2018-03-08 08:14:25,785 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x8E6300FD;-1906114307
2018-03-08 08:14:25,785 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass16_0.<Start>b__0(Object o, DoWorkEventArgs args)
2018-03-08 08:14:25,801 ERROR  9 OutlookGoogleCalendarSync.Console [0] -  The operation failed.
2018-03-08 08:14:30,445 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Operation aborted after 1 failed attempts!
2018-03-08 08:14:30,476 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'LastSyncDate' updated to '3/8/2018 8:14:20 AM'
2018-03-08 08:14:30,523 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Value cannot be null.
Parameter name: value
2018-03-08 08:14:30,538 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Registering for Outlook appointment change events...
2018-03-08 08:14:30,538 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Create the timer for the push synchronisation
```

**Comment by lacibaci** [comment]
The exception is thrown at this line:
UserProperty prop = **ai.UserProperties**.Find(MetadataIdKeyName(key));
in OutlookCalendar.cs: GetOGCSproperty(...)

I'm not sure why **ai.UserProperties** is failing (throwing exception)

I wrapped it in try-catch block and it seems to work now.
>            try
>            {
>                UserProperty prop = ai.UserProperties.Find(MetadataIdKeyName(key));
>                if (prop == null)
>                {
>                    value = null;
>                    return false;
>                }
>                else
>                {
>                    value = prop.Value.ToString();
>                    return true;
>                }
>            }
>            catch
>            {
>                value = null;
>                return false;
>            }

**Comment by phw198** [comment]
Hi @lacibaci 

This [looks pertinent](https://www.add-in-express.com/forum/read.php?FID=5&TID=13265) - perhaps the Outlook item had moved during the sync? Did the problem persist even after a restart of Outlook and OGCS (without your try-catch workaround)?

:package: I've put in a different workaround in with [hotfix v2.7.1.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1799377/v2.7.1.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by lacibaci** [comment]
I could not make this work even after I removed all entries from my Google calendar and restarting/reinstalling the app. It is possible that one or more events in the Outlook calendar are weird (people who do the schedule rarely know what they're doing...) but I could not remove anything from Outlook's side to diagnose it more.
I will try your fix time permitting and let you know.

**Comment by phw198** [comment]
Had any time to test this further?

**Comment by phw198** [comment]
@lacibaci Have you been able to test the hotfix?

**Comment by lacibaci** [comment]
Unfortunately, no. I am using a different solution now.

**Comment by phw198** [comment]
OK, no worries.
