### ISSUE TITLE
Failing to check for update: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#490]
```
2018-03-15 21:15:56,420 ERROR OutlookGoogleCalendarSync.Updater [210]: Failed checking for update.
'OutlookGoogleCalendarSync.vshost.exe' (CLR v4.0.30319: OutlookGoogleCalendarSync.vshost.exe): Loaded 'C:\Windows\assembly\GAC\Microsoft.mshtml\7.0.3300.0__b03f5f7f11d50a3a\Microsoft.mshtml.dll'. Module was built without symbols.
2018-03-15 21:15:58,077 ERROR OutlookGoogleCalendarSync.OGCSexception [16]: System.Net.Http.HttpRequestException: An error occurred while sending the request.
2018-03-15 21:15:58,078 ERROR OutlookGoogleCalendarSync.OGCSexception [18]: Code: 0x80131500;-2146233088
2018-03-15 21:15:58,079 ERROR OutlookGoogleCalendarSync.OGCSexception [21]: InnerException:-
2018-03-15 21:15:58,079 ERROR OutlookGoogleCalendarSync.OGCSexception [16]: System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
2018-03-15 21:15:58,080 ERROR OutlookGoogleCalendarSync.OGCSexception [18]: Code: 0x80131509;-2146233079
2018-03-15 21:15:58,080 ERROR OutlookGoogleCalendarSync.OGCSexception [24]:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OutlookGoogleCalendarSync.Updater.<githubCheck>d__12.MoveNext() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Updater.cs:line 108
Exception thrown: 'System.Net.Http.HttpRequestException' in OutlookGoogleCalendarSync.exe
```
https://github.com/Squirrel/Squirrel.Windows/issues/237#issuecomment-75012198
https://weblog.west-wind.com/posts/2011/Feb/11/HttpWebRequest-and-Ignoring-SSL-Certificate-Errors

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.7.1.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1817456/v2.7.1.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
