### ISSUE TITLE
Crash on automated startup - file not found when initialising error reporting

### ISSUE THREAD

**Issue by LHuisingh** [phw198/OutlookGoogleCalendarSync#559]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.5.0
**Installed or Portable**: Portable

**Problem Description**  
I have OGCS set to start on login with a delay of 240 seconds.  The error I receive happens when it starts up.  The error happens before it can open the log file.  It might actually be an error opening the log file.

**Steps to Reproduce the Issue**  
1. Happens only on automatic launch on login.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2241649/OGcalsync.log)

**Any other information**  
Data from event viewer: 
```
Log Name:      Application
Source:        .NET Runtime
Date:          7/30/2018 7:03:58 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WF37131.rl.gov
Description:
Application: OutlookGoogleCalendarSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   at System.IO.StreamReader..ctor(System.String)
   at OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting.Initialise()
   at OutlookGoogleCalendarSync.Program.Main(System.String[])
```

Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-30T14:03:58.208991000Z" />
    <EventRecordID>45084</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WF37131.rl.gov</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: OutlookGoogleCalendarSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions, System.String, Boolean, Boolean, Boolean)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32, Boolean)
   at System.IO.StreamReader..ctor(System.String)
   at OutlookGoogleCalendarSync.GoogleOgcs.ErrorReporting.Initialise()
   at OutlookGoogleCalendarSync.Program.Main(System.String[])

</Data>
  </EventData>
</Event>
```
```
Log Name:      Application
Source:        Application Error
Date:          7/30/2018 7:03:58 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WF37131.rl.gov
Description:
Faulting application name: OutlookGoogleCalendarSync.exe, version: 2.7.5.0, time stamp: 0x5b4bb7b8
Faulting module name: KERNELBASE.dll, version: 10.0.16299.547, time stamp: 0xb03e83b5
Exception code: 0xe0434352
Fault offset: 0x00103ff2
Faulting process id: 0x3254
Faulting application start time: 0x01d4280e2182095b
Faulting application path: C:\OGCalSync\2.7.5\OutlookGoogleCalendarSync.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: f8bfad08-ac48-4c4d-a45a-b6b8a197c70f
Faulting package full name: 
Faulting package-relative application ID: 
```
Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-07-30T14:03:58.728928300Z" />
    <EventRecordID>45086</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WF37131.rl.gov</Computer>
    <Security />
  </System>
  <EventData>
    <Data>OutlookGoogleCalendarSync.exe</Data>
    <Data>2.7.5.0</Data>
    <Data>5b4bb7b8</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.16299.547</Data>
    <Data>b03e83b5</Data>
    <Data>e0434352</Data>
    <Data>00103ff2</Data>
    <Data>3254</Data>
    <Data>01d4280e2182095b</Data>
    <Data>C:\OGCalSync\2.7.5\OutlookGoogleCalendarSync.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>f8bfad08-ac48-4c4d-a45a-b6b8a197c70f</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by phw198** [comment]
:package: This should now be resolved with [v2.7.5.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2259460/v2.7.5.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) - this must be applied after upgrading to v2.7.5).

Please let me know how it goes.

**Comment by tuniel-xda** [comment]
i had this problem too - the hotfix prevents the crash on startup - i set the delay to 300s, seems to work ;)

**Comment by LHuisingh** [comment]
The fix worked for me.  Thank you.
