### ISSUE TITLE
Crash on startup after trying to close "Google+ API wasn't enabled." error dialog.

### ISSUE THREAD

**Issue by stephengeorgewest-navitaire** [phw198/OutlookGoogleCalendarSync#576]
**OGCS Version**: 2.7.6601.23081 
**Installed or Portable**: Installed
OutlookGoogleCalendarSync
    Assembly Version: 2.7.6601.23081
    Win32 Version: 2.7.0.0
    CodeBase: file:///C:/Users/swest/AppData/Local/OutlookGoogleCalendarSync/app-2.7.0-beta/OutlookGoogleCalendarSync.exe

**Problem Description**  
Crash on closing the error dialog that said that the Google+ API wasn't enabled.

**Steps to Reproduce the Issue**  
1. don't have Google+ api enabled  for the project.
2. start OGCS

**Any other information**  
```
************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.ApplicationException: If you are using your own API keys, you must also enable the Google+ API.
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.getGaccountEmail(String accessToken)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<getAuthenticated>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<>c__DisplayClass13_0.<<GetAuthenticated>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.GetAuthenticated()
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.get_Instance()
   at OutlookGoogleCalendarSync.Social.TrackSync()
   at OutlookGoogleCalendarSync.MainForm.sync_Start(Boolean updateSyncSchedule)
   at OutlookGoogleCalendarSync.MainForm.Sync_Requested(Object sender, EventArgs e)
   at OutlookGoogleCalendarSync.NotificationTray.notifyIcon_DoubleClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseDoubleClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.ApplicationException: If you are using your own API keys, you must also enable the Google+ API.
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.getGaccountEmail(String accessToken)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<getAuthenticated>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OutlookGoogleCalendarSync.GoogleOgcs.Authenticator.<>c__DisplayClass13_0.<<GetAuthenticated>b__0>d.MoveNext()<---
```

----
tried the alpha and it still crashed, but gave a nicer error, saying go to this url to enable. That's a nice response from the googles.
```
2018-08-23 16:21:18,573 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleWhenMinimising: True
2018-08-23 16:21:18,573 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Portable: False
2018-08-23 16:21:18,573 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    CreateCSVFiles: False
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    VerboseOutput: False
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MuteClickSounds: False
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Logging Level: DEBUG
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Error Reporting: 
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ABOUT:-
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Alpha Releases: False
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Skip Version: 
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Subscribed: 01-Jan-2000
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Timezone Database: 2018e
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ENVIRONMENT:-
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Current Locale: en-US
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Date Format: M/d/yyyy
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Time Format: h:mm tt
2018-08-23 16:21:18,574 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Completed Syncs: 6563
2018-08-23 16:21:18,647 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Create the timer for the auto synchronisation
2018-08-23 16:21:18,651 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for Thursday, August 23, 2018 @ 4:22:18 PM
2018-08-23 16:21:22,568 DEBUG  16 OutlookGoogleCalendarSync.Forms.Splash [0] -  Disposed of splash screen.
2018-08-23 16:21:30,546 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Manual sync requested.
2018-08-23 16:21:30,608 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync version: 2.7.5.0
2018-08-23 16:21:30,608 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync started at 8/23/2018 4:21:30 PM
2018-08-23 16:21:30,609 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Syncing from 8/22/2018 to 10/23/2018
2018-08-23 16:21:30,609 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Outlook → Google
2018-08-23 16:21:30,662 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Authenticating with Google calendar service...
2018-08-23 16:21:30,664 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Google credential file location: C:\Users\swest\AppData\Roaming\Outlook Google Calendar Sync\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user
2018-08-23 16:21:30,695 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  User has provided authorisation and credential file saved.
2018-08-23 16:21:30,695 INFO  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Refresh and Access token successfully retrieved.
2018-08-23 16:21:30,695 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token expires 8/23/2018 2:04:43 PM
2018-08-23 16:21:30,698 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token needs refreshing.
2018-08-23 16:21:32,240 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token refreshed.
2018-08-23 16:21:32,245 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Retrieving email address associated with Google account.
2018-08-23 16:21:32,703 DEBUG  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Reading response.
2018-08-23 16:21:32,704 ERROR  21 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  {
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "accessNotConfigured",
    "message": "Access Not Configured. Google+ API has not been used in project 456234065785 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=456234065785 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "extendedHelp": "https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=456234065785"
   }
  ],
  "code": 403,
  "message": "Access Not Configured. Google+ API has not been used in project 456234065785 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=456234065785 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."
 }
}

2018-08-23 16:21:32,752 DEBUG  21 OutlookGoogleCalendarSync.Forms.ErrorReporting [0] -  Asking user if they want to automatically report errors.
```

**Comment by stephengeorgewest-navitaire** [comment]
I enabled the api via the link, and it doesn't show the error dialog anymore. And doesn't crash anymore.

**Comment by phw198** [comment]
I don't think it's worth spending time improving the prettiness of this error (eg proactively checking this API is enabled), as the API is being deprecated by Google and will be removed from the next release of OGCS.

🔗  See issue #646
