### ISSUE TITLE
2 way sync failing to correctly handle new google calendar entries copied from external google calendar

### ISSUE THREAD

**Issue by kwagner115** [phw198/OutlookGoogleCalendarSync#600]
Starting with outlook and google calendars 100% in sync.

1) Copy an existing google calendar entry from separate google account, not part of outlook sync processes, into my google calendar.

2) run 2 way sync. All is good.

3) run 2 way sync again, message to OK to delete the entry is presented. I say no. The numbers of calendar entries now has changed.

4) run sync again, same count discrepancies, and delete message.  

5) I can recreate the issue at will. 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2397103/OGcalsync.log)

**Comment by kwagner115** [comment]
```
2018-09-23 14:32:52,760 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Setting up Squirrel handlers.
2018-09-23 14:32:52,823 DEBUG  6 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'CompletedSyncs' with value '11522'
2018-09-23 14:32:52,825 DEBUG  6 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'Donor' with value 'false'
2018-09-23 14:32:52,825 DEBUG  6 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'Subscribed' with value '2000-01-01T00:00:00'
2018-09-23 14:32:52,826 DEBUG  6 OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'HideSplashScreen' with value 'false'
2018-09-23 14:32:52,827 DEBUG  6 OutlookGoogleCalendarSync.Forms.Splash [0] -  Showing splash screen.
2018-09-23 14:32:52,868 DEBUG  1 OutlookGoogleCalendarSync.Program [0] -  Loading settings from file.
2018-09-23 14:32:52,919 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Automatic update check requested.
2018-09-23 14:32:52,921 INFO  1 OutlookGoogleCalendarSync.SettingsProxy [0] -  Removing proxy usage.
2018-09-23 14:32:52,925 DEBUG  1 OutlookGoogleCalendarSync.Updater [0] -  Checking for Squirrel update...
2018-09-23 14:32:52,959 INFO  1 OutlookGoogleCalendarSync.NotificationTray [0] -  Using NodaTime TZDB: 2018e (mapping: 13923)
2018-09-23 14:32:52,960 DEBUG  17 OutlookGoogleCalendarSync.NotificationTray [0] -  Checking for new timezone database...
2018-09-23 14:32:52,961 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Initialiasing MainForm.
2018-09-23 14:32:53,051 DEBUG  17 OutlookGoogleCalendarSync.NotificationTray [0] -  Already have latest TZDB version.
2018-09-23 14:32:53,223 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attaching to the already running Outlook process.
2018-09-23 14:32:53,226 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attachment failed - Outlook is running without GUI for programmatic access.
2018-09-23 14:32:53,229 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Starting a new instance of Outlook.
2018-09-23 14:32:53,382 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Factory [0] -  Outlook Version: 16.0.0.10730
2018-09-23 14:32:53,382 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Getting MD5 hash for 'kw*******5@gmail.com'
2018-09-23 14:32:53,382 DEBUG  1 OutlookGoogleCalendarSync.Analytics [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&cid=0f16f3ad53964d26d71ea7606de951c5&ec=outlook&ea=version&el=2016
2018-09-23 14:32:53,398 DEBUG  1 OutlookGoogleCalendarSync.Analytics [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&cid=0f16f3ad53964d26d71ea7606de951c5&ec=ogcs&ea=version&el=2.7.6.0
2018-09-23 14:32:53,414 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Find Folders
2018-09-23 14:32:53,414 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attaching to the already running Outlook process.
2018-09-23 14:32:53,414 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Attachment failed - Outlook is running without GUI for programmatic access.
2018-09-23 14:32:53,414 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Starting a new instance of Outlook.
2018-09-23 14:32:53,429 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Setting up Outlook connection.
2018-09-23 14:32:53,429 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Exchange connection mode: olNoExchange
2018-09-23 14:32:53,452 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Getting active window inspector
2018-09-23 14:32:53,458 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Done.
2018-09-23 14:32:53,477 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Get the folders configured in Outlook
2018-09-23 14:32:53,482 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Finding Alternative Mailbox calendar folders
2018-09-23 14:32:53,665 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Default Calendar folder: Gmail
2018-09-23 14:32:53,669 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [0] -  Folder type: olNotExchange
2018-09-23 14:32:53,673 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Setting up Explorer event watchers.
2018-09-23 14:32:53,673 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Watch needed for 1 existing explorers.
2018-09-23 14:32:53,689 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [0] -  Adding listener for Explorer 'Inbox - kwagner115@gmail.com - Outlook'
2018-09-23 14:32:53,720 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  List Calendar folders
2018-09-23 14:32:53,772 DEBUG  1 OutlookGoogleCalendarSync.Program [0] -  CheckShortcut: directory=Startup; subdir=
2018-09-23 14:32:53,772 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  Logging level configured to 'Debug'
2018-09-23 14:32:53,772 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  C:\Users\Kevin\AppData\Roaming\Outlook Google Calendar Sync\settings.xml
2018-09-23 14:32:53,772 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  OUTLOOK SETTINGS:-
2018-09-23 14:32:53,772 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Service: AlternativeMailbox
2018-09-23 14:32:53,772 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Mailbox/FolderStore Name: iCloud
2018-09-23 14:32:53,772 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: Gmail
2018-09-23 14:32:53,772 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Category Filter: Exclude
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Categories: 
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Only Responded Invites: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Filter String: g
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    GAL Blocked: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  GOOGLE SETTINGS:-
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: Kevin
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Personal API Keys: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Identifier: 
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Secret: 
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit in effect: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit last reached: 01/01/00 12:00:00 AM
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Assigned API key: 653617509806-2nq341ol8ejgqhh2ku4j45m7q2bgdimv.apps.googleusercontent.com
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Cloak Email: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  SYNC OPTIONS:-
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   How
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncDirection: Outlook ↔ Google
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MergeItems: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DisableDelete: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ConfirmOnDelete: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesPrivate: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesAvailable: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesColour: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Obfuscate Words: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   When
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInThePast: 10
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInTheFuture:365
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncInterval: 2
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncIntervalUnit: Hours
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Push Changes: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   What
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddLocation: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddDescription: True; OnlyToGoogle: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddAttendees: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddColours: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddReminders: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      UseGoogleDefaultReminder: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      ReminderDND: False (22:00-06:00)
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  PROXY:-
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Type: None
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  APPLICATION BEHAVIOUR:-
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleTooltipWhenSyncing: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartOnStartup: True; DelayedStartup: 300
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    HideSplashScreen: N/A
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartInTray: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseToTray: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseNotClose: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleWhenMinimising: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Portable: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    CreateCSVFiles: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    VerboseOutput: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MuteClickSounds: False
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Logging Level: DEBUG
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Error Reporting: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ABOUT:-
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Alpha Releases: True
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Skip Version: 
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Subscribed: 01-Jan-2000
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Timezone Database: 2018e
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ENVIRONMENT:-
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Current Locale: en-US
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Date Format: MM/dd/yy
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Time Format: h:mm tt
2018-09-23 14:32:53,787 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Completed Syncs: 11522
2018-09-23 14:32:53,819 DEBUG  1 OutlookGoogleCalendarSync.Forms.Main [0] -  Create the timer for the auto synchronisation
2018-09-23 14:32:53,819 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for September 23, 2018 @ 4:17:51 PM + Push
2018-09-23 14:32:53,819 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Create the timer for the push synchronisation
2018-09-23 14:32:53,936 INFO  9 OutlookGoogleCalendarSync.Updater [0] -  Already running the latest version of OGCS.
2018-09-23 14:33:00,921 DEBUG  6 OutlookGoogleCalendarSync.Forms.Splash [0] -  Disposed of splash screen.
2018-09-23 14:33:22,063 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  Manual sync requested.
2018-09-23 14:33:22,110 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync version: 2.7.6.0
2018-09-23 14:33:22,110 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync started at 09/23/18 2:33:22 PM
2018-09-23 14:33:22,110 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Syncing from 09/13/18 to 09/24/19
2018-09-23 14:33:22,110 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Outlook ↔ Google
2018-09-23 14:33:22,125 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Stop monitoring for Outlook appointment changes...
2018-09-23 14:33:22,125 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for September 23, 2018 @ 4:17:51 PM + Push
2018-09-23 14:33:22,125 DEBUG  26 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Getting keyring.
2018-09-23 14:33:22,422 DEBUG  26 OutlookGoogleCalendarSync.GoogleOgcs.ApiKey [0] -  OGCS Default = ACTIVE
2018-09-23 14:33:22,422 DEBUG  26 OutlookGoogleCalendarSync.GoogleOgcs.ApiKey [0] -  OGCS PW 001 = DISABLED
2018-09-23 14:33:22,422 DEBUG  26 OutlookGoogleCalendarSync.GoogleOgcs.ApiKey [0] -  OGCS KW 001 = DISABLED
2018-09-23 14:33:22,422 DEBUG  26 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  There are 3 keys.
2018-09-23 14:33:22,422 DEBUG  26 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  1 keys are active.
2018-09-23 14:33:22,422 DEBUG  26 OutlookGoogleCalendarSync.GoogleOgcs.ApiKeyring [0] -  Picking a Standard key.
2018-09-23 14:33:22,453 DEBUG  22 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Authenticating with Google calendar service...
2018-09-23 14:33:22,453 DEBUG  22 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Google credential file location: C:\Users\Kevin\AppData\Roaming\Outlook Google Calendar Sync\Google.Apis.Auth.OAuth2.Responses.TokenResponse-user
2018-09-23 14:33:22,485 DEBUG  22 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  User has provided authorisation and credential file saved.
2018-09-23 14:33:22,485 INFO  22 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Refresh and Access token successfully retrieved.
2018-09-23 14:33:22,485 DEBUG  22 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Access token expires 09/23/18 3:17:53 PM
2018-09-23 14:33:22,485 DEBUG  22 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Retrieving email address associated with Google account.
2018-09-23 14:33:22,797 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Retrieving all subscribers from past year.
2018-09-23 14:33:24,032 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Page 1 received.
2018-09-23 14:33:24,032 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Searching for subscription for: kw*******5@gmail.com
2018-09-23 14:33:24,032 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Retrieving all donors.
2018-09-23 14:33:24,219 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Page 1 received.
2018-09-23 14:33:24,219 DEBUG  1 OutlookGoogleCalendarSync.GoogleOgcs.Authenticator [0] -  Searching for donation from: kw*******5@gmail.com
2018-09-23 14:33:24,219 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'Donor' updated to 'False'
2018-09-23 14:33:24,219 INFO  23 OutlookGoogleCalendarSync.Console [0] -  Finding Calendar Entries
2018-09-23 14:33:24,796 INFO  23 OutlookGoogleCalendarSync.Console [0] -  Scanning Outlook calendar...
2018-09-23 14:33:25,530 INFO  23 OutlookGoogleCalendarSync.Console [0] -  72 Outlook calendar entries found.
2018-09-23 14:33:26,125 INFO  23 OutlookGoogleCalendarSync.Console [0] -  Scanning Google calendar...
2018-09-23 14:33:26,672 DEBUG  23 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving all events from Google: 09/13/18 -> 09/24/19
2018-09-23 14:33:26,968 DEBUG  23 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Page 1 received.
2018-09-23 14:33:26,968 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  Identifying exceptions in recurring Google events.
2018-09-23 14:33:26,968 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  Found 3 exceptions.
2018-09-23 14:33:26,968 INFO  23 OutlookGoogleCalendarSync.Console [0] -  72 Google calendar entries found.
2018-09-23 14:33:27,328 INFO  23 OutlookGoogleCalendarSync.Console [0] -  3 are exceptions to recurring events.
2018-09-23 14:33:27,766 INFO  23 OutlookGoogleCalendarSync.Console [0] -  Total inc. recurring items spanning sync date range...
2018-09-23 14:33:28,890 DEBUG  23 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving specific Event with ID 419btkgcce9nslp1ilb78aiim4
2018-09-23 14:33:29,733 INFO  23 OutlookGoogleCalendarSync.Console [0] -  Outlook 72, Google 72
2018-09-23 14:33:30,311 DEBUG  23 OutlookGoogleCalendarSync.Sync.Engine [0] -  Synchronising from Outlook to Google.
2018-09-23 14:33:30,311 DEBUG  23 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Scanning 72 Google events for orphans to reclaim...
2018-09-23 14:33:30,889 DEBUG  23 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  0 unclaimed.
2018-09-23 14:33:30,889 DEBUG  23 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Comparing Outlook items to Google events...
2018-09-23 14:35:09,077 INFO  23 OutlookGoogleCalendarSync.Console [0] -  0 Google calendar entries to be deleted.
2018-09-23 14:35:09,077 INFO  23 OutlookGoogleCalendarSync.Console [0] -  0 Google calendar entries to be created.
2018-09-23 14:35:09,077 INFO  23 OutlookGoogleCalendarSync.Console [0] -  72 calendar entries to be compared.
2018-09-23 14:35:09,650 INFO  23 OutlookGoogleCalendarSync.Console [0] -  Comparing 72 existing Google calendar entries
2018-09-23 14:35:10,687 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  05/03/18 5:00 PM (R) => "Amana Men's League"
2018-09-23 14:35:10,687 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring appointment with 4 exceptions that will now be iteratively compared.
2018-09-23 14:35:10,702 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  Finding Google instance for deleted Outlook exception:-
2018-09-23 14:35:10,702 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -    Original date: 20/09/2018
2018-09-23 14:35:10,702 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  Matching Google Event recurrence found.
2018-09-23 14:35:10,702 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  It is deleted in Google, so cannot compare items.
2018-09-23 14:35:10,702 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  Finding Google instance for deleted Outlook exception:-
2018-09-23 14:35:10,702 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -    Original date: 18/10/2018
2018-09-23 14:35:10,718 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  Matching Google Event recurrence found.
2018-09-23 14:35:10,718 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  It is deleted in Google, so cannot compare items.
2018-09-23 14:35:14,905 INFO  23 OutlookGoogleCalendarSync.Console [0] -  0 entries updated.
2018-09-23 14:35:15,436 DEBUG  23 OutlookGoogleCalendarSync.Sync.Engine [0] -  Synchronising from Google to Outlook.
2018-09-23 14:35:15,436 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Scanning 72 Outlook appointments for orphans to reclaim...
2018-09-23 14:35:19,155 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  0 unclaimed.
2018-09-23 14:35:19,155 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Comparing Google events to Outlook items...
2018-09-23 14:35:39,405 INFO  23 OutlookGoogleCalendarSync.Console [0] -  0 Outlook calendar entries to be deleted.
2018-09-23 14:35:39,406 INFO  23 OutlookGoogleCalendarSync.Console [0] -  0 Outlook calendar entries to be created.
2018-09-23 14:35:39,406 INFO  23 OutlookGoogleCalendarSync.Console [0] -  72 calendar entries to be compared.
2018-09-23 14:35:39,906 INFO  23 OutlookGoogleCalendarSync.Console [0] -  Comparing 72 existing Outlook calendar entries
2018-09-23 14:35:40,687 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  09/28/18 6:00 AM (R) => "Fri/Sat/Sun Amana Golf"
2018-09-23 14:35:41,250 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  05/03/18 5:00 PM (R) => "Amana Men's League"
2018-09-23 14:35:41,250 DEBUG  23 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring Google event with 3 exceptions in the sync date range.
2018-09-23 14:35:41,281 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 09/27/18 4:30 PM (R) => "Amana Men's League"
2018-09-23 14:35:41,328 ERROR  23 OutlookGoogleCalendarSync.Console [0] -  Unable to update existing entries in the Outlook calendar.
2018-09-23 14:35:42,500 DEBUG  23 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2018-09-23 14:35:42,500 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The object does not support this method.
2018-09-23 14:35:42,515 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x8E620009;-1906180087
2018-09-23 14:35:42,515 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.Sync.Engine.googleToOutlook(List`1 googleEntries, List`1 outlookEntries, String& bubbleText)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass16_0.<Start>b__0(Object o, DoWorkEventArgs args)
2018-09-23 14:35:42,515 ERROR  23 OutlookGoogleCalendarSync.Console [0] -  The object does not support this method.
2018-09-23 14:35:45,874 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Operation aborted after 1 failed attempts!
2018-09-23 14:35:45,897 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'LastSyncDate' updated to '09/23/18 2:33:22 PM'
2018-09-23 14:35:46,130 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Create the timer for the push synchronisation
```

**Comment by phw198** [comment]
So which is the appointment exhibiting the issue you describe in your OP? `10/31/18 => "Steven /Laura/kids in Florida"` ? If so, this is erroring with `System.ArgumentException: Sorry, something went wrong. You may want to try again.` which is an amazingly vague message from Outlook.

You say you can recreate the error at will - is this with any calendar item copied from another calendar, or just this one? Does it always report the above error when creating the Outlook appointment? If so, I'll probably need to add in some each debug logging to try and close in on the problem...

Also, is your second post for the same issue? It has a very different error message occurring at a very different point.

**Comment by kwagner115** [comment]
I can’t reproduce the error this morning. 
 
Feel free to close. Lots has happened in the 30 days that has past since I first reported. 
 
Windows update, chrome update, office 365 update, etc… 
 
 
Kevin
