### ISSUE TITLE
The application called an interface that was marshalled for a different thread.  [0x8001010E RPC_E_WRONG_THREAD]

### ISSUE THREAD

**Issue by frattaro** [phw198/OutlookGoogleCalendarSync#604]
**OGCS Version**: v2.7.0.0
**Installed or Portable**: Installed

**Problem Description**  
I think it had to do with an Office update. Getting this error now:
```
2018-09-25 22:26:18,463 DEBUG  1 OutlookGoogleCalendarSync.SyncTimer [0] -  Scheduled sync triggered.
2018-09-25 22:26:18,472 INFO  1 OutlookGoogleCalendarSync.MainForm [0] -  Scheduled sync started.
2018-09-25 22:26:18,725 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync version: 2.7.0.0
2018-09-25 22:26:18,725 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Sync started at 9/25/2018 10:26:18 PM
2018-09-25 22:26:18,725 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Syncing from 9/24/2018 to 11/25/2018
2018-09-25 22:26:18,725 DEBUG  1 OutlookGoogleCalendarSync.Console [0] -  Outlook → Google
2018-09-25 22:26:19,037 INFO  32 OutlookGoogleCalendarSync.Console [0] -  Finding Calendar Entries
2018-09-25 22:26:19,799 INFO  32 OutlookGoogleCalendarSync.Console [0] -  Scanning Outlook calendar...
2018-09-25 22:26:20,387 ERROR  32 OutlookGoogleCalendarSync.Console [0] -  Unable to access the Outlook calendar.
2018-09-25 22:26:20,947 DEBUG  32 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2018-09-25 22:26:20,948 ERROR  32 OutlookGoogleCalendarSync.OGCSexception [0] -  System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)).
2018-09-25 22:26:20,948 ERROR  32 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004002;-2147467262
2018-09-25 22:26:20,948 ERROR  32 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.MainForm.synchronize()
   at OutlookGoogleCalendarSync.MainForm.<>c__DisplayClass26_0.<sync_Start>b__0(Object o, DoWorkEventArgs args)
2018-09-25 22:26:20,949 ERROR  32 OutlookGoogleCalendarSync.Console [0] -  Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Office.Interop.Outlook.MAPIFolder'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{00063006-0000-0000-C000-000000000046}' failed due to the following error: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)).
```

**Steps to Reproduce the Issue**  
1. Started happening after latest office update.

**Comment by frattaro** [comment]
To followup, it started working again without issue. Might have been a system restart that fixed it.

**Comment by phw198** [comment]
@frattaro Yes I'd imagine that maybe Outlook got restarted and OGCS got some cross threading going on - a restart of Outlook and OGCS would no doubt resolve it.

I've not seen this particular error before, so don't think it's worth worrying to hard about. Thanks for reporting though!
