### ISSUE TITLE
Additional metadata entry stored instead of updating existing

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#656]
**OGCS Version**: v2.7.7.8
🛑 This issue is **specifically** for those that used hotfixes posted on issue #599, and is working to resolve some bugs introduced in those hotfixes.

**Problem Description**  
Additional Google metadata stored during "reclaim" phase, even though the calendar ID is the same. It should instead update the existing metadata for that calendar.

**Steps to Reproduce the Issue**  
There may be other ways, but:
1. Create a Google item and sync two-way
1. Delete Outlook item
1. Sync one-way G->O
1. Sync two-way

**Any other information**  
Possibly may be making OGCS crash on subsequent syncs too.
```
2019-01-18 14:29:33,593 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Scanning 120 Outlook appointments for orphans to reclaim...
2019-01-18 14:29:33,593 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2019-01-18 14:29:33,593 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  30.12.2018 10:30 => "asfdasdf"
2019-01-18 14:29:33,603 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleCalendarID-01=kpf29aiflco95f3aed9pffvkmc@group.calendar.google.com
2019-01-18 14:29:33,633 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleEventID=6img428lt9pad36prr5fgkveqc
2019-01-18 14:29:33,653 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  OGCSmodified-01=18.01.2019 14:27:00
2019-01-18 14:29:33,673 FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console finished navigating
2019-01-18 14:29:33,733 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  Set userproperty googleEventID=6img428lt9pad36prr5fgkveqc
2019-01-18 14:29:33,763 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  Set userproperty googleCalendarID-01=kpf29aiflco95f3aed9pffvkmc@group.calendar.google.com
2019-01-18 14:29:33,763 FINE  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  GetSummary - not all day event
2019-01-18 14:29:33,763 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  30.12.2018 10:30 => "asfdasdf"
2019-01-18 14:29:33,773 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleCalendarID-01=kpf29aiflco95f3aed9pffvkmc@group.calendar.google.com
2019-01-18 14:29:33,783 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  googleEventID=6img428lt9pad36prr5fgkveqc
2019-01-18 14:29:33,783 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.CustomProperty [0] -  OGCSmodified-01=18.01.2019 14:27:00
2019-01-18 14:29:33,793 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Saving timestamp when OGCS updated appointment.
2019-01-18 14:29:33,843 ERROR  9 OutlookGoogleCalendarSync.Console [0] -  Unable to reclaim orphan calendar entries in Outlook calendar.
2019-01-18 14:29:42,263 DEBUG  9 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2019-01-18 14:29:42,263 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
2019-01-18 14:29:42,263 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2019-01-18 14:29:42,273 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.Sync.Engine.googleToOutlook(List`1 googleEntries, List`1 outlookEntries, String& bubbleText)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
2019-01-18 14:29:42,273 ERROR  9 OutlookGoogleCalendarSync.Console [0] -  Object reference not set to an instance of an object.
2019-01-18 14:29:42,383 FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console finished navigating
2019-01-18 14:29:46,591 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Operation aborted after 1 failed attempts!
2019-01-18 14:29:46,601 FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console finished navigating
2019-01-18 14:29:46,611 DEBUG  1 OutlookGoogleCalendarSync.XMLManager [0] -  Setting 'LastSyncDate' updated to '18.01.2019 14:28:40'
2019-01-18 14:30:36,620 INFO  1 OutlookGoogleCalendarSync.Program [0] -  Application closed.
```

**Comment by salzrat** [comment]
Yes, this happens every time. Tried reducing log level to debug, of course that didn't change anything. Further steps I should try?

**Comment by phw198** [comment]
:package: Please try [hotfix v2.7.7.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2776968/v2.7.7.9.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

I'm not sure if it will handle the slightly corrupted metadata that the previous hotfix produced. If not, try a one-way sync in one direction, then the other before turning back on two-way sync.

**Comment by phw198** [comment]
I think the metadata is too corrupted and as this is a feature of previous buggy hotfixes, and that you are testing it on test calendars, I don't want to write code to heal the corruption. Either just scrap your existing test calendars and build a new test.....or you _could_ try a slightly stronger version of what you tried previously (though I'm not very confident this will work either):

1. Delete Google items
1. One-way sync O->G
1. Delete Outlook items
1. One-way sync G->O
1. Turn back on two-way sync.

**Comment by phw198** [comment]
> I don't want to write code to heal the corruption

In light of recent comments from @kwagner115 and @Stuwilli1 on issue #599, it appears others may now have corrupted metadata on their real calendars (ie not test calendars). If this is true and the above steps don't resolve the problem, please up-vote this comment and I'll see what can be done.

**Comment by salzrat** [comment]
I understand. It's not getting easier though. I tried what you suggested. First, I tried disabling "merge with existing entries", but that didn't change anything, error still appeared.
Then I deleted all google calendar entries (used the program "Bulk Edit Calendar Events" for that, otherwise it would have been very tedious!).
Then synced outlook to google, but this failed on the first event, see the attached log ("Object reference not set to an instance of an object."). I tried for a few events (answering "yes" to the prompt whether to continue), but then aborted as it was too tedious.

Maybe this can be rectified going through an ics file? I exported my outlook test calendar to an ics file and uploaded it so you can have a look. The UID entry has two lines, is this normal? Maybe reimporting the ics file in google or outlook or replacing the additional UID entry with a regular expression might work?

I'm open for any suggestion...

**Comment by salzrat** [comment]
But maybe exporting to ics, deleting the entries and importing again could do that?

**Comment by kwagner115** [comment]
Do we know the offending record(s) and their source, outlook or google? Could we not flag those in the error message, and give end user the option to delete and recreate the bad record?


Kevin

319-382-4461

________________________________

**Comment by kwagner115** [comment]
I am traveling next 7 days and will not be able to test.

Kevin

319-382-4461

________________________________

**Comment by salzrat** [comment]
I tried the new version, and started with an empty google calendar and the corrupted outlook calendar. Please see the uploaded log. Simply trying a new sync didn't work, same error as before. Then I set the setting, cleared the metadata, and then ran a normal two-way sync. That worked fine. I repeated this a couple of times (you'll see in the logfile), sometimes with, sometimes without ultra-fine.

Please see the last 2 runs - it seems that the step "Comparing Google events to Outlook items" still takes a disproportionate amount of time (16s), everything else is super quick. You said the the slow path should only be hit if there were two metadata items per entry, but this should now be fixed. Maybe you can determine from the logfile what's happening...

**Comment by phw198** [comment]
OK, on the whole that sounds good - at least the metadata purge worked.

Yes, I had hoped the slow-down of G->O was because of multiple sets of metadata in Outlook, but it would seem that's not entirely the cause. I think it's simply the way in which custom metadata can be stored in Outlook calendar items isn't as efficient as Google 😞  I think we've reached the end of the road for ways in which to optimise syncing G->O...but the trade-off is users can now sync two-way between different Google calendars that uses a single common Outlook calendar.

**Comment by salzrat** [comment]
one more piece of data: I bit the bullet and moved my production calendar to the new build. Had to extirpate calendar data there as well.

The production calendar has 93 entries (in the 1-year window - overall it has about 170). Takes about 25 seconds for the G->O step, that's more than for the test calendar (at least on second run), which has fewer entries. Strange. Also, the overall time is about 45s. But it's spending 10s dealing with recurring events as far as I can tell from the log.

**Comment by phw198** [comment]
The fundamental issue is the way in which custom attributes/metadata is stored against Outlook - each attribute is a COM object that has to be individually addressed, opened, value retrieved, object de-referenced. This in contrast to Google, where it's a modern Dictionary object with key-value pairs of strings that can be accessed directly.

In versions prior to v2.7.6, it was always assumed the 2 pieces of metadata held in Outlook items (Google calendar ID and Google entry ID) would be for the calendar currently being synced - and if not it would be reclaimed. Obviously this assumption was flawed when needing to support multiple calendars, but it did make for quick access. Now however, there can be multiple "sets" of metadata:
* gCalendarID = fooCal
* gEventID = fooEvent
* gCalendarID_01 = barCal
* gEventID_01 = barEvent

So we need to retrieve all the Google calendars IDs held against an Outlook item, then check if there is one that matches the current calendar being synced. If a match is found, then retrieve the other attributes (event ID) in the same set.

The main enhancement in v2.7.7.12 was to cache the set number for each Outlook item, so it only has to work out which set to work with once. This I had hoped would return performance to similar to that of earlier versions where only one set was ever stored and accessed, but it hasn't I think because there is now more checks to ensure attributes exist etc before accessing them.

I've put granular timings around each operation and can't see anything that jumps out as being sub-optimal,,,,just that accessing COM objects is really rather slow.

>one more piece of data: I bit the bullet and moved my production calendar to the new build. Had to extirpate calendar data there as well.

What was the previous version of OGCS you had in production? Just wondering how many people may be affected and need to extirpate metadata...

**Comment by salzrat** [comment]
Hard to say. Before I had 2.7.5.0. Then I find in my log 2.7.6.10, 2.7.7.0, 2.7.7., but I had definitely applied 2.7.6.10, 2.7.7.0, and 2.7.7.3.

I checked back, and in 2.7.5.0 I had reported 13s for the G->O step. So the time about doubled. Would that correspond to twice as many COM-object calls than before?

**Comment by phw198** [comment]
OK, thanks. Pretty sure the issue was introduced around 2.7.7.3 so hopefully only the people following issue #599 would need to cleanse the metadata.

Probably double the number of COM-object calls would be about right...

**Comment by kwagner115** [comment]
Ok. I am still traveling, and have been unable to keep up with current status. I have 2 instances of app on test and prod machines. What is the process, instructions to get both environments back to a clean state and correct metadata inconsistencies?
 
Thanks in advanced!!
 
Kevin

**Comment by Stuwilli1** [comment]
Paul,

Finally got around to try and am unable to locate the ExtirpateOgcsMetadata
file in the settings.XML file

Stuart

**Comment by Stuwilli1** [comment]
Paul,

I had sent you a note about not being able to find the file in the
Settings.xml file to change (ExtirpateOgcsMetadata).  Any suggestions?

Best regards,

Stuart

**Comment by phw198** [comment]
@Stuwilli1 I can only assume either you're not actually running the hotfix v2.7.7.12, or you're not accessing the correct `settings.xml` for the instance of OGCS running. I've added a new step 3 in the [original instructions above](https://github.com/phw198/OutlookGoogleCalendarSync/issues/656#issuecomment-457030599):
> 3. Go to `About` tab and double click the `Config In` file location to open Windows Explorer, then close OGCS

**Comment by Stuwilli1** [comment]
Thanks and will give it a try and provide documentation otherwise! 

Stuart


On Feb 6, 2019, at 12:00 AM, Paul Woolcock <notifications@github.com> wrote:

@Stuwilli1 I can only assume either you're not actually running the hotfix v2.7.7.12, or you're not accessing the correct settings.xml for the instance of OGCS running. I've added a new step 3 in the original instructions above:

Go to About tab and double click the Config In file location to open Windows Explorer, then close OGCS

**Comment by Stuwilli1** [comment]
Confirmed 2.7.7.12 is running and attached XML file also confirms.

Stuart

**Comment by kwagner115** [comment]
Paul,
 
I’m now back from vacation.
 
What is the most current beta / alpha / hotfix version I should be testing with? 
 
 
Kevin
 
 <mailto:kwagner115@gmail.com> kwagner115@gmail.com
319-382-4461 (mobile)

**Comment by phw198** [comment]
@kwagner115 Alpha v2.7.8.0 is now out, so please upgrade to this.

@Stuwilli1 As always, you can't attach files by email so there is no XML file with your post.
