### ISSUE TITLE
Unable to find a calendar folder in the alternative mailbox.

### ISSUE THREAD

**Issue by emilyjohns1109** [phw198/OutlookGoogleCalendarSync#673]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v1.2.3.4  
**Installed or Portable**: Installed

**Problem Description**  
\<Unable to sync a secondary (non-default) calendar in outlook with a google calendar.  I get the following message: "Unable to find a calendar folder in the alternative mailbox.   Reverting to the default  mailbox calendar." >

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
What version of OGCS are you running?

_Is_ there a calendar folder in the alternate mailbox? What is the account type for that mailbox? If it's POP3 or IMAP that doesn't support calendars...

Can you provide screenshots etc of the calendar in Outlook you expect it to be finding?

**Comment by SullyGIT** [comment]
I seem to have his the same issue here, but not sure if you want me to create a new issue or just add in the screenshots and/or logs from my instance of this.

I have multiple mailboxes, but the default entry in the Alternative is a gmail account so it is IMAP and I know this won't work.  Feels like I need a way to force OGCS past the IMAP mailboxes to the ones I want to see.

I'll hedge my bet and add in my screenshots...

**Error showing Alternative calendar greyed out:**
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/56499319/93160e0d-d840-4b92-8af8-d996b18051a7)

**My mailboxes:**
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/56499319/adc8e4d9-ced7-4a66-9967-50bebb224c7b)

Let me know what else I can provide to aid diagnosis and I'll get straight on it.

Cheers,

Ian

**Comment by SullyGIT** [comment]
Just had this error come up:
![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/56499319/e91b7bce-937f-4864-84b2-d14105ffb5fc)

Here are the contents of the details area:
<details><summary>Logs</summary>

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Office.Interop.Outlook.NameSpaceClass.Logoff()
   at OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew.Connect() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookNew.cs:line 107
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.Reset() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\OutlookOgcs\OutlookCalendar.cs:line 75
   at OutlookGoogleCalendarSync.Forms.Main.rbOutlookAltMB_CheckedChanged(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 1327
   at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
   at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
   at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
OutlookGoogleCalendarSync
    Assembly Version: 2.10.8702.31664
    Win32 Version: 2.10.2.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/OutlookGoogleCalendarSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
log4net
    Assembly Version: 2.0.15.0
    Win32 Version: 2.0.15.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Squirrel
    Assembly Version: 1.9.0.0
    Win32 Version: 1.9.0.1
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Squirrel.DLL
----------------------------------------
Splat
    Assembly Version: 1.6.2.0
    Win32 Version: 1.6.2
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Splat.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Newtonsoft.Json.DLL
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Google.Cloud.Logging.Log4Net
    Assembly Version: 2.5.0.0
    Win32 Version: 2.5.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Cloud.Logging.Log4Net.DLL
----------------------------------------
Google.Cloud.Logging.V2
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Cloud.Logging.V2.DLL
----------------------------------------
Google.Protobuf
    Assembly Version: 3.17.3.0
    Win32 Version: 3.17.3.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Protobuf.DLL
----------------------------------------
Google.Cloud.Logging.Type
    Assembly Version: 2.1.0.0
    Win32 Version: 2.1.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Cloud.Logging.Type.DLL
----------------------------------------
Google.Api.Gax
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Api.Gax.DLL
----------------------------------------
Google.Api.CommonProtos
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Api.CommonProtos.DLL
----------------------------------------
Google.Api.Gax.Grpc
    Assembly Version: 2.10.0.0
    Win32 Version: 2.10.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Api.Gax.Grpc.DLL
----------------------------------------
Google.Apis.Auth
    Assembly Version: 1.60.0.0
    Win32 Version: 1.60.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Apis.Auth.DLL
----------------------------------------
Google.Apis.Core
    Assembly Version: 1.60.0.0
    Win32 Version: 1.60.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Apis.Core.DLL
----------------------------------------
Grpc.Core
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.1.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Grpc.Core.DLL
----------------------------------------
Grpc.Core.Api
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Grpc.Core.Api.DLL
----------------------------------------
Grpc.Auth
    Assembly Version: 1.0.0.0
    Win32 Version: 1.22.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Grpc.Auth.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9191.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
NuGet.Squirrel
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/NuGet.Squirrel.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
NodaTime
    Assembly Version: 2.4.18.0
    Win32 Version: 2.4.18.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/NodaTime.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------
Microsoft.Office.Interop.Outlook
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4569.1507
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.Office.Interop.Outlook/15.0.0.0__71e9bce111e9429c/Microsoft.Office.Interop.Outlook.dll
----------------------------------------
office
    Assembly Version: 15.0.0.0
    Win32 Version: 15.0.4613.1000
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/office/15.0.0.0__71e9bce111e9429c/office.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
CustomMarshalers
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/CustomMarshalers/v4.0_4.0.0.0__b03f5f7f11d50a3a/CustomMarshalers.dll
----------------------------------------
Google.Apis.Calendar.v3
    Assembly Version: 1.60.0.3088
    Win32 Version: 1.60.0.3088
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Apis.Calendar.v3.DLL
----------------------------------------
Google.Apis
    Assembly Version: 1.60.0.0
    Win32 Version: 1.60.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Apis.DLL
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Google.Cloud.DevTools.Common
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/Google.Cloud.DevTools.Common.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/System.Memory.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/New%20Buyer/AppData/Local/OutlookGoogleCalendarSync/app-2.10.2-alpha/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box. 
```
</details>

**Comment by phw198** [comment]
@SullyGIT Can you provide your `OGcalsync.log` file after you hit the error when selecting the Alternate mailbox? If I select an IMAP mailbox/account, Outlook still has a calendar folder locally for it - usually named "IMAP calendar (This computer only)".

However, if I delete that local IMAP calendar, then I get the same error - that might be a workaround to create a calendar folder yourself.

**Comment by phw198** [comment]
:package: Actually, you might like to try [hotfix v2.10.3.2.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14132718/v2.10.3.2.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `8932455A` Exe = `3463D5F9`

This will loop through the available alternate mailbox accounts until a calendar is found. If none is found, then the previous behaviour is invoked - fall back to the default mailbox.

Please let me know how it goes!

**Comment by MichaelOvens** [comment]
I had this issue and applying the above hotfix solved it. Thanks!

**Comment by tvarohohlavy** [comment]
> I had this issue and applying the above hotfix solved it. Thanks!

Same for me : )
