### ISSUE TITLE
Outlook reporting all items are "moved or deleted"

### ISSUE THREAD

**Issue by Kateylynn4** [phw198/OutlookGoogleCalendarSync#721]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**: v2.7.8.0  
**Installed or Portable**: Installed

**Problem Description**  
OGCS unable to access any Outlook calendar item - reporting "moved or deleted".

**Steps to Reproduce the Issue**  
1. \<Update>
1. 

**Any other information**  
[OGcalsync.log.2019-04-29.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3131326/OGcalsync.log.2019-04-29.zip)
```
2019-04-29 10:05:15,191 WARN  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Failed to get appointment summary: 
2019-04-29 10:05:15,192 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: The item has been moved or deleted.
2019-04-29 10:05:15,265 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0xE514010A;-451673846
2019-04-29 10:05:15,266 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_AllDayEvent()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.GetEventSummary(AppointmentItem ai, Boolean onlyIfNotVerbose)
```

**Comment by phw198** [comment]
Thanks for reporting, but I don't think there's anything to be done. For some reason Outlook was reporting every single object has been "moved or deleted", but the subsequent since 15 minutes later worked fine.

If this was just a one-off problematic sync, the issue can be closed.

**Comment by phw198** [comment]
Issue abandoned by user.
