### ISSUE TITLE
All of the sudden, Sync failure

### ISSUE THREAD

**Issue by xraydoc** [phw198/OutlookGoogleCalendarSync#792]
OGCS Version 2.8.0.0

Failure on syncing. Just started with out any changes to programs

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3449432/OGcalsync.log)

**Comment by phw198** [comment]
```
2019-07-30 15:24:02,303 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 8/10/2019 2:45 PM => "Flight: UA 9807 from ORD to ZRH"
2019-07-30 15:24:02,328 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Doing a dummy update in order to update the last modified date.
2019-07-30 15:24:02,353 DEBUG  23 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Saving timestamp when OGCS updated appointment.
2019-07-30 15:24:02,393 ERROR  23 OutlookGoogleCalendarSync.Console [0] -  Unable to update existing entries in the Outlook calendar.
2019-07-30 15:24:04,468 DEBUG  23 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2019-07-30 15:24:04,468 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: Unknown error
2019-07-30 15:24:04,468 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x8004010F;-2147221233
2019-07-30 15:24:04,468 ERROR  23 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.Sync.Engine.googleToOutlook(List`1 googleEntries, List`1 outlookEntries, String& bubbleText)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
2019-07-30 15:24:04,468 ERROR  23 OutlookGoogleCalendarSync.Console [0] -  Unknown error
```

So it looks like OGCS is unable to update `8/10/2019 2:45 PM => "Flight: UA 9807 from ORD to ZRH"` in Outlook due to `Unknown error`....very helpful!

Do you know what created this entry? Does the problem remain if you close Outlook and OGCS and re-open? Are you able to edit the entry manually? Can you recreate it and see if that helps?
