### ISSUE TITLE
Sync continuously fails since full re-sync

### ISSUE THREAD

**Issue by DannyBeanz** [phw198/OutlookGoogleCalendarSync#811]
**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed

**Problem Description**  
I noticed that Outlook meeting attendees were not configured to sync to my Google calendar, so I enabled this option and followed the steps here: https://github.com/phw198/outlookgooglecalendarsync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync to perform a full resync.

Since doing this, every subsequent sync has failed with the following entries appearing the log file:
```
2019-08-21 14:43:16,238 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 24/10/2019 => "DM in Birmingham"
2019-08-21 14:43:16,319 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Doing a dummy update in order to update the last modified date.
2019-08-21 14:43:16,345 DEBUG  9 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Saving timestamp when OGCS updated appointment.
2019-08-21 14:43:16,379 ERROR  9 OutlookGoogleCalendarSync.Console [0] -  Unable to update existing entries in the Outlook calendar.
2019-08-21 14:43:16,736 DEBUG  9 OutlookGoogleCalendarSync.Console [0] -  The following error was encountered during sync:-
2019-08-21 14:43:16,737 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
2019-08-21 14:43:16,738 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2019-08-21 14:43:16,738 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.Sync.Engine.googleToOutlook(List`1 googleEntries, List`1 outlookEntries, String& bubbleText)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
2019-08-21 14:43:16,739 ERROR  9 OutlookGoogleCalendarSync.Console [0] -  Object reference not set to an instance of an object.
2019-08-21 14:43:43,394 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Operation aborted after 1 failed attempts!
2019-08-21 14:43:43,624 ERROR  1 OutlookGoogleCalendarSync.Console [0] -  Value cannot be null`
```

**Steps to Reproduce the Issue**  
1. Configure OGCS for 2-way sync without attendee sync enabled.
2. Perform a sync.
3. Enable attendee sync
4. Follow steps here https://github.com/phw198/outlookgooglecalendarsync/wiki/Hints-&-Tips#fixing-a-stubborn-unwanted-deletion-with-full-sync to perform a full re-sync
5. Sync as usual on a schedule, or manually.
6. Receive error.

**Any other information**  
\<Update here>

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

Let me know if the issue then still remains.

**Comment by DannyBeanz** [comment]
Hi,

That appears to have done the trick - thank you for your help, and sorry for not trying the upgrade first 🤦‍♂️.

As an aside, the auto update within the app failed.  I suspect it's something on my side that caused it to fail but thought it best to mention in case it's something your side 👍
