### ISSUE TITLE
Crash loop - closing app when syncing

### ISSUE THREAD

**Issue by YasharF** [phw198/OutlookGoogleCalendarSync#846]
**OGCS Version**: v2.8.1.0
**Installed or Portable**: Installed

**Bug Description**  
The app crashes and is stuck in a loop, popping up crash screens over and over, until the process is terminated in Windows Task Manager.

**Steps to Reproduce the Issue**  
I have run into this bug three times, and this is what happened.  I suspect there might be a few different places that some improvements may be helpful:
1. The app starts to sync in the background.
2. It produces a taskbar bubble that it is syncing.
3. It also produces a popup to confirm an item that is to be deleted
4. I used the bubble to open the app, didn't see the popup for delete confirmation (perhaps it was under something else.  I clicked on the upper X to close the app, thinking it would stay in the taskbar and continue with its work.  But the app terminated.
5. The delete confirmation stayed, and when I clicked on yes go ahead and delete, it got into an error loop.  The first time It was popping up a crash report like screen.  There was a button that said don't show this again or something of that nature.  I clicked don't show thinking it would terminate the error popups. Now the error loop is occurring, but not even visible, Windows is just constantly beeping.
6. The error loop can be terminated by using the Windows Task Manager and killing the process.

**Any other information**  
The section of the log file that I think is for this issue is as follows. (I replaced three items that I thought are sensitive with [redacted])

```
2019-09-16 15:11:48,793 DEBUG  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Scheduled sync triggered.
2019-09-16 15:11:48,797 DEBUG  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Busy syncing already. Rescheduled for 5 mins time.
2019-09-16 15:11:48,800 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for Monday, September 16, 2019 @ 3:16:48 PM + Push
2019-09-16 15:16:48,846 DEBUG  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Scheduled sync triggered.
2019-09-16 15:16:48,847 DEBUG  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Busy syncing already. Rescheduled for 5 mins time.
2019-09-16 15:16:48,848 INFO  1 OutlookGoogleCalendarSync.Sync.SyncTimer [0] -  Next sync scheduled for Monday, September 16, 2019 @ 3:21:48 PM + Push
2019-09-16 15:17:06,140 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  Saving settings.
2019-09-16 15:17:06,160 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  C:\Users\[redacted]\AppData\Roaming\Outlook Google Calendar Sync\settings.xml
2019-09-16 15:17:06,160 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  OUTLOOK SETTINGS:-
2019-09-16 15:17:06,160 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Service: DefaultMailbox
2019-09-16 15:17:06,160 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Mailbox/FolderStore Name: 
2019-09-16 15:17:06,161 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: Default Calendar
2019-09-16 15:17:06,161 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Category Filter: Exclude
2019-09-16 15:17:06,161 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Categories: 
2019-09-16 15:17:06,161 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Only Responded Invites: False
2019-09-16 15:17:06,161 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Filter String: g
2019-09-16 15:17:06,161 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    GAL Blocked: False
2019-09-16 15:17:06,162 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  GOOGLE SETTINGS:-
2019-09-16 15:17:06,162 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Calendar: yasharf3@gmail.com
2019-09-16 15:17:06,162 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Personal API Keys: False
2019-09-16 15:17:06,162 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Identifier: 
2019-09-16 15:17:06,162 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      Client Secret: 
2019-09-16 15:17:06,163 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit in effect: False
2019-09-16 15:17:06,163 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    API attendee limit last reached: 1/1/2000 12:00:00 AM
2019-09-16 15:17:06,163 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Assigned API key: [redacted]
2019-09-16 15:17:06,165 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Cloak Email: True
2019-09-16 15:17:06,165 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  SYNC OPTIONS:-
2019-09-16 15:17:06,165 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   How
2019-09-16 15:17:06,165 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncDirection: Outlook ↔ Google
2019-09-16 15:17:06,165 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MergeItems: True
2019-09-16 15:17:06,166 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DisableDelete: False
2019-09-16 15:17:06,166 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ConfirmOnDelete: True
2019-09-16 15:17:06,166 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesPrivate: False
2019-09-16 15:17:06,166 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesAvailable: False
2019-09-16 15:17:06,166 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SetEntriesColour: False
2019-09-16 15:17:06,167 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Obfuscate Words: False
2019-09-16 15:17:06,167 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   When
2019-09-16 15:17:06,167 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInThePast: 5
2019-09-16 15:17:06,168 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    DaysInTheFuture:60
2019-09-16 15:17:06,168 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncInterval: 2
2019-09-16 15:17:06,168 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SyncIntervalUnit: Hours
2019-09-16 15:17:06,168 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Push Changes: True
2019-09-16 15:17:06,168 INFO  1 OutlookGoogleCalendarSync.Settings [0] -   What
2019-09-16 15:17:06,168 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddLocation: True
2019-09-16 15:17:06,169 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddDescription: True; OnlyToGoogle: True
2019-09-16 15:17:06,169 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddAttendees: False
2019-09-16 15:17:06,169 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddColours: False
2019-09-16 15:17:06,169 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    AddReminders: False
2019-09-16 15:17:06,169 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      UseGoogleDefaultReminder: False
2019-09-16 15:17:06,169 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      UseOutlookDefaultReminder: False
2019-09-16 15:17:06,170 INFO  1 OutlookGoogleCalendarSync.Settings [0] -      ReminderDND: False (22:00-06:00)
2019-09-16 15:17:06,170 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  PROXY:-
2019-09-16 15:17:06,170 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Type: IE
2019-09-16 15:17:06,170 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  APPLICATION BEHAVIOUR:-
2019-09-16 15:17:06,170 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleTooltipWhenSyncing: False
2019-09-16 15:17:06,170 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartOnStartup: False; DelayedStartup: 0
2019-09-16 15:17:06,171 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    HideSplashScreen: N/A
2019-09-16 15:17:06,171 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    SuppressSocialPopup: N/A
2019-09-16 15:17:06,171 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    StartInTray: False
2019-09-16 15:17:06,171 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseToTray: True
2019-09-16 15:17:06,171 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MinimiseNotClose: False
2019-09-16 15:17:06,171 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    ShowBubbleWhenMinimising: False
2019-09-16 15:17:06,172 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Portable: False
2019-09-16 15:17:06,172 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    CreateCSVFiles: False
2019-09-16 15:17:06,172 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    VerboseOutput: True
2019-09-16 15:17:06,172 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    MuteClickSounds: False
2019-09-16 15:17:06,172 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Logging Level: DEBUG
2019-09-16 15:17:06,172 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Error Reporting: False
2019-09-16 15:17:06,172 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ABOUT:-
2019-09-16 15:17:06,173 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Alpha Releases: True
2019-09-16 15:17:06,173 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Skip Version: 
2019-09-16 15:17:06,173 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Subscribed: 01-Jan-2000
2019-09-16 15:17:06,173 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Timezone Database: 2019c
2019-09-16 15:17:06,173 INFO  1 OutlookGoogleCalendarSync.Settings [0] -  ENVIRONMENT:-
2019-09-16 15:17:06,173 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Current Locale: en-US
2019-09-16 15:17:06,173 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Date Format: M/d/yyyy
2019-09-16 15:17:06,174 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Short Time Format: h:mm tt
2019-09-16 15:17:06,174 INFO  1 OutlookGoogleCalendarSync.Settings [0] -    Completed Syncs: 7
2019-09-16 15:17:13,244 INFO  19 OutlookGoogleCalendarSync.Console [0] -  Deleted: 9/16/2019 1:00 PM  "[redacted]"
2019-09-16 15:17:13,248 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Event deletion failed.
2019-09-16 15:17:13,250 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Cannot access a disposed object.
2019-09-16 15:17:13,251 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Object name: 'WebBrowser'.
2019-09-16 15:17:13,252 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Unable to delete obsolete entries in Google calendar.
2019-09-16 15:17:13,252 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Cannot access a disposed object.
2019-09-16 15:17:13,252 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Object name: 'WebBrowser'.
2019-09-16 15:17:13,367 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'WebBrowser'.
2019-09-16 15:17:13,368 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131622;-2146232798
2019-09-16 15:17:13,370 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.Windows.Forms.WebBrowser.get_AxIWebBrowser2()
   at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.set_Url(Uri value)
   at System.Windows.Forms.WebBrowser.set_DocumentStream(Stream value)
   at System.Windows.Forms.WebBrowser.set_DocumentText(String value)
   at OutlookGoogleCalendarSync.Console.Update(String moreOutput, Nullable`1 markupPrefix, Boolean newLine, Boolean verbose, Boolean notifyBubble, Boolean logit)
   at OutlookGoogleCalendarSync.Console.UpdateWithError(String moreOutput, Exception ex, Boolean notifyBubble)
   at OutlookGoogleCalendarSync.Sync.Engine.outlookToGoogle(List`1 outlookEntries, List`1 googleEntries, String& bubbleText)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
2019-09-16 15:17:13,370 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Cannot access a disposed object.
2019-09-16 15:17:13,370 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Object name: 'WebBrowser'.
2019-09-16 15:17:13,527 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  User opted to retry sync straight away.
2019-09-16 15:17:13,528 INFO  11 OutlookGoogleCalendarSync.Console [0] -  Finding Calendar Entries
2019-09-16 15:17:13,528 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -  System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'WebBrowser'.
2019-09-16 15:17:13,528 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131622;-2146232798
2019-09-16 15:17:13,529 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.Windows.Forms.WebBrowser.get_AxIWebBrowser2()
   at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.set_Url(Uri value)
   at System.Windows.Forms.WebBrowser.set_DocumentStream(Stream value)
   at System.Windows.Forms.WebBrowser.set_DocumentText(String value)
   at OutlookGoogleCalendarSync.Console.Update(String moreOutput, Nullable`1 markupPrefix, Boolean newLine, Boolean verbose, Boolean notifyBubble, Boolean logit)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
2019-09-16 15:17:13,529 ERROR  11 OutlookGoogleCalendarSync.Console [0] -  Cannot access a disposed object.
2019-09-16 15:17:13,529 ERROR  11 OutlookGoogleCalendarSync.Console [0] -  Object name: 'WebBrowser'.
2019-09-16 15:17:13,740 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  User opted to retry sync straight away.
2019-09-16 15:17:13,741 INFO  19 OutlookGoogleCalendarSync.Console [0] -  Finding Calendar Entries
2019-09-16 15:17:13,741 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'WebBrowser'.
2019-09-16 15:17:13,741 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131622;-2146232798
2019-09-16 15:17:13,741 ERROR  19 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.Windows.Forms.WebBrowser.get_AxIWebBrowser2()
   at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.set_Url(Uri value)
   at System.Windows.Forms.WebBrowser.set_DocumentStream(Stream value)
   at System.Windows.Forms.WebBrowser.set_DocumentText(String value)
   at OutlookGoogleCalendarSync.Console.Update(String moreOutput, Nullable`1 markupPrefix, Boolean newLine, Boolean verbose, Boolean notifyBubble, Boolean logit)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)
2019-09-16 15:17:13,741 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Cannot access a disposed object.
2019-09-16 15:17:13,741 ERROR  19 OutlookGoogleCalendarSync.Console [0] -  Object name: 'WebBrowser'.
2019-09-16 15:17:13,953 INFO  1 OutlookGoogleCalendarSync.Sync.Engine [0] -  User opted to retry sync straight away.
2019-09-16 15:17:13,954 INFO  11 OutlookGoogleCalendarSync.Console [0] -  Finding Calendar Entries
2019-09-16 15:17:13,954 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -  System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'WebBrowser'.
2019-09-16 15:17:13,954 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131622;-2146232798
2019-09-16 15:17:13,954 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.Windows.Forms.WebBrowser.get_AxIWebBrowser2()
   at System.Windows.Forms.WebBrowser.PerformNavigate2(Object& URL, Object& flags, Object& targetFrameName, Object& postData, Object& headers)
   at System.Windows.Forms.WebBrowser.set_Url(Uri value)
   at System.Windows.Forms.WebBrowser.set_DocumentStream(Stream value)
   at System.Windows.Forms.WebBrowser.set_DocumentText(String value)
   at OutlookGoogleCalendarSync.Console.Update(String moreOutput, Nullable`1 markupPrefix, Boolean newLine, Boolean verbose, Boolean notifyBubble, Boolean logit)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass19_0.<Start>b__0(Object o, DoWorkEventArgs args)

```

**Comment by phw198** [comment]
Thanks for the clear explanation of what the issue was. 

I have now made it so that any messagebox popups are associated with the main application window, so it should not be possible to close that now without first responding to the messagebox. 

:package: Please give [hotfix v2.8.1.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3648996/v2.8.1.10.zip) a go ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Let me know how it goes...

**Comment by YasharF** [comment]
Confirming that it didn't let me close the Delete confirmation error, and didn't crash.  Thanks
