### ISSUE TITLE
String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by fogoat** [phw198/OutlookGoogleCalendarSync#870]
**OGCS Version**: v2.8.2.0 Alpha
**Installed or Portable**: Portable

**Bug Description**  
```
2019-10-22 10:51:44,741 DEBUG  25 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing recurring master appointment.
2019-10-22 10:51:44,742 DEBUG  25 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 9/21/2012 (R) => "Loren Ipsum Anniversary"
2019-10-22 10:51:44,797 DEBUG  25 OutlookGoogleCalendarSync.Recurrence [0] -  Converting RRULE:FREQ=YEARLY;UNTIL=20350921
2019-10-22 10:51:44,820 ERROR  25 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
2019-10-22 10:51:44,822 ERROR  25 OutlookGoogleCalendarSync.Console [0] -  String was not recognized as a valid DateTime.
2019-10-22 10:51:44,862 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [0] -  System.FormatException: String was not recognized as a valid DateTime.
2019-10-22 10:51:44,863 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131537;-2146233033
2019-10-22 10:51:44,863 ERROR  25 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
   at OutlookGoogleCalendarSync.Recurrence.buildOutlookPattern(Event ev, AppointmentItem ai, RecurrencePattern& oPattern)
   at OutlookGoogleCalendarSync.Recurrence.CompareOutlookPattern(Event ev, RecurrencePattern& aiOpattern, Direction syncDirection, StringBuilder sb, Int32& itemModified)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)

```

**Steps to Reproduce the Issue**  

Was not issue prior to alpha upgrade. Only occurs for one profile that is GC -> Outlook. Other GC -> Outlook works fine. 

Other yearly recurring do not error out so I am guessing it has to do with a yearly recurring that contain an end year (e.g. 2035)?

**Any other information**  

Related issues?

https://github.com/phw198/OutlookGoogleCalendarSync/issues/5
https://github.com/phw198/OutlookGoogleCalendarSync/issues/21
https://github.com/phw198/OutlookGoogleCalendarSync/issues/32

**Comment by jondavis9898** [comment]
Also encountering this with v2.8.2.0 Alpha and was not prior to this version.

Will email full log.

The event is recurring (2 days per week) and ends 12/31/2019.

**Comment by AgentP2** [comment]
I have the same issue. 
There's the problem that every sync comes with a pop-up. It would be nicer if the informations would be displayed over the Windows Notification Center. Then the sync will continue without any intervention.

**Comment by camdecoster** [comment]
I'm getting this same issue with two different appointments. It happens with one calendar going from Google to Outlook. I'm also using the portable version of v2.8.2.0 Alpha. I believe this is the relevant log info:

```
2019-11-07 13:06:51,459 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing recurring master appointment.
2019-11-07 13:06:51,460 DEBUG  21 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 12/21/2018 (R) => "Appointment Name"
2019-11-07 13:06:51,503 DEBUG  21 OutlookGoogleCalendarSync.Recurrence [0] -  Converting RRULE:FREQ=WEEKLY;UNTIL=20200103;INTERVAL=2;BYDAY=FR
2019-11-07 13:06:51,522 ERROR  21 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
2019-11-07 13:06:51,522 ERROR  21 OutlookGoogleCalendarSync.Console [0] -  String was not recognized as a valid DateTime.
2019-11-07 13:06:51,530 ERROR  21 OutlookGoogleCalendarSync.OGCSexception [0] -  System.FormatException: String was not recognized as a valid DateTime.
2019-11-07 13:06:51,530 ERROR  21 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131537;-2146233033
2019-11-07 13:06:51,530 ERROR  21 OutlookGoogleCalendarSync.OGCSexception [0] -     at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at System.DateTime.ParseExact(String s, String format, IFormatProvider provider, DateTimeStyles style)
   at OutlookGoogleCalendarSync.Recurrence.buildOutlookPattern(Event ev, AppointmentItem ai, RecurrencePattern& oPattern)
   at OutlookGoogleCalendarSync.Recurrence.CompareOutlookPattern(Event ev, RecurrencePattern& aiOpattern, Direction syncDirection, StringBuilder sb, Int32& itemModified)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
```

**Comment by phw198** [comment]
This is a bug (introduced by #799) where recurrence end time is assumed to always have a time element - which is not true.

:package: This should now be resolved with [hotfix v2.8.2.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/3828371/v2.8.2.3.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by jondavis9898** [comment]
@phw198 - Confirmed that 2.8.2.3 resolves the issue.  Thank you!!

**Comment by camdecoster** [comment]
@phw198 The hotfix took care of the issue for me. Thank you.

**Comment by fogoat** [comment]
Thanks for the fix. I was going to say, this issue only occurred if I modified an existing appointment where the `FREQ=YEARLY` changed to `FREQ=YEARLY;UNTIL=20350921`. I think this was the case for newly created recurring events as well.

**Comment by phw198** [comment]
This issue will be closed once the fix is released to alpha.
