### ISSUE TITLE
Alpha release 2.8.3 won't download

### ISSUE THREAD

**Issue by jcagpn** [phw198/OutlookGoogleCalendarSync#926]
Can't access Alpha 2.8.3 to test it.  Tried the auto download multiple times but it fails to download.  Went to website but can't find 2.8.3 to instal
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3976289/OGcalsync.log)
l.
John

**Comment by phw198** [comment]
```
2019-12-24 17:37:51,571 DEBUG  18 OutlookGoogleCalendarSync.Updater [0] -  Download complete.
2019-12-24 17:37:51,571 DEBUG  18 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=83cd7f98ca21f1ddcaa6155e06125009&ec=squirrel&ea=download&el=from%3D2.8.2.0%3Bto%3D2.8.3.0%3Bsuccessful
2019-12-24 17:37:51,571 INFO  18 OutlookGoogleCalendarSync.Updater [0] -  Applying the updated release...
2019-12-24 17:37:52,492 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  System.TypeLoadException: Could not load type 'SharpCompress.Readers.ExtractionOptions' from assembly 'SharpCompress, Version=0.23.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'.
2019-12-24 17:37:52,618 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131522;-2146233054
2019-12-24 17:37:52,649 ERROR  18 OutlookGoogleCalendarSync.OGCSexception [0] -     at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
2019-12-24 17:37:52,666 DEBUG  18 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=83cd7f98ca21f1ddcaa6155e06125009&ec=squirrel&ea=download&el=%3Bfailed
2019-12-24 17:37:52,666 ERROR  18 OutlookGoogleCalendarSync.Updater [0] -  Failed upgrading OGCS. Could not load type 'SharpCompress.Readers.ExtractionOptions' from assembly 'SharpCompress, Version=0.23.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'.
```

**Comment by phw198** [comment]
Dependencies are broken in Squirrel: https://github.com/Squirrel/Squirrel.Windows/issues/1253

Reverting to SharpCompress v0.20.0

**Comment by phw198** [comment]
This will be fixed in the next release - ie upgrading _from_ v2.8.4.

In the meantime, you'll need to upgrade manually by [downloading the `setup.exe`](https://github.com/phw198/OutlookGoogleCalendarSync/releases/download/v2.8.3-alpha/Setup.exe).
