### ISSUE TITLE
Alpha Release 2.8.3.0 upgrade fails

### ISSUE THREAD

**Issue by dutch55** [phw198/OutlookGoogleCalendarSync#927]
Selecting the upgrade option from the application fails, and also fails when I download the upgrade and attempt to apply it. I am posting this as a separate bug report from the bug report about the download failing, because I think in my case the download works.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/3979861/OGcalsync.log)

**Comment by kwagner115** [comment]
I can also report the exact same failure and success as described above. The upgrade failure has also been an issue for me for many previous versions (alpha and beta). I did not report previously as I was unsure the problem wasn't unique to me.
```
2019-12-16 05:58:27,530 DEBUG  11 OutlookGoogleCalendarSync.Updater [0] -  Download started...
2019-12-16 05:58:28,749 DEBUG  11 OutlookGoogleCalendarSync.Updater [0] -  Download complete.
2019-12-16 05:58:28,749 DEBUG  11 OutlookGoogleCalendarSync.Telemetry [0] -  Retrieving URL: https://www.google-analytics.com/collect?v=1&t=event&tid=UA-19426033-4&aip=1&cid=0f16f3ad53964d26d71ea7606de951c5&ec=squirrel&ea=download&el=from%3D2.8.2.14%3Bto%3D2.8.3.0%3Bsuccessful
2019-12-16 05:58:28,796 INFO  11 OutlookGoogleCalendarSync.Updater [0] -  Applying the updated release...
2019-12-16 05:58:28,999 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -  System.TypeLoadException: Could not load type 'SharpCompress.Readers.ExtractionOptions' from assembly 'SharpCompress, Version=0.23.0.0, Culture=neutral, PublicKeyToken=afb0a02973931d96'.
2019-12-16 05:58:28,999 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80131522;-2146233054
2019-12-16 05:58:28,999 ERROR  11 OutlookGoogleCalendarSync.OGCSexception [0] -     at Squirrel.DeltaPackageBuilder.ApplyDeltaPackage(ReleasePackage basePackage, ReleasePackage deltaPackage, String outputFile)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass8_0.<createFullPackagesFromDeltas>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<createFullPackagesFromDeltas>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<ApplyReleases>d__9.MoveNext()
```

**Comment by phw198** [comment]
Hi @dutch55 Thanks for reporting, but the underlying issue is the same as #926 

@kwagner115 A shame you didn't report this when you noticed, as it's been broken since I updated all the DLLs in v2.8.1 :slightly_frowning_face:
