### ISSUE TITLE
Outlook ResponseStatus inaccessible - "Something went wrong. You may want to try again"

### ISSUE THREAD

**Issue by DamianEdwards** [phw198/OutlookGoogleCalendarSync#972]
**OGCS Version**: v2.8.3-alpha  
**Edition**: Installed
**Sync Direction**: O->G

**Bug Description**  
Sync starting failing 10 days ago (March 18th, 2020) with error "Value cannot be null. Parameter name: source". After updating to 2.8.3-alpha the specific error message is no longer displayed in the UI but you can see it in the log. Screen shot:

![image](https://user-images.githubusercontent.com/249088/77837323-b2bd6100-711c-11ea-8580-7cd435618e67.png)

**Steps to Reproduce the Issue**  
It happens on any sync attempt. I tried changing back to manual sync (from push sync) and it still fails the same way.

**Any other information**  
:paperclip: `OGcalsync.log` file is at https://gist.github.com/DamianEdwards/5383cd9d33c028f76536007910eed2b6

**Comment by phw198** [comment]
Excerpt from your log:
```
2020-03-28 17:47:05,640 ERROR  28 OutlookGoogleCalendarSync.OGCSexception [0] -  System.Runtime.InteropServices.COMException: Sorry, something went wrong. You may want to try again.
2020-03-28 17:47:05,642 ERROR  28 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0xAC570057;-1403584425
2020-03-28 17:47:05,642 ERROR  28 OutlookGoogleCalendarSync.OGCSexception [0] -     at Microsoft.Office.Interop.Outlook._AppointmentItem.get_ResponseStatus()
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.FilterCalendarEntries(Items OutlookItems, Boolean filterBySettings, Boolean noDateFilter, String extraFilter, Boolean suppressAdvisories)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.GetCalendarEntriesInRange(Boolean suppressAdvisories)
   at OutlookGoogleCalendarSync.Sync.Engine.synchronize()
   at OutlookGoogleCalendarSync.Sync.Engine.<>c__DisplayClass20_0.<Start>b__0(Object o, DoWorkEventArgs args)
```
So it seems you have the filter set to only sync invites that you have responded to, but for at least one item, this attribute cannot be accessed.

:package: This [hotfix v2.8.3.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4583408/v2.8.3.10.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)) should now skip filtering any such appointments and continue.

Please let me know how it goes.

**Comment by phw198** [comment]
@DamianEdwards Any feedback on the fix?
